### ISSUE TITLE
Change the name of the add-ins that are built

### ISSUE THREAD

**Issue by topowright** [Esri/coordinate-conversion-addin-dotnet#110]
ArcMap: 
CoordinateConversion.esriAddIn

ArcGIS Pro: 
CoordinateConversion.esriAddInX

**Comment by conklinbd** [comment]
Is there a reason the product name is in the AddIn name? 

I don't see the point.

**Comment by topowright** [comment]
I take it that the extension keeps it unique. Good catch.

**Comment by topowright** [comment]
fixed.

**Comment by jmccausland** [comment]
when are we going to be done changing the name of things.  Do we realize this will require updates to other repos and the Jenkins build?
