### ISSUE TITLE
Change the Map Point Tool icon

### ISSUE THREAD

**Issue by topowright** [Esri/coordinate-conversion-addin-dotnet#113]
Change the map point tool to use the 16 bit image not the 32 bit image. This is based on the feedback from graphics.

**Comment by jmccausland** [comment]
There are a few other icons where we are using 32x32.  If we are going to update them to 16x16 then I think we should do them all.

**Comment by jmccausland** [comment]
pull request waiting #114

**Comment by dhagens** [comment]
Working on another project right now.  Will get to it when I’m done.  Thanks.

**Comment by jmccausland** [comment]
addressed in #114, verify and close

**Comment by jmccausland** [comment]
No one verified, closing
