### ISSUE TITLE
Same coordinate shows different locations. 

### ISSUE THREAD

**Issue by topowright** [Esri/coordinate-conversion-addin-dotnet#128]
When taking a coordinate from ArcMap add-in to ArcGIS Pro add-in the coordinate/location does not come up the same; however, if I take a coordinate from ArcGIS Pro to ArcMap everything works fine. Any ideas? This is the coordinate I used: 38 53.2788N 076 56.9070W

38 53.2788N 076 56.9070W

**Comment by jmccausland** [comment]
Fix merged, please verify at next build
