### ISSUE TITLE
Collect Tab - Clear Graphics is not clearing points.

### ISSUE THREAD

**Issue by pshowalter** [Esri/coordinate-conversion-addin-dotnet#133]
After using Map Point tool to collect points, the "Clear Graphics" button is clicked and nothing happens. Tried selecting, highlighting etc.

Right click in the pane will allow Delete (_selected_), and Delete All, and Flash
![image](https://cloud.githubusercontent.com/assets/6842145/18060190/06cde078-6deb-11e6-8ec8-bcb49c6802b5.png)

Right click in the pane will allow Delete (_selected_), and Delete All, and Flash
![image](https://cloud.githubusercontent.com/assets/6842145/18060241/4fb6b4f4-6deb-11e6-848d-bffe9a34840d.png)

**Comment by jmccausland** [comment]
Known issue

**Comment by jmccausland** [comment]
removed button
