### ISSUE TITLE
DD/DDM/DMS Conversion does not work for region settings with "," decimal separator

### ISSUE THREAD

**Issue by mfunk** [Esri/coordinate-conversion-addin-dotnet#134]
Reported by Esri Spain via Tech Support:

The Coordinate Conversion ArcMap 1.0.1 add-in fails to populate the DMS, DD, and DDM fields if the region is set to use a comma as the decimal separator.
1. From the control panel > Region and language > Additional settings > Numbers tab > Decimal symbol ','> OK > OK
2. Download the add-in from:
http://solutions.arcgis.com/defense/templates/coordinate-conversion/#Download
3. Install it.
4. From the 'customize' menu > customize mode > commands tab > search for 'coordinate conversion'
5. Drag it to any existing toolbox
6. Open any existing map in Arcmap > click on the icon 'show coordinate conversion'
7. Type any coordinate or use the 'map point tool'
9. The DMS, DD and DDM will not display.
10. See video:
http://screencast-o-matic.com/watch/cDjvIgjnQ4

@topowright

**Comment by Dbarnes1** [comment]
As I'm working on doc for d&d I was able to verify that this works now, closing.
