### ISSUE TITLE
Coordinate Conversion in ArcGIS Pro Issue

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/coordinate-conversion-addin-dotnet#137]
_From @joebayles on October 14, 2016 21:57_

## Expected Behavior

When typing in an MGRS coordinate string, the Coordinate Conversion Add-In will accurately display the location and convert to another supported coordinate system.
When using a four-digit coordinate (i.e. 11SNT6963), the Add-In should:
- identify the nexus of the 69 easting and 63 northing in the NT grid square of the 11S grid zone
- display the complete MGRS Coordinate (11SNT6900063000) and the converted coordinate in any other identified coordinate system.
## Current Behavior

When using a four-digit coordinate (i.e. 11SNT6963), the Add-In currently:
- identifies the nexus of the 00069 easting and 00063 northing in the NT grid square of the 11S grid zone
- displays the complete but incorrect MGRS Coordinate (11SNT0006900063) and the converted incorrect coordinate in any other identified coordinate system.

**Essentially, the extra zeroes are being added to the front of the number, instead of the back.**
## Screenshots

![image](https://cloud.githubusercontent.com/assets/5016557/19402035/93b762ce-9213-11e6-8021-5ba8498c9bb1.png)

![image](https://cloud.githubusercontent.com/assets/5016557/19402288/29f21530-9215-11e6-943f-7586fe9d94b6.png)
## Steps to Reproduce (for bugs)

1. Start ArcGIS Pro
2. Navigate to Coordinate Conversion Add-In
3. Type in coordinate
## Context

Inaccurate coordinate conversion not only make this tool useless, but hazardous if used.
## Environment

- Coordinate Conversion 1.0.1
- ArcGIS Pro 1.3.1 and ArcGIS Pro 1.4 (build 6926)
- _ArcMap (10.4.1 and 10.5) works as intended_
- Windows 10

@nfeuerstein @lfunkhouser @karlterrey FYI

_Copied from original issue: Esri/military-tools-for-arcgis#33_

**Comment by lfunkhouser** [comment]
_From @joebayles on October 14, 2016 21:57_

Copied from https://github.com/ArcGIS/solutions-desktop-templates/issues/271

**Comment by lfunkhouser** [comment]
_From @nfeuerstein on October 15, 2016 0:3_

Thank you Joe.  Added the showstopper tag and adding to backlog to be addressed next sprint.

**Comment by lfunkhouser** [comment]
_From @mfunk on October 28, 2016 13:37_

@lfunkhouser @nfeuerstein 
This will be fixed in the coordinate-conversion-addin-dotnet repo:
https://github.com/Esri/coordinate-conversion-addin-dotnet

**Comment by mfunk** [comment]
@joebayles @nfeuerstein 

Just want you guys to check off on this. So what we really want is support for 100,000m grids, 10,000m grids, 1,000m grids, 100m grids, 10m grids in addition to the standard 1m grid. What I mean is:

| Grid Size | As Entered | As 15-digit |
| --- | --- | --- |
| 100,000m grid | 11SMT | 11SMT0000000000 |
| 10,000m grid | 11SMT90 | 11SMT9000000000 |
| 1,000m grid | 11SMT9902 | 11SMT9900002000 |
| 100m grid | 11SMT991024 | 11SMT9910002400 |
| 10m grid | 11SMT99150243 | 11SMT9915002430 |
| 1m grid | 11SMT9915302431 | 11SMT9915302431 |

According to NGA's [Web Geographic Translator](http://egeoint.nrlssc.navy.mil/web_geographic_translator/faces/tabbed_transform.jsp) these should correspond to 117 0 32.8W 33 27 40.8N.

Is this acceptable?

@lfunkhouser 
@jrweakland 
@jmccausland

**Comment by nfeuerstein** [comment]
Yes'ir.  That's right.

**Comment by mfunk** [comment]
Fixed and closed in #136 and #138.
