### ISSUE TITLE
Branch needed for ArcGIS Pro 1.2 Support

### ISSUE THREAD

**Issue by topowright** [Esri/coordinate-conversion-addin-dotnet#142]
Currently our Dev branch supports current development and Master branch should support the latest release. I have been asked by @dhagens to create this issue to allow us to understand the effort that is needed for taking the code that was compiled in ArcGIS Pro 1.3 and moving it to ArcGIS Pro 1.2. 

Due to changes in the API this work is necessary before any bugs can be addressed in ArcGIS Pro 1.2

**Comment by nfeuerstein** [comment]
@dhagens @topowright verifying that the bug fixes in 1.2 are only for Coordinate Conversion and Military Symbol Editor add-ins.  Distance and Direction and Visibility are dead at 1.2.  Correct?

**Comment by dhagens** [comment]
Only creating the 1.2 branch for Coordinate Conversion at this time to allow us to work on the Coordinate Conversion 1.2 bugs.

**Comment by topowright** [comment]
@nfeuerstein that is what I understand based on the MTA presentation given earlier this week. Thank you for bringing that up for clarification.

**Comment by dhagens** [comment]
ArcGIS Pro 1.2 branch has been created and the current code has been modified to work with the 1.2 API.  For any 1.2 bug fixes, we'll need to make those changes to the ArcGIS_Pro_1.2 branch in CoordinateConversion.  The fix will also need to go into the dev branch as well.
