### ISSUE TITLE
Coordinate Conversion: should clear all outputs when invalid coordinate is entered (ArcGIS Pro)

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/coordinate-conversion-addin-dotnet#151]
_From @elinz on December 14, 2016 16:53_

**NOTE: This is an enhancement, but a very critical enhancment**

When you specify an invalid coordinate in the Input textbox, any previous calculated results in the Output texboxes are not cleared. The last valid output is still displayed. This is extremely dangerous as the user may not have realized they entered an invalid coordinate or did not realize that the output values didn't change from the last valid coordinate entered; they will then copy the outputs to use in other applications thinking they copied valid values.

Example:
The user enters the following valid MGRS coordinate: 34PFR1459853908
The output textboxes are updated to display the output coordinates...
![image](https://cloud.githubusercontent.com/assets/4635490/21191094/ec1f9ce8-c1d8-11e6-81f0-b8b348fead74.png)

Then the user enters the following invalid MGRS coordinate, either because the user was given an invalid MGRS coordinate or maybe they did a copy/paste from a report and didn't copy all the coordinates: 34KGE358193443 
(it's invalid because it's missing the 10th digit in the easting/northing; perfect example of a copy/paste issue)...
![image](https://cloud.githubusercontent.com/assets/4635490/21191285/7b44ceac-c1d9-11e6-8f99-0327ee7fb68f.png)

Note that the output textboxes retained the previously calculated outputs values.

This issue applies to all versions of Pro. Also applies to ArcMap - separate issue will be logged.

## Expected Behavior

When a user enters an invalid coordinate, all output textboxes should be cleared to prevent them from copying invalid output coordinates.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

_Copied from original issue: Esri/military-tools-for-arcgis#86_

**Comment by Dbarnes1** [comment]
Verified fixed. 

![image](https://cloud.githubusercontent.com/assets/13024357/21429826/5a137250-c815-11e6-9368-2005a274f35e.png)
