### ISSUE TITLE
Coordinate Conversion Add-in generates bad grid when tool settings are set to "Default Map Unit" as Display Coordinate

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/coordinate-conversion-addin-dotnet#153]
_From @migueldls on December 13, 2016 22:32_

Grids are not accurate using the Map Point Tool when the Coordinate Conversion tool settings are set as "Default Map Unit" in the Display Coordinate settings. When the Map or Data Frame is set to any projection other than WGS84 Web Mercator coordinates not accurate or correct. Problem persists in both ArcMap and ArcPro. If is set the map or data frame to eg. WGS84 UTM 13N projection,  I get 31RE0000000000 in an area that should be 13RCR0000000000.
![coordinate conversion - bad grids](https://cloud.githubusercontent.com/assets/23364449/21162121/917761ec-c140-11e6-87f8-2e747547a92f.png)

## Expected Behavior

Should get accurate grids using the Map Point Tool in any projection or at least at a minimum get accurate grids when map or data-frame is set to any WGS84 projection.
## Current Behavior

 I get 31RE0000000000 in an area that should be 13RCR0000000000. Using the Map Point Tool in both ArcMap 10.4.1 and ArcPro 1.4
## Steps to Reproduce (for bugs)

1. In ArcPro add map set to Web Mercator prj. Add map set to WGS84 UTM zone 13N.
2. Pan to El Paso, TX.
3. Open CC Add-in, set display coordinate to "Default Map Unit"
4. Check Grids using Map Point Tool
5. Same process for ArcMap, change dataframe coordinate system to WGS84 UTM zone 13N. Verify problem persits.

## Your Environment

* Version used: ArcMap 10.4.1, ArcPro 10.4 (7160)
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile): Windows 7 En.
* Link to your project:

_Copied from original issue: Esri/military-tools-for-arcgis#85_

**Comment by jmhauck** [comment]
@migueldls as I was looking at another issue I noticed that the commit for this was not quite correct. You should see the correct values reported but the wkid is incorrectly being included in the display string shown in the Input box. Will need to do another commit.

**Comment by migueldls** [comment]
@jmhauck Yeah I noticed the wkid, and verified the fix for both ArcMap, ArcPro just now. I re-check after the commit for the wkid but this issue seems good now. ?..Does this tool only accept a Projected spatial reference with uniits in (meters)?

**Comment by jmhauck** [comment]
@migueldls it should accept projected coordinate values regardless of the linear unit.

**Comment by migueldls** [comment]
@jmhauck, I verified the fix in ArcMap 10.4.1 and Pro 1.4 this issue now works as expected in both. Tool outputs correct coordinates using "default map" setting and I don't see the wkid in the display.
