### ISSUE TITLE
Coordinate Conversion - ArcMap 10.3.1 addin not creating same output as Pro 1.4 addin

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/coordinate-conversion-addin-dotnet#154]
_From @elinz on December 12, 2016 20:1_

I tested the ArcMap 10.3.1 addin that was built from the dev branch and the coordinates are not matching the output from the Pro 1.4 that was built from the same dev branch. Addins built 12 Dec 2016 09:11.

Enter the following coordinates: -116.299264 36.103061

In Pro 1.4 addin the output is:
![image](https://cloud.githubusercontent.com/assets/4635490/21114436/eed4b658-c061-11e6-9300-1f814e58933b.png)

In ArcMap 10.3.1 addin the output is:
![image](https://cloud.githubusercontent.com/assets/4635490/21114459/0330fd5a-c062-11e6-8020-84fa25894554.png)

Using the "Go To XY" tool in ArcMap, I entered the same long lat coordinate...
![image](https://cloud.githubusercontent.com/assets/4635490/21114471/0ce0aaee-c062-11e6-8dec-5fd81988a270.png)

NOTE: Pro 1.2 addin built on 1.2 and Pro 1.4 addin built on 1.4 are creating the same output.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

_Copied from original issue: Esri/military-tools-for-arcgis#83_

**Comment by lfunkhouser** [comment]
_From @dhagens on December 12, 2016 20:44_

@elinz, it would be useful to know which values are actually correct from your testing.

**Comment by lfunkhouser** [comment]
_From @elinz on December 13, 2016 0:5_

@dhagens Here is one correct, where ArcGIS Pro 1.4 and ArcMap 10.3.1 addin match:

45.47E 20.82S

ArcGIS Pro 1.4:
![image](https://cloud.githubusercontent.com/assets/4635490/21122028/b7098ad2-c084-11e6-9c0c-639165d13d09.png)

ArcMap 10.3.1:
![image](https://cloud.githubusercontent.com/assets/4635490/21122033/c368e96c-c084-11e6-9b06-16a34b372001.png)

**Comment by lfunkhouser** [comment]
_From @elinz on December 13, 2016 16:24_

@dhagens Another example of an incorrect match between ArcGIS Pro 1.4 addin and ArcMap 10.3.1 addin:

120.56879W 45.56789N

ArcGIS Pro:
![image](https://cloud.githubusercontent.com/assets/4635490/21147845/2a95d9d4-c10b-11e6-9db1-483b14f2e859.png)

ArcMap:
![image](https://cloud.githubusercontent.com/assets/4635490/21147857/37ac6066-c10b-11e6-8064-f1cce2c08196.png)

Take for example, DDM. 
![image](https://cloud.githubusercontent.com/assets/4635490/21148159/373f98a4-c10c-11e6-961a-dd739dbe82f4.png)

![image](https://cloud.githubusercontent.com/assets/4635490/21148321/a847c59e-c10c-11e6-9a7c-81ab77dbdad3.png)

If I then create a custom DDM (i.e. DDM_Customer_2places) in ArcMap, this still doesn't give me more precision in the coordinate. I still get the same coordinate using the default DDM (i.e. 45 34.2N, 120 34.2W)...
![image](https://cloud.githubusercontent.com/assets/4635490/21148545/71c6963e-c10d-11e6-9725-6fdbe94e2a3c.png)

**Comment by dhagens** [comment]
This issue has been fixed and is ready for testing.

**Comment by elinz** [comment]
@dhagens I will test this fix with the next Jenkins build addin. Thanks.

**Comment by elinz** [comment]
@dhagens I tested the addin built on 10.3.1 ArcObjects and 1.4 SDK dated 15 Dec 2016 09:06 on ArcMap 10.3.1 and ArcGIS Pro 1.4 and they are creating the same output. Thanks for the fix. Closing this issue.
