### ISSUE TITLE
Coordinate Conversion: losing positional accuracy between coordinate formats (ArcGIS Pro)

### ISSUE THREAD

**Issue by elinz** [Esri/coordinate-conversion-addin-dotnet#157]
**This is an extremely important bug**

The addin is not maintaining the same input coordinate positional accuracy in the output values for DD, DDM, and DMS.

For example, if I set the default map unit in the addin to "DD" and using the Map Point tool, add the location of Sevastopol as the input value. See screenshot below:
![image](https://cloud.githubusercontent.com/assets/4635490/21206989/59409994-c21a-11e6-9451-c9a7721e72be.png)

The addin sets the input value to 44.608559N 033.528627E; (6 decimal places lat/long). Which using the calculator at [NGA](http://msi.nga.mil/MSISiteContent/StaticFiles/Calculators/degree.html) to determine the length of a degree of latitude and longitude at 45 degrees, I calculate that storing a coordinate down to 6 decimal places will allow a location to be stored down below a 1/10 of a meter (i.e. 0.11 meters of latitude and 0.08 meters of longitude). See snapshot of my spreadsheet below:
![image](https://cloud.githubusercontent.com/assets/4635490/21207152/4afad2c2-c21b-11e6-81ed-63eda986e410.png)

However, the default formatting for DD, DDM, and DMS do not allow us to output the coordinate down to the same accuracy.
- The output for DD displays out to 2 decimal places, only gets us down to approx. 1,111 meters of latitude and approx. 788 meters of longitude (see screenshot above).

- The output for DDM displays the decimal minute out to 2 decimal places, which based on my calculations, gets us down to approx. 18 meters of latitude and approx. 13 meters of longitude.
![image](https://cloud.githubusercontent.com/assets/4635490/21207370/cf26a2fa-c21c-11e6-9c59-a7f04465d590.png)

- The output for DMS displays seconds out to a single decimal place, which based on my calculations, gets us down to approx. 3 meters of latitude and 2 meters of longitude.
![image](https://cloud.githubusercontent.com/assets/4635490/21207446/eccca002-c21c-11e6-9762-e6477a8ba3f2.png)

The default configuration of the output coordinate formats should not store a less accuracy position then the user has entered. If the user wants to add custom formats and change the number of decimal places that's fine, but out of the box, the addin must calculate the same positional accuracy

Another example, would be the user entering the MGRS coordinate down to the meter, such as 36TWQ4194739604 (Sevastopol location specified above) and asking for DD, DDM, or DMS as the output. We are not providing the same coordinate back to the user.

**Comment by elinz** [comment]
@jmhauck The default formatting for DD was not altered to handle 6 decimal places. It's still the original 2 decimal places:
![image](https://cloud.githubusercontent.com/assets/4635490/21441816/f5a8cd58-c84e-11e6-94fc-3985db53458a.png)

**Comment by jmhauck** [comment]
@elinz I will need to check why it is automatically switching to "Custom" and why that is still showing the old format there. You should see the new default format when you select the example coordinate from the Formats list...in this case "70.49N 40.32W".

Would it also be better to just say "Default" in the formats list rather than showing an example there and another example below the Formats list...that don't even show the same coordinate?

**Comment by elinz** [comment]
@jmhauck Yes, lets make the change so the default format is listed as "Default" instead of showing a coordinate pair in the format list.

**Comment by jmhauck** [comment]
@elinz ok, sounds good.

**Comment by jmhauck** [comment]
@elinz  In terms of using the word Default for each. The code is currently using those example values as a unique key for looking up and storing the formats. Anything can be changed but this would require a fair bit of effort. As a possible alternative I switched them to be "Default DD" and "Default DDM" for example so they would retain the unique nature and avoid showing an additional coordinate value. Please let me know what you think and if we need to alter any further.

**Comment by elinz** [comment]
@jmhauck Ok. Understand the issue. The alternative of using "Default DD", "Default DDM" is a good alternative.

**Comment by jmccausland** [comment]
@elinz @jmhauck FYI the format list box was intended to have more than two options.  These options are defaulted when there are no formats found in the assembly .config file.  A request went out to the team over a year ago on what 'configured' formats should be in the list box for each coordinate type.  We received ZERO feedback so that's why there is only two, the default and custom.

**Comment by jmhauck** [comment]
@jmccausland that makes sense why the sample coordinate value would be used. Would be easy to see differences between each example format for each category without having to click on them. Do you think that will come back up again? Should we switch back to the previously used coordinate value rather than the text that was just added?

**Comment by jmccausland** [comment]
As soon as a user reads the readme file and modifies the config file with their defaults, it would probably break.

**Comment by jmhauck** [comment]
@jmccausland ok...I can switch them back.

**Comment by elinz** [comment]
@jmhauck @jmccausland if we're going to keep the default name as before (for DD, DDM, and DMS), for example, 70.49N 40.32W for DD then should we change the label to match the altered formatting?

![image](https://cloud.githubusercontent.com/assets/4635490/21697898/6a175ff6-d349-11e6-98e2-ad55820d1f9a.png)
For the default DD format, we changed so that up to 6 decimal places would display in the output. Based on the default label of 70.49N 40.32W the user would expect that this format would only display out to 2 places. So they would need to click on Advanced to see the correct formatting.

Thoughts?

**Comment by jmhauck** [comment]
@elinz The labels are updated to reflect the new default format.

**Comment by elinz** [comment]
@jmhauck Verified this is working on Pro addin build 10 Jan 2017 05:53 on ArcGIS Pro 1.4 final build.

- Verified that the default DD format is set to display up to 6 significant digits.
- Verified that the default DDM format is set to display up to 4 significant digits.
- Verified that the default DMS form is set to display up to 2 significant digits.
- Performed the following test:
1. Entered the MGRS coordinate:10TET4889274330
DD: 47.620528N 122.349328W
DDM: 47° 37.2317'N 122° 20.9597'W
DMS: 47° 37' 13.9"N 122° 20' 57.58"W
GARS: 116MM35
MGRS: 10TET4889274330
USNG: 10TET4889274330
UTM: 10T 548892 5274330

2. Took the DD output (47.620528N 122.349328W) from #1 above and entered as input. The output
is shown below:
DD: 47.620528N 122.349328W
DDM: 47° 37.2317'N 122° 20.9597'W
DMS: 47° 37' 13.9"N 122° 20' 57.58"W
GARS: 116MM35
MGRS: 10TET4889274330
USNG: 10TET4889274330
UTM: 10T 548891 5274329 <- 1 meter different, but believe this is just a rounding issue.

3. Took the DDM output (47° 37.2317'N 122° 20.9597'W) from #1 above and entered as input. The output
is shown below:
DD: 47.620528N 122.349328W
DDM: 47° 37.2317'N 122° 20.9597'W
DMS: 47° 37' 13.9"N 122° 20' 57.58"W
GARS: 116MM35
MGRS: 10TET4889274330
USNG: 10TET4889274330
UTM: 10T 548891 5274330 <- 1 meter different, but believe this is just a rounding issue.

4. Took the DMS output (47 37 13.9N 122 20 57.58W) from #1 above and entered as input. The output is shown below:
DD: 47.620528N 122.349328W
DDM: 47° 37.2317'N 122° 20.9597'W
DMS: 47° 37' 13.9"N 122° 20' 57.58"W
GARS: 116MM35
MGRS: 10TET4889274330
USNG: 10TET4889274330
UTM: 10T 548891 5274329 <- 1 meter different, but believe this is just a rounding issue.

Closing issue.
