### ISSUE TITLE
Coordinate Conversion ArcGIS Pro Add-In Version Number

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/coordinate-conversion-addin-dotnet#160]
_From @joebayles on October 14, 2016 23:0_

The Add-In included in the Coordinate Conversion 1.0.1 download is labeled as 1.0. Not sure if this is:
- Incomplete number in the Add-In Installation Utility
- Wrong version

![image](https://cloud.githubusercontent.com/assets/5016557/19404955/4bc1cbb2-9227-11e6-81ee-1a612128b6e7.png)

FYI @nfeuerstein @lfunkhouser 

_Copied from original issue: Esri/military-tools-for-arcgis#35_

**Comment by lfunkhouser** [comment]
_From @topowright on October 18, 2016 16:26_

@joebayles good catch. 

@nfeuerstein @lfunkhouser this should be added to the backlog or should it just be done outside the other work? Not sure how we are addressing bugs under the new system.

**Comment by lfunkhouser** [comment]
_From @nfeuerstein on October 18, 2016 17:53_

@topowright definitely added to the backlog.  Anyone can add something to the backlog under the "for review" section and I'll prioritize it appropriately.

**Comment by lfunkhouser** [comment]
_From @topowright on October 18, 2016 21:0_

@nfeuerstein Thanks for the info.

**Comment by lfunkhouser** [comment]
_From @topowright on October 18, 2016 21:2_

This has been added to the backlog for review.

**Comment by mfunk** [comment]
Still seeing this for 1.2 in today's 9am build.

![image](https://cloud.githubusercontent.com/assets/3093182/21653573/a29ae868-d266-11e6-844f-b8e0e36a6af5.png)

**Comment by topowright** [comment]
Verified
