### ISSUE TITLE
Holistic Testing - Coordinate Conversion Tool - ArcGIS Pro 1.2

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/coordinate-conversion-addin-dotnet#163]
_From @abrowning80 on November 4, 2016 19:2_

## Expected Behavior
Selection arrow for Coorrdinates when activated should allow the user to select where they want coordinates of.

## Current Behavior
As soon as the arrow is dragged on the map it takes the 1st coordinates it can and does not allow the user to select a different location.

## Steps to Reproduce (for bugs)

1.  Open up Coordinate conversion tool.
2.  Select Map point tool
3.  Move arrow over map, coordinates will be chosen as soon as the arrow gets on to the map.
4.

## Your Environment
* Version used: ArcPro 1.2
* Environment name and version (e.g. Chrome 39, node.js 5.4): 
* Operating System and version (desktop or mobile): Windows 8 desktop
* Link to your project:

_Copied from original issue: Esri/military-tools-for-arcgis#47_

**Comment by jmhauck** [comment]
Only tested Pro 1.4

**Comment by nfeuerstein** [comment]
@abrowning80 can you verify this is still an issue at 1.4?

This is how it should work:
1. choose the map tool
2. click a point on the map
3. map tool is disabled 
4. choose the map tool to choose a different point on the map

**Comment by nfeuerstein** [comment]
@joebayles please verify that this can/cannot be replicated in 1.4.  I'm not sure when @abrowning80 will be available to do so.
