### ISSUE TITLE
Copy format type of coordinates when copying coordinates

### ISSUE THREAD

**Issue by dfoll** [Esri/coordinate-conversion-addin-dotnet#168]
When you use the "copy all" button and then paste elsewhere we should insert the coordinate format next to the coordinate value.

Copying this 
![image](https://cloud.githubusercontent.com/assets/5322669/21246671/fb107cd4-c2de-11e6-88b5-24ce9b9a0782.png) 
and then pasting outputs this 

09 56.0507S 003 04.3261E
31LEK0790401864
31LEK0790401864
9° 56.05'S 3° 4.33'E
9° 56' 3.0"S 3° 4' 19.6"E

i think we should insert the format types next to them either like this

DDM 09 56.0507S 003 04.3261E
MGRS 31LEK0790401864
USNG 31LEK0790401864
DDM 9° 56.05'S 3° 4.33'E
DMS 9° 56' 3.0"S 3° 4' 19.6"E

or this

09 56.0507S 003 04.3261E DDM
31LEK0790401864 MGRS
31LEK0790401864 USNG
9° 56.05'S 3° 4.33'E DDM
9° 56' 3.0"S 3° 4' 19.6"E DMS

**Comment by joebayles** [comment]
@dfoll I would actually make it an option.

I had the same thought, but some people might not want that (especially if they are pasting into a spreadsheet or other form).

**Comment by topowright** [comment]
@dfoll @joebayles When we showed this to our users it would output this:
DDM 09 56.0507S 003 04.3261E
MGRS 31LEK0790401864
USNG 31LEK0790401864
DDM 9° 56.05'S 3° 4.33'E
DMS 9° 56' 3.0"S 3° 4' 19.6"E

We then changed it because they wanted to transpose the data. 

I think adding it as an option is a great idea.

**Comment by topowright** [comment]
This issue can be closed as wont fix

**Comment by joebayles** [comment]
@topowright
So, I just tried this by adding the names to the custom output:

|Custom Output|Actual Output|
|:---|:---|
|**MGRS** ZSX00000Y00000|MGREF 13TEF5269568108|
|**DMS** A0° B0' C0.0#"N X0° Y0' Z0.0#"E|DMN 41° 15' 45.63"N 104° 22' 15.36"W|
|ZSX00000Y00000 **MGRS**|13TEF5269568108 MGREF|
|A0° B0' C0.0#"N X0° Y0' Z0.0#"E **DMS**|41° 15' 45.63"N 104° 22' 15.36"W DMN|

I'm not sure about the development aspect, but even if you didn't hard-code the option, you could document that people could write it in if they wanted... That is, if the `EF` and `N` weren't there.
