### ISSUE TITLE
Poor tooltip name and description for Coordinate Conversion addin (ArcMap)

### ISSUE THREAD

**Issue by elinz** [Esri/coordinate-conversion-addin-dotnet#170]
When I hover over the Coordinate Conversion addin the following tooltip is displayed:
![image](https://cloud.githubusercontent.com/assets/4635490/21274272/2fa423c2-c37c-11e6-9331-87923abcf47b.png)

"Show Coordinate Conversion" - there is no reason to use the verb "Show". Users know that the tool will open or do something.

"Add-in command to show Coordinate Conversion Window." - This doesn't help the user at all. We should be describing what the user can do with the Coordinate Conversion addin. Look at other tools and see how they describe the tool.

**Comment by elinz** [comment]
Here is what we should use for the name and description for the tooltip...
![image](https://cloud.githubusercontent.com/assets/4635490/21360659/b3519850-c695-11e6-8952-e7fcc2247194.png)

**Comment by jmhauck** [comment]
Should have waited on this one until we start with the single addin. This change will need to be made there also I believe.

**Comment by jmhauck** [comment]
@kgonzago the change for the component level has been merged.

**Comment by nfeuerstein** [comment]
@kgonzago @jmhauck can this be moved to the validation stage?

**Comment by kgonzago** [comment]
@nfeuerstein yes. I'll reassign it back to @elinz for verification.

**Comment by elinz** [comment]
@jmhauck @nfeuerstein @kgonzago Installed build 22 Dec 2016 10:15 of the individual coordinate conversion addin and the name and description are good. See screenshot below:
![image](https://cloud.githubusercontent.com/assets/4635490/21439710/600a654a-c844-11e6-8f4e-9b614d447c68.png)

Closing issue.
