### ISSUE TITLE
Poor tooltip name and description for Coordinate Conversion addin (ArcGIS Pro)

### ISSUE THREAD

**Issue by elinz** [Esri/coordinate-conversion-addin-dotnet#171]
When I hover over the Coordinate Conversion addin the following tooltip is displayed:
![image](https://cloud.githubusercontent.com/assets/4635490/21275131/35c77c8c-c380-11e6-91c4-2fd869965fb8.png)

"Show Coordinate Conversion Dockpane" - there is no reason to use the verb "Show". Users know that the tool will open or do something. The description doesn't help the user at all. We should be describing what the user can do with the addin. Look at other tools and see how they describe the tool.

**Comment by elinz** [comment]
Here is what we should use for name and description on the tooltip...
![image](https://cloud.githubusercontent.com/assets/4635490/21360564/471af708-c695-11e6-9916-8cefdeaf7c6f.png)

**Comment by jmhauck** [comment]
Should have waited on this one until we start with the single addin. This change will need to be made there also I believe.

**Comment by kgonzago** [comment]
@jmhauck Tooltip To keep things consistent, please change the tooltip message at component level and I'll handle the single add-in.

**Comment by jmhauck** [comment]
Ok, thanks @kgonzago the change for the component level has been merged.

**Comment by nfeuerstein** [comment]
@jmhauck @kgonzago is this in the verify stage?

**Comment by kgonzago** [comment]
Assigning to @elinz for verification.

**Comment by elinz** [comment]
@kgonzago Installed the individual component build 22 Dec 2016 15:43 and verified that the name and description in the tooltip is correct; shown below:
![image](https://cloud.githubusercontent.com/assets/4635490/21443956/d36d43c2-c85d-11e6-9998-9eaabf155ad6.png)

Closing issue.
