### ISSUE TITLE
Coordinate Conversion: Add support for GEOREF (ArcGIS Pro)

### ISSUE THREAD

**Issue by elinz** [Esri/coordinate-conversion-addin-dotnet#181]
According to help doc for the Convert Coordinate Notation gp tool: http://pro.arcgis.com/en/pro-app/tool-reference/data-management/convert-coordinate-notation.htm, the gp tool supports the following formats:
DD, DDM, DMS, GARS, GEOREF, UTM, USNG, and MGRS.

The current addin supports all these same formats except: GEOREF - World Geographic Reference System. We should support all the same formats across the addins, widgets, and gp tools.

**Comment by topowright** [comment]
@lfunkhouser since we have released this add-in I have not heard of anyone using GEOREF. I feel like this issue should be closed.
