### ISSUE TITLE
Coordinate Conversion input format doesn't support +/- hemisphere character as suffix (ArcGIS Pro)

### ISSUE THREAD

**Issue by elinz** [Esri/coordinate-conversion-addin-dotnet#188]
According to the following help topic, ArcGIS Pro supports the + and - hemisphere character as a suffix to the latitude and longitude values, however, the Coordinate Convert addin does not:
http://pro.arcgis.com/en/pro-app/tool-reference/data-management/supported-notation-formats.htm

The addin does support the + and - hemisphere character as a prefix to the coordinate values:

Here are some examples, in this particular case the input is DD, but the addin should also support in DDM, and DMS input formats:
45.0+ 100.0-
45.0+ 100.0+
45.0- 100.0-
45.0- 100.0+

Should also support + and - as suffix when entering in Longitude Latitude order in DD, DDM, and DMS input formats; example shown below is in DD:
100.0- 45.0+
100.0+ 45.0+
100.0- 45.0-
100.0+ 45.0-

**Comment by dhagens** [comment]
@elinz, Could you provide me with a list of what should / shouldn't be allowed or where I can find that?  For example, should we allow S100.0- 45.0+
What should happen if they enter N100- S45.0+

**Comment by dhagens** [comment]
@elinz, could you elaborate on how the hemisphere characters can be used?  I reviewed the supported-notations-format document that is listed above and this issue should be changed to include the use of hemisphere characters as a prefix as well as a suffix.  It doesn't specify in the document whether both a prefix and a suffix are allowed for a given coordinate.  For example, +100S should be invalid but is +100N or +100+ valid?  My suggestion is that we only allow a prefix OR a suffix for a given Lat or Lon, not both.  So they can't enter +100N.  Thoughts?

**Comment by dhagens** [comment]
@elinz, @nfeuerstein, @topowright, @kgonzago - I didn't receive any feedback on my previous comments so I made the tool function how I thought it should.  We allow hemisphere characters for both Lat & Lon and both as either a prefix or a suffix, but not both.  You can also use both a heading and a hemisphere character in the Lat / Lon but can't use both for just Lat or just Lon.  Here are some examples:
Valid:
+100 45S
100- -45
100+ 45N
Invalid:
+100+ 45
100 N45+
100 E45
100 +45+

**Comment by elinz** [comment]
@dhagens @nfeuerstein @topowright @kgonzago I hadn't given any feedback since we were all meeting tomorrow to discuss this.

**Comment by dhagens** [comment]
@elinz, no problem.  I just didn't want to sit around until tomorrow and do nothing.  I already have files checked out for the regex changes and didn't want to jump to something else.  I thought tomorrow's discussion was more about multiple input boxes for lat / lon vs. how to represent hemispheres but maybe I'm wrong.  As for now, it works as I listed above.  If we decide it needs changed, I can do that.  Thanks.

**Comment by elinz** [comment]
@dhagens Absolutely understand. Thanks.

**Comment by lfunkhouser** [comment]
Assigning to MT PEs and @elinz who originally submitted the issue to verify. Release notes for next release will need to be updated too if this is fixed.

**Comment by NatalieCampos** [comment]
I used the coordinates from @elinz and @dhagens.  They all worked.  Verified.  Documentation was not updated, however needs to updated.

**Comment by lfunkhouser** [comment]
Removing ```verify``` label and adding ```in progress``` label to this issue - @NatalieCampos will be updating the documentation.

**Comment by NatalieCampos** [comment]
The (+,-) suffixes were added to the Supported notation format topic for DD, DDM, and DSM. Closing issue

**Comment by topowright** [comment]
@lfunkhouser we have finished the documentation on this task, which is the reason why i removed the tag for Affects Documentation. Is that the correct workflow?
