### ISSUE TITLE
Coordinate Conversion input format doesn't support +/- hemisphere character as suffix (ArcMap)

### ISSUE THREAD

**Issue by elinz** [Esri/coordinate-conversion-addin-dotnet#189]
According to the following help topic, ArcMap supports the + and - hemisphere character as a suffix to the latitude and longitude values, however, the Coordinate Convert addin does not:
http://desktop.arcgis.com/en/arcmap/10.3/tools/data-management-toolbox/supported-notation-formats.htm

The addin does support the + and - hemisphere character as a prefix to the coordinate values:

Here are some examples, in this particular case the input is DD, but the addin should also support in DDM, and DMS input formats:
45.0+ 100.0-
45.0+ 100.0+
45.0- 100.0-
45.0- 100.0+

Should also support + and - as suffix when entering in Longitude Latitude order in DD, DDM, and DMS input formats; example shown below is in DD:
100.0- 45.0+
100.0+ 45.0+
100.0- 45.0-
100.0+ 45.0-

**Comment by lfunkhouser** [comment]
Assigning to MT PEs and @elinz who originally submitted the issue to verify. Release notes for next release will need to be updated too if this is fixed.

**Comment by ACueva** [comment]
Team, I'll work on verifying this issue.  Unassigned you guys.

**Comment by ACueva** [comment]
Verified.  Appears to be working as expected.  Tested against the 8 points listed in the original issue.  Valid results returned.  Tested against values from the map point tool.
@elinz FYI

@dfoll @NatalieCampos Can you guys assist me, not sure how this would affect documentation.  Thanks

**Comment by lfunkhouser** [comment]
@ACueva This affects the topic on what input format is supported

**Comment by ACueva** [comment]
Will work with @NatalieCampos to document this issue.

**Comment by lfunkhouser** [comment]
Documentation has been updated. This is the same topic that was updated for #188
