### ISSUE TITLE
Coordinate Conversion input format does not support the _ (underscore) coordinate pair separator character when input is DDM and DMS (ArcMap)

### ISSUE THREAD

**Issue by elinz** [Esri/coordinate-conversion-addin-dotnet#203]
According to the following help topic, ArcMap supports the underscore _ as the separator between degrees and decimal minutes in DDM format, and the separator between degrees, minutes, and seconds in DMS format, however, the Coordinate Convert addin does not supports this.
http://desktop.arcgis.com/en/arcmap/10.3/tools/data-management-toolbox/supported-notation-formats.htm

**NOTEs:**
- **The addin should support this capability when the input format is in DDM, and DMS.**
- **The addin should also support this when entering in Longitude Latitude order.**

DDM examples:
45_0.0N 100_0.0W
100_0.0W 45_0.0N

DMS examples:
45_0_0N 100_0_0W
100_0_0W 45_0_0N

**Comment by jmhauck** [comment]
The following notation should work with either (lat\lon) or (lon\lat)

DDM examples:
45_0.0N 100_0.0W

DMS examples:
45_0_0.0N 100_0_0.0W

However, will need to resolve #207 to handle as below:

DDM examples:
45_0N 100_0W

DMS examples:
45_0_0N 100_0_0W

**Comment by elinz** [comment]
@jmhauck Installed Pro addin dated 05 Jan 2017 14:42 and tested on ArcMap 10.3.1 and the _ (underscore) character is working. Closing issue.
