### ISSUE TITLE
Coordinate Conversion input format does not support the - (hyphen) coordinate pair separator character when input is DDM and DMS (ArcGIS Pro)

### ISSUE THREAD

**Issue by elinz** [Esri/coordinate-conversion-addin-dotnet#204]
According to the following help topic, ArcGIS Pro supports the hyphen - as the separator between degrees and decimal minutes in DDM format, and the separator between degrees, minutes, and seconds in DMS format, however, the Coordinate Convert addin does not supports this.
http://pro.arcgis.com/en/pro-app/tool-reference/data-management/supported-notation-formats.htm

**NOTEs:**
- **The addin should support this capability when the input format is in DDM, and DMS.**
- **The addin should also support this when entering in Longitude Latitude order.**

DDM examples:
45-0.0N 100-0.0W
100-0.0W 45-0.0N

DMS examples:
45-0-0N 100-0-0W
100-0-0W 45-0-0N

**Comment by jmhauck** [comment]
The following notation should work with either (lat\lon) or (lon\lat)

DDM examples:
45-0.0N 100-0.0W

DMS examples:
45-0-0.0N 100-0-0.0W

However, will need to resolve #207 to handle as below:

DDM examples:
45-0N 100-0W

DMS examples:
45-0-0N 100-0-0W

**Comment by elinz** [comment]
@jmhauck Installed Pro addin dated 05 Jan 2017 11:04 and tested on Pro build 1.4.7197 and the - (hyphen) character is working. Closing issue.
