### ISSUE TITLE
DDM and DMS need to support coordinates without decimal point

### ISSUE THREAD

**Issue by jmhauck** [Esri/coordinate-conversion-addin-dotnet#207]
For example:

DDM
45 0.0N 100 0.0W (works)
45 0N 100 0W (fails)

DMS
45 0 0.0N 100 0 0.0W (works)
45 0 0N 100 0 0W (fails)

**Comment by elinz** [comment]
@jmhauck Good catch

**Comment by elinz** [comment]
@jmhauck I'll start a build and test this.

**Comment by elinz** [comment]
@jmhauck oops. spoke to soon. The commit with the fix hasn't been merged yet.

**Comment by jmhauck** [comment]
@elinz the commit with this fix has been merged. I have been waiting to flip the label to verify until the merge occurs.

**Comment by elinz** [comment]
@jmhauck Thanks.

**Comment by elinz** [comment]
@jmhauck I tested the latest addin built at 07:40 this morning in both ArcMap 10.3.1 and Pro 1.4 and this fix isn't working.

**Comment by dhagens** [comment]
@elinz, I suspect the merge was made after that build was kicked off.  Try kicking off a new build and testing with that.

**Comment by elinz** [comment]
@dhagens I'll test on a newer build. Thanks.

**Comment by elinz** [comment]
@jmhauck @dhagens Tested this again with latest build 06 Jan 2017 09:31 and this still doesn't work.

**Comment by elinz** [comment]
@jmhauck Verified this is working on Pro addin build 09 Jan 2017 16:49 on ArcGIS Pro 1.4 final build. Verified this is working on ArcMap addin build 09 Jan 2017 16:49 on ArcMap 10.3.1 final.
