### ISSUE TITLE
Coordinate Conversion generating output for input values that are ambiguous (ArcMap)

### ISSUE THREAD

**Issue by elinz** [Esri/coordinate-conversion-addin-dotnet#209]
The addin is generating output for input values that are ambiguous.

Some examples, below:

- [ ] Input value: 00
![image](https://cloud.githubusercontent.com/assets/4635490/21627792/33815ec2-d1cf-11e6-83f5-25c9dd07ec43.png)
This doesn't become a valid value until 00 is separated by a space, a comma or one of the other valid coord-pair-separators (http://desktop.arcgis.com/en/arcmap/10.3/tools/data-management-toolbox/supported-notation-formats.htm)

- [ ] Input value: 45
![image](https://cloud.githubusercontent.com/assets/4635490/21627801/3ed94456-d1cf-11e6-8b62-e23b5ec86ed5.png)

- [ ] Input value: 457898
![image](https://cloud.githubusercontent.com/assets/4635490/21627809/4e71a890-d1cf-11e6-9dff-631518a6a3dd.png)

@topowright FYI.

**Comment by dfoll** [comment]
This is what we will add to the documentation. 

When entering integers without spaces the coordinates will be returned as inaccurate. As an example: 

12 returns 1N 2E
1234 returns 4N 123E

**Comment by dhagens** [comment]
Ready for testing

**Comment by lfunkhouser** [comment]
Assigning to MT PEs and @elinz who originally submitted the issue to verify

**Comment by ACueva** [comment]
I'll take this one.

**Comment by ACueva** [comment]
New results:
![2017-05-02_10-12-24](https://cloud.githubusercontent.com/assets/3093940/25629881/fc1e41da-2f1f-11e7-951e-008ff17349dd.png)
![2017-05-02_10-14-36](https://cloud.githubusercontent.com/assets/3093940/25629959/3bac0616-2f20-11e7-90b2-604145706c48.png)
![2017-05-02_10-15-43](https://cloud.githubusercontent.com/assets/3093940/25629990/59e41498-2f20-11e7-96c1-f8c2f3c37202.png)

@elinz Mind giving this a quick once over to make sure it is now the desired output?

**Comment by topowright** [comment]
The expected behavior would be when a user puts in a coordinate that is not clear that the tool will prompt them to allow the tool to understand what they mean. 

If a user puts in 11 or 1234 or 123456 as examples the feedback should be: 
![image](https://cloud.githubusercontent.com/assets/5488313/25634470/a1b9b5d4-2f2f-11e7-90ba-cd9d4f3688f1.png)

Currently this prompt happens correctly if there is a space in the inputs as an example 1 1, 12 34 , 123 456

**Comment by csmoore** [comment]
@kgonzago 's PR merged - ready for retest in next build

**Comment by ACueva** [comment]
Got this one again.

**Comment by ACueva** [comment]
@csmoore @topowright I'm not sure the expected behavior now:
I used the same values from above.
00, 45, and 457598 throw:
![2017-05-03_15-44-02](https://cloud.githubusercontent.com/assets/3093940/25684634/5c50021c-3017-11e7-9c4f-801fb2942587.png)

**Comment by kgonzago** [comment]
@ACueva 00, 45, and 457598 are invalid coordinates. The logic used to parse these coordinates assumes there will be a delimiter (comma, space, period, etc.) used to distinguish between x and y coordinates. 0 0 is valid but 00 (no spacing) is invalid.

**Comment by ACueva** [comment]
@kgonzago Makes sense.  Based off your reply I believe this issue is good to go.  @topowright thoughts?

**Comment by topowright** [comment]
We need to look a the documentation.

**Comment by NatalieCampos** [comment]
@lfunkhouser at 2:25 pm, I tried to recheck out the "known issues for CC Addin for ArcGIS Pro" and it still says it is checked out by you.

**Comment by topowright** [comment]
@dfoll commented on Jan 14th about listing this as a known issue. This never made it into the known issue list; however, this no longer needs to be documented. When invalid coordinates are entered a user is now prompted that the coordinate is invalid. 

![image](https://cloud.githubusercontent.com/assets/5488313/25757613/0861c9aa-3180-11e7-905d-a820b05074dd.png)
