### ISSUE TITLE
"History" input coordinate list does not work (ArcGIS Pro)

### ISSUE THREAD

**Issue by elinz** [Esri/coordinate-conversion-addin-dotnet#214]
I've typed and pasted multiple coordinates into the input control, but the drop-down list does not display the previously entered coordinates.
![image](https://cloud.githubusercontent.com/assets/4635490/21692638/a14ea644-d332-11e6-8652-0da83a571a46.png)

In my opinion, this can be looked at for a future release of the tools.

**Comment by dfoll** [comment]
just to add to the confusion a little bit 😵 ,   in Pro with build 1057 i'm not able to reproduce this 

![image](https://cloud.githubusercontent.com/assets/5322669/21693594/5c03cdea-d336-11e6-9220-7007c9ec3c37.png)

**Comment by elinz** [comment]
Based on @dfoll testing it has been determined that the coordinate is only saved to the history if you used the Map point tool to specify the location. Typing/pasting in a coordinate and hitting return is not saving the coordinate.

**Comment by joebayles** [comment]
Also, it should be noted that it will only save it in the Display Coordinate chosen _at that time:_
![image](https://cloud.githubusercontent.com/assets/5016557/21697966/c04b8c1c-d349-11e6-9706-aa90e1e080e2.png)

**Comment by topowright** [comment]
This has been fixed and I have verified.
