### ISSUE TITLE
"History" input coordinate list does not work (ArcMap)

### ISSUE THREAD

**Issue by elinz** [Esri/coordinate-conversion-addin-dotnet#215]
I've typed and pasted multiple coordinates into the input control, but the drop-down list does not display the previously entered coordinates.
![image](https://cloud.githubusercontent.com/assets/4635490/21692748/28b34504-d333-11e6-90ee-696f1be05e81.png)

In my opinion, this can be looked at for a future release of the tools.

**Comment by elinz** [comment]
Based on @dfoll testing it has been determined that the coordinate is only saved to the history if you used the Map point tool to specify the location. Typing/pasting in a coordinate and hitting return is not saving the coordinate.

**Comment by topowright** [comment]
verified
