### ISSUE TITLE
Doc-Coordinate Conversion: include section/appendix that lists the supported notation formats (ArcGIS Pro)

### ISSUE THREAD

**Issue by elinz** [Esri/coordinate-conversion-addin-dotnet#216]
We need to add a section or appendix to the Pro tool .pdf that describes all the supported notation formats. It's important to include as the tool does not support all the notations described in the core help (link below); and the tool supports notations not supported by core.

http://pro.arcgis.com/en/pro-app/tool-reference/data-management/supported-notation-formats.htm

**Comment by joebayles** [comment]
Related to https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/92?

**Comment by Dbarnes1** [comment]
@NatalieCampos please review, make any additional edits, and close this out once you are done.

**Comment by NatalieCampos** [comment]
reviewed and verified.
