### ISSUE TITLE
Doc-Coordinate Conversion: include section/appendix that lists the supported notation formats (ArcMap)

### ISSUE THREAD

**Issue by elinz** [Esri/coordinate-conversion-addin-dotnet#217]
We need to add a section or appendix to the Pro tool .pdf that describes all the supported notation formats. It's important to include as the tool does not support all the notations described in the core help (link below); and the tool supports notations not supported by core.

http://desktop.arcgis.com/en/arcmap/10.3/tools/data-management-toolbox/supported-notation-formats.htm

**Comment by Dbarnes1** [comment]
@NatalieCampos assigning for you to review. once you give it the ok, we can close this issue out.

**Comment by NatalieCampos** [comment]
reviewed and verified.
