### ISSUE TITLE
No default output formats? (ArcGIS Pro)

### ISSUE THREAD

**Issue by BobBooth** [Esri/coordinate-conversion-addin-dotnet#218]
Didn't the CC tool have some default output formats set at installation?
Seems like this would be useful.

**Comment by joebayles** [comment]
Related to https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/92?

**Comment by elinz** [comment]
@BobBooth @joebayles yes, this is the same as #92

**Comment by nfeuerstein** [comment]
If this duplicated, can we close it out?
