### ISSUE TITLE
Coordinate Conversion - Diacritical Marks (ArcGIS Pro)

### ISSUE THREAD

**Issue by joebayles** [Esri/coordinate-conversion-addin-dotnet#220]
![image](https://cloud.githubusercontent.com/assets/5016557/21698964/637d950c-d34e-11e6-8dcb-80220f2a60c4.png)

If I paste the regular DMS and DM outputs that I received in this dialog into the input, it will not work.

A few suggestions:
- If we are going to use them, they should be:
  - Readable by the input.
  - Copyable by the output.
  - Displayed at all times.
  - If it's an issue to parse them in the input, suggest removing the punctuation from the input, like [this](http://stackoverflow.com/questions/23332146/remove-punctuation-preserve-letters-and-white-space-java-regex).
- We should also be able to build a custom format with them:
  - As the degree symbol isn't readily accessible, suggest we add a degree (°) button.
  - Other common formats without diacritical marks should also be valid.

Daily Build ArcGIS Pro and Daily Build Military Tools for ArcGIS.
FYI @elinz @nfeuerstein

**Comment by elinz** [comment]
@joebayles @nfeuerstein @jmhauck Here is what we have for default formatting for DD, DDM, and DMS related to diacritics:
![image](https://cloud.githubusercontent.com/assets/4635490/21699157/410958e8-d34f-11e6-9176-b9e71b7b0059.png)

For the default DD output formatting we don't include the degree symbols, so for DDM and DMS we shouldn't include the degree, minutes, or seconds. This will make it easier for other applications, which don't accept diacritics to use the output from this tool.

For DD, DDM, and DMS we could add additional out of the box formats which do have the diacritics which users could use if their other application accepts diacritics.

**Comment by joebayles** [comment]
@elinz agreed for output.

For input, we should be able to handle a coordinate string that has diacritical marks, even if it is just removing them to make the string eligible.

**Comment by elinz** [comment]
@joebayles fyi. I've created other issues about accepting diacritics as input. #196 #197, #198, #199

**Comment by BobBooth** [comment]
@elinz @joebayles - strangely enough, in ArcMap (10.4.1) the Distance and Direction and Coordinate Conversion tool accept DMS formatted strings (like 35° 19' 19.91"N 116° 17' 22.01"W) that include diacritics (including the degree symbol) as inputs with no problem. Odd that it works in ArcMap but not Pro.

**Comment by topowright** [comment]
This is now working. @joebayles Can you verify that this works. I attempted it with todays build with the following coordinate:

35° 19' 19.91"N 116° 17' 22.01"W

**Comment by topowright** [comment]
This is what I get when I paste the coordinates to the clipboard: 

35° 19' 19.91"N 116° 17' 22.01"W
128LL19
11SNV6458409006
11S 564584 3909006
35° 19' 19.91"N 116° 17' 22.01"W

**Comment by topowright** [comment]
verified.
