### ISSUE TITLE
Coordinate Conversion - Flash or Persist - ArcGIS Pro

### ISSUE THREAD

**Issue by joebayles** [Esri/coordinate-conversion-addin-dotnet#222]
I suggest that the user be given the option to flash a point or persist a feature, which would be useful in remembering where certain points are. This would dovetail nicely with the ability to batch capture coordinates.

FYI @elinz @mfunk @dfoll @nfeuerstein

**Comment by topowright** [comment]
@joebayles Do you think that this suggestion could be fulfilled by using the collect tab. I do not think the collect tab was showing up five days ago, but it should be there now. I feel like the collect tab has all of these features.

**Comment by joebayles** [comment]
It does, thanks. However, what is the best way to batch convert these, or at least do them one-at-a-time? Copy and paste them back into the Convert tab Input, or Select the feature in the map? Also, I'm not seeing any documentation on the Collect tab.

**Comment by Dbarnes1** [comment]
no documentation on collect tab is issue https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/236, should be taken care of soon.

**Comment by kgonzago** [comment]
@joebayles @topowright @Dbarnes1 My comment references #339. 

The list off coordinates captured is now implemented in the addin. The flash function as a right-click context menu item is now available to the user. When you "flash" a selected coordinate from the list, the point flashes on the map. The enhancement moving forward is to have the user select a point/coordinate on the map that was created with the addin and have that coordinate highlighted in the list.

**Comment by dfoll** [comment]
closing this issue, as the flash functionality exists. created new issues for the ability to select a point on the map and have it highlight in the list #359 #360 and listed on for WAB as well https://github.com/Esri/solutions-webappbuilder-widgets/issues/880
