### ISSUE TITLE
Doc-Coordinate Conversion: "Customize a coordinate format" does not include instructions on how to format DD/DDM/DMS (ArcGIS Pro)

### ISSUE THREAD

**Issue by elinz** [Esri/coordinate-conversion-addin-dotnet#231]
For DD, DDM, and DMS formats, the user can customize the output, however, we don't have any content in this .pdf topic to explain how users can do this.

For example, using # and 0's to format decimal places.
![image](https://cloud.githubusercontent.com/assets/4635490/21785166/4928a160-d673-11e6-89a0-9cf55d279064.png)

**Comment by elinz** [comment]
Should also include content on how to customize the output of the other coordinate systems also.

**Comment by Dbarnes1** [comment]
@elinz I added a sentence explaining the difference between 0 and #, and specified MGRS letter formatting. I believe that we could include more content on how to customize the output of other coordinate systems, but the deeper I look into this the more I am confused at why our coordinate conversion tool doesn't mimic exactly how output coordinates are displayed in ArcGIS Pro. 

I propose that, for post January release, we decide on whether we are going to change how the coordinate conversion tool formats coordinates to match that of arcgis pro, or whether we are going to keep the tool as is and add more extensive documentation that covers how we display output coordinate formats. 

@dfoll @nfeuerstein fyi.

**Comment by jmccausland** [comment]
@Dbarnes1 The original intention of the CC tool was to meet a need for users who use different apps that use different systems and notations.  The original case had a user who had a dozen different applications running at the same time (including Desktop or Pro) and needed to copy/paste coordinates to and from all of these systems.  The CC AddIn allows the user to quickly copy/paste from system A, get the correct notation they need for system B, C, D, E, etc and copy/paste to these systems with only mouse clicks.

**Comment by Dbarnes1** [comment]
per my conversation with @nfeuerstein, we are going to move any further explanation of output coordinate display to post january release.

**Comment by elinz** [comment]
@Dbarnes1 @nfeuerstein Sounds good.

**Comment by dfoll** [comment]
@topowright could you review the published documentation and see if you feel this is sufficiently documented now, if so please remove the "affects documentation" tag, if not we need to address this

**Comment by dfoll** [comment]
closing. @topowright @lfunkhouser @NatalieCampos reviewed what exists in the documentation in the "customize coordinate" section. we came to consensus that the "affects documentation" aspect of this is taken care of. because the issue was just documentation based, closing because the documentation has been updated sufficiently
