### ISSUE TITLE
MGRS coordinate in input textbox is converted to incorrect UTM when display coordinate is changed to UTM (ArcGIS Pro)

### ISSUE THREAD

**Issue by elinz** [Esri/coordinate-conversion-addin-dotnet#233]
Steps to reproduce:
- The Map Point tool is disabled.
- Paste the following MGRS coordinate in the input textbox: 10TET4889274330
- This MGRS coordinate is interpreted:
![image](https://cloud.githubusercontent.com/assets/4635490/21793511/ed6e2956-d6a6-11e6-98ec-23c0d9fddf1a.png)

- The output UTM coordinate is: 10T 548892 5274330

- Now change the display coordinate properties to UTM.
![image](https://cloud.githubusercontent.com/assets/4635490/21793626/dbba1fd4-d6a7-11e6-9253-d6ecc6e9537a.png)

-After clicking OK, the MGRS coordinate in the input textbox is converted to UTM however it's convert not converted to the correct UTM value of 10T 548892 5274330, but to 10N 548892 5274330 (incorrect zone N)

Pro addin build 09 Jan 2017 16:49 on ArcGIS Pro 1.4 final build (7198)

**Comment by elinz** [comment]
@jmhauck Verified that changing the display map units to UTM change the input value to the correct coordinated. build 12 Jan 2017 09:50.

**Comment by elinz** [comment]
@nfeuerstein @dhagens Reopening this issue because the fix is no longer working in latest ArcGIS Pro addin build 17 Jan 2017 13:13.
- When I change the Display Coordinates to UTM, the UTM value that is displayed in the Input textbox is using hemisphere designator instead of latitude band.
![image](https://cloud.githubusercontent.com/assets/4635490/22046246/2c762af8-dcd4-11e6-89d6-6088193fbaea.png)

- When I active the Map Point tool to select a location on the map and move cursor over map the coordinates in the Input textbox are using hemisphere designator instead of latitude band.

**Comment by dhagens** [comment]
Ready for testing once the PR is merged.

**Comment by elinz** [comment]
@dhagens Verified fixed in build 18 Jan 2017 10:14. Closing issue.
