### ISSUE TITLE
No Documentation on Collect Tab for ArcGIS Pro

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/coordinate-conversion-addin-dotnet#236]
I'm realizing the the collect tab has reappeared in our add-in for ArcGIS Pro, and a workflow topic needs to be added to the documentation explaining what it is. I'm going to try and tackle this and assign for review once I'm done.

**Comment by NatalieCampos** [comment]
The following topics were added to the Pro Xmetal map and are ready to be reviewed.  

1.  Collecting Coordiantes
2. Importing Coordiantes

**Comment by Dbarnes1** [comment]
@NatalieCampos I verified that the documentation was added, I made some edits to the collect topic but everything looks good now. I'm going to go ahead and close.
