### ISSUE TITLE
Display Coordinate - Edit Properties Bug - ArcGIS Pro

### ISSUE THREAD

**Issue by joebayles** [Esri/coordinate-conversion-addin-dotnet#238]
Clicking on the Edit Properties button brings this up:
![image](https://cloud.githubusercontent.com/assets/5016557/21824700/711832e0-d735-11e6-900d-d8214e38f1be.png)

The options are all there, but you can't see them. I don't know if this is just a Dark Theme issue or a bug.
![image](https://cloud.githubusercontent.com/assets/5016557/21824815/eda46c48-d735-11e6-966e-5463cc1f70ae.png)

Also, I'm not sure if it is remembering my last choice of DD or not, but it is not defaulting to Default Map Unit.

**Comment by joebayles** [comment]
This is well-documented in a few different issues (Esri/distance-direction-addin-dotnet#233, https://github.com/Esri/military-tools-for-arcgis/issues/66, https://github.com/Esri/military-tools-for-arcgis/issues/79), so I'll add it to the tracker.

**Comment by pHill5136** [comment]
@joebayles Yes this is a dark theme issue for which we have a fix on its way.

**Comment by joebayles** [comment]
Verified.
