### ISSUE TITLE
Unselect multiple coordinates

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/coordinate-conversion-addin-dotnet#239]
In the Collection tab, I would like to deselect all the selected coordinates (See Pic).  Currently when multiple coordinates are selected they have to be individually deselected.  I would like a deselect all button or to be able to use the core select tools.  

![image](https://cloud.githubusercontent.com/assets/5116835/21827584/310c407c-d741-11e6-8d08-503b08d7abdb.png)

**Comment by lfunkhouser** [comment]
Closing. Collect tab no longer exists.
