### ISSUE TITLE
Select multiple coordinates

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/coordinate-conversion-addin-dotnet#241]
I would like to select multiple coordinates using the shift+select like in excel or windows.  Currently when selecting multiple coordinates, I have to select multiple coordinates.  But I would like to use the  shift+select keys to select groups of coordinates.  

![image](https://cloud.githubusercontent.com/assets/5116835/21828410/2a2ebae2-d745-11e6-9ce9-067cc0cafa81.png)

**Comment by lfunkhouser** [comment]
Closing. This functionality exists in Coordinate Conversion List. The Collect tab no longer exists.

Military Tools for ArcGIS 2.0
