### ISSUE TITLE
unable to save collected coordinates in collect tab

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/coordinate-conversion-addin-dotnet#242]
unable to save collected coordinates in collect tab of cc addin. To reproduce 

1. collect coordiantes
2. Save as

Error is below
 
![image](https://cloud.githubusercontent.com/assets/5116835/21830678/36a639e0-d753-11e6-92ad-f7b644cafd2e.png)

**Comment by elinz** [comment]
@NatalieCampos @nfeuerstein This is a duplicate of issue #235, which has been fixed and verified. Closing this issue.

**Comment by NatalieCampos** [comment]
I tried this again with this mornings build and no errors.  Closing this issue.
