### ISSUE TITLE
Coordinate Conversion does not support diaeresis and double acute accent symbol for seconds-mark (ArcGIS Pro)

### ISSUE THREAD

**Issue by elinz** [Esri/coordinate-conversion-addin-dotnet#243]
The addin currently supports all other symbols for degrees, minutes, and seconds (see https://pro.arcgis.com/en/pro-app/tool-reference/data-management/supported-notation-formats.htm) except for the following symbols:

- Diaeresis  ¨  (U+00A8)
- Double Acute Accent ˝ (U+02DD)

**Comment by elinz** [comment]
@nfeuerstein @topowright I have noted this limitation n the addin doc topic about what coordinate notations are supported.

**Comment by topowright** [comment]
I feel like this issue needs to be closed being that we have not heard of a customer not being able to use this format and it is in the documentation. @lfunkhouser  I am moving this to done and tagging it with wont fix.
