### ISSUE TITLE
Coordinate Conversion does not support diaeresis and double acute accent symbol for seconds-mark (ArcMap)

### ISSUE THREAD

**Issue by elinz** [Esri/coordinate-conversion-addin-dotnet#244]
The addin currently supports all other symbols for degrees, minutes, and seconds (see http://desktop.arcgis.com/en/arcmap/10.3/tools/data-management-toolbox/supported-notation-formats.htm) except for the following symbols:

- Diaeresis  ¨  (U+00A8)
- Double Acute Accent ˝ (U+02DD)

**Comment by elinz** [comment]
@nfeuerstein @topowright I have noted this limitation n the addin doc topic about what coordinate notations are supported.

**Comment by lfunkhouser** [comment]
Closing. No user requirement.
