### ISSUE TITLE
Typing versus pasting in an input coordinate produces invalid results (ArcGIS Pro)

### ISSUE THREAD

**Issue by elinz** [Esri/coordinate-conversion-addin-dotnet#247]
- Type in the following coordinate: 90N 50E
The coordinate is interpreted and the following output is created:
![image](https://cloud.githubusercontent.com/assets/4635490/21835339/173b656c-d771-11e6-9c27-320257d50935.png)
The output coordinates DD, DDM, DMS, and GARS are correct, however MGRS (32NNF0000000000), USNG (32NNF0000000000), and UTM (32N 500000 0) are not correct.

The output MGRS/USNG/UTM values represent 0.0S 9.0E (also confirmed by Geotrans).

- Now remove the coordinate from the input textbox and _paste_ in the same value that was typed in above: 90N 50E
Pasting in the value does not create the invalid MGRS, USNG, and UTM values:
![image](https://cloud.githubusercontent.com/assets/4635490/21835522/81eaa44e-d772-11e6-8f7f-74fb4eb334b0.png)

SIDENOTE: UTM is only valid between 84N and 80S. Outside of these latitudes, the Universal Polar Stereographic (UPS) coordinate system is used (http://earth-info.nga.mil/GandG/coordsys/grids/utm.html)

**Comment by dfoll** [comment]
@Dbarnes1  we need to check to make sure we instruct the user to press the enter key

**Comment by Dbarnes1** [comment]
@dfoll pressing the enter key is already a part of our instructions, I'm going to go ahead and remove the affects doc tag.

**Comment by elinz** [comment]
@nfeuerstein @Dbarnes1 @dfoll Verified that input coordinates are not evaluated until the user clicks enter. I also verified that the user doc instructs the user to click Enter for the coordinate to be converted. See below:
![image](https://cloud.githubusercontent.com/assets/4635490/21951199/62b513be-d9b8-11e6-9167-305460075739.png)

Removing Verify label.

**Comment by dfoll** [comment]
@elinz @lfunkhouser does this mean this can be closed with no need for further verification and no further changes to documentation?

**Comment by elinz** [comment]
@dfoll @lfunkhouser That's what I'm assuming, however, I don't know what the milestone was changed in yesterday afternoon's war room to Version after next. This changes makes it seem like there was something else that need to be done, but I don't know of anything else. Same can be said of #248 for ArcMap issue.

**Comment by dfoll** [comment]
This is no longer a known issue because we have changed the functionality to work when the user hits enter.

**Comment by elinz** [comment]
There is nothing left to do on this issue. Closing issue.
