### ISSUE TITLE
Coordinate Conversion does not support the ; and : as coordinate pair separtors when input is DDM and DMS (ArcGIS Pro)

### ISSUE THREAD

**Issue by elinz** [Esri/coordinate-conversion-addin-dotnet#249]
The Coordinate Conversion addin supports the colon and and semi-colon characters (this is not supported by Pro/ArcMap). These separator characters work for input in DD format, but not DDM and DMS.

The following DD coordinates which have ; and : work:
- 45.0N;100.0W
- 45.0N; 100.0W
- 45.0N ; 100.0W
- 45.0N:100.0W
- 45.0N: 100.0W
- 45.0N : 100.0W

The following DDM and DMS coordinates which have ; and : do not work:
- 45 0.0N;100 0.0W
- 45 0.0N; 100 0.0W
- 45 0.0N ; 100 0.0W
- 45 0.0N:100 0.0W
- 45 0.0N: 100 0.0W
- 45 0.0N : 100 0.0W

**Comment by elinz** [comment]
@dfoll @topowright FYI. I have this noted in the Word doc that will serve as the xmetal content.

**Comment by dfoll** [comment]
@topowright and I believe this should be closed

**Comment by elinz** [comment]
@dfoll @topowright I just confirmed that the Supported notation formats topic lists : and ; in DD but not for DDM and DMS, so yes it was okay to close.
