### ISSUE TITLE
Issues with the collect tab

### ISSUE THREAD

**Issue by topowright** [Esri/coordinate-conversion-addin-dotnet#251]
1. When writing the features collected from the collect tab to shp, featureclass or kml it should include all of the formats and their custom settings that have been set in the convert tab. 

2. When importing csv's into the collect tab the options should b x and y for fields in the dialog box. Currently they are set to field 1 and field 2. 

![image](https://cloud.githubusercontent.com/assets/5488313/21862847/d52e5e3e-d7ef-11e6-98d5-5223f6d35e6a.png)

**Comment by topowright** [comment]
@jmhauck I have tried the component and-in and the Military Tools add-in and I am not seeing these changes.  I am testing from build 01-12-2017_1097.

**Comment by NatalieCampos** [comment]
Verified

**Comment by topowright** [comment]
@NatalieCampos I think staying with x and y works for this issue. The issue that is still out there is the issue of the feature class not having any coordinate fields in it.

**Comment by nfeuerstein** [comment]
@topowright please comment with what needs to be addressed "version-next"

**Comment by topowright** [comment]
Part of this issue has been addressed. the second portion of this issue has been addressed by Now having X Field and Y Filed. 

![image](https://user-images.githubusercontent.com/5488313/35402908-cbf3dc16-01b2-11e8-881a-12a3757ac9db.png)

**Comment by topowright** [comment]
The first portion of this issue should be addressed in its own issue. Going to log a new issue once I verify that the issue has not already been logged.

**Comment by topowright** [comment]
This issue has been fixed in previous releases. Closing this issue being that it is not an issue.
