### ISSUE TITLE
Coordinate Conversion: UTM rounding issue (1 meter off)? (ArcGIS Pro)

### ISSUE THREAD

**Issue by elinz** [Esri/coordinate-conversion-addin-dotnet#252]
@nfeuerstein When I was verifying the fix to #157 I found that the output UTM coordinate in some test cases was 1 meter off then what was expected (see https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/157#issuecomment-271653373). If I remember correctly it was never 1 meter off in both the easting and northing. It was either off on one or the other coordinate components and didn't happen every time.

At the time, I was thinking that this was a rounding issue. @jmhauck was starting to look into this. I think we can live with this issue for this release.

**Comment by topowright** [comment]
@elinz please verify

**Comment by elinz** [comment]
@topowright I'm not sure what you're asking me to verify. There have been no fixes. There wasn't going to be.

**Comment by elinz** [comment]
@topowright For an example, see my comment https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/158#issuecomment-270993622

**Comment by topowright** [comment]
I am not sure this is still an issue.

**Comment by topowright** [comment]
This is still an issue: 
![image](https://user-images.githubusercontent.com/5488313/36203401-5203eca4-113c-11e8-9646-ed72fb5912a2.png)

**Comment by lfunkhouser** [comment]
Closing duplicate of #546
