### ISSUE TITLE
Coordinate Conversion: UTM rounding issue (1 meter off)? (ArcMap)

### ISSUE THREAD

**Issue by elinz** [Esri/coordinate-conversion-addin-dotnet#253]
@nfeuerstein When I was verifying the fix to #158 I found that the output UTM coordinate in some test cases was 1 meter off then what was expected (see https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/158#issuecomment-270993622). If I remember correctly it was never 1 meter off in both the easting and northing. It was either off on one or the other coordinate components and didn't happen every time.

At the time, I was thinking that this was a rounding issue. @jmhauck was starting to look into this. I think we can live with this issue for this release.

**Comment by topowright** [comment]
@elinz I believe this was addressed by @dhagens. Please verify

**Comment by topowright** [comment]
Looking at this issue in ArcGIS Pro 2.1 there does not still seem to be the issue. using the coordinates from issue #158 I do not see the presence of the rounding issue. I feel like this can be closed. @dfoll @ACueva  can either of you verify this as well?

**Comment by lfunkhouser** [comment]
Closing. #546
