### ISSUE TITLE
Coordinate Conversion is auto correcting incorrect invalid coordinates (ArcGIS Pro)

### ISSUE THREAD

**Issue by elinz** [Esri/coordinate-conversion-addin-dotnet#254]
Enter the following invalid coordinate: 45 300s|100 30.0w

The tool auto corrects the 300s to 5 minutes and creates the following output:
![image](https://cloud.githubusercontent.com/assets/4635490/21874896/d27a6024-d82c-11e6-8be4-cedfd63dc535.png)

The tool should not auto correct invalid coordinates. The tool should interpret this as invalid and clear the output coordinate textboxes as an indicator to the user that the input is invalid so the user can verify the input coordinate.

**Comment by dfoll** [comment]
noted this in the most recent version of the pdf in the supported notation section near the top as the last bullet under degree based formats. @topowright and @NatalieCampos  agreed it satisfied the "affects documentation" tag... removing "affects "documentation" leaving the issue itself open with the bug tag in case this is something we want to fix

**Comment by dfoll** [comment]
the pub on blaster will have these changes if anyone wants to verify the removal of the affects documentation tag, they won't be picked up by jenkins until another build kicks off

**Comment by dhagens** [comment]
@nfeuerstein, @topowright , @dfoll, @elinz - I would suggest that before we make any changes to this, that the pro or arcmap team is first contacted to determine their reasoning for automatically making this conversion, or to find out if there could be a property added to the ToGeoCoordinateParameter that would allow us to turn off automatic autocorrection.  We are making ArcObject calls to get the coordinates back based on what the user inputs.  Is it likely that a user would ever be given 300" vs 5'?   The class is in ArcGIS.Core.Geometry - ToGeoCoordinateParameter

**Comment by dhagens** [comment]
I would also like to note that other tools also perform the conversion automatically.  

http://www.latlong.net/degrees-minutes-seconds-to-decimal-degrees
![image](https://cloud.githubusercontent.com/assets/13664546/22254693/56cc2fa6-e223-11e6-8153-9330d2858055.png)

http://www.earthpoint.us/Convert.aspx
![image](https://cloud.githubusercontent.com/assets/13664546/22254736/75cd40ac-e223-11e6-8c3b-efc4eabd8786.png)

**Comment by dfoll** [comment]
if this is the generally accepted way of dealing with "invalid" coordinates, does this really belong as an issue

**Comment by dfoll** [comment]
I do not see this as an issue with 10.6.1 MT build 48
also tried
35 180 52.14N 098 47 32.15W
35 180 52.14N 098 47 302.15W
 properly bounced back Invalid Coordinate window

**Comment by topowright** [comment]
I have validated this as well with the released version of MT 3.1: 
![image](https://user-images.githubusercontent.com/5488313/43735038-6f812b88-996e-11e8-90ab-f3f2b193d9f0.png)
