### ISSUE TITLE
Coordinate Conversion doesn't fully support GARS as input (ArcGIS Pro)

### ISSUE THREAD

**Issue by elinz** [Esri/coordinate-conversion-addin-dotnet#256]
Note: GARS is fully supported in the ArcMap addin.

According to https://pro.arcgis.com/en/pro-app/tool-reference/data-management/supported-notation-formats.htm:
GARS is based on longitude and latitude and divides the world into 30 minute by 30 minute cells. The first three digits represent a 30 minute wide longitude band. The fourth and fifth letters represent a 30 minute tall latitude band. Each 30 by 30 minute cell can be divided into four 15 by 15 minute cells with the 15 by 15 minute cells further divided into nine 5 by 5 minute cells.

161MG - Coordinate down to 30' x 30' cell.
161MG3 - Coordinate down to 15' x 15' cell.
161MG37 - Coordinate down to 5' x 5' cell.

The ArcGIS Pro addin can interpret the 5' x 5' cell coordinate, 161MG37. It can't interpret the 15' x 15' cell and the 30' x 30' cell. The ArcMap addin can interpret all resolutions of cells. The examples below show the Pro addin results on the left and the ArcMap addin results on the right:

![image](https://cloud.githubusercontent.com/assets/4635490/21877561/b185b7a6-d840-11e6-9ed5-197b45251a4e.png)

![image](https://cloud.githubusercontent.com/assets/4635490/21877581/d5a02ef0-d840-11e6-9626-efb1773f1d05.png)

**Comment by nfeuerstein** [comment]
Do people use GARS at a lower resolution? 15x15 or 30x30?

**Comment by nfeuerstein** [comment]
According to NGA, GARS is primarily designed as a battlespace management tool and not to be used for navigation or targeting.  For this version, let's just document this limitation in Pro.

**Comment by elinz** [comment]
@nfeuerstein @dfoll @Dbarnes1 I've added a note to the Word doc that we're using for the Xmetal content.

**Comment by Dbarnes1** [comment]
@elinz this is now in xmetal, ready for verification.

**Comment by elinz** [comment]
@nfeuerstein @Dbarnes1 Since the time of the document update, I've found that Pro isn't creating a valid output when you input GARS at 5' by 5' cell.

When I enter the following 5' by 5' coordinate: 161MG37, Pro outputs the following:
![image](https://cloud.githubusercontent.com/assets/4635490/21948810/551f870e-d9a2-11e6-9233-d8bd3d1ff019.png)

This is the output created by the ArcMap addin which is correct and matches GeoTrans:
![image](https://cloud.githubusercontent.com/assets/4635490/21948834/7d0173d6-d9a2-11e6-9719-4778413eaf55.png)

We will have to update the coordinate notation topic. In summary, the ArcGIS Pro addin:
- Does not create output when GARS 30' x 30' cell coordinate is entered.
- Does not create output when GARS 15' x 15' cell coordinate is entered.
- Creates incorrect output when GARS 5' x 5' cell coordinate is entered.

**Comment by lfunkhouser** [comment]
We do not fully support GARS at this release. @pHill5136 please remove GARS from Pro and ArcMap

**Comment by Dbarnes1** [comment]
gars removed from support doc.

**Comment by pHill5136** [comment]
@elinz @dfoll @NatalieCampos @lfunkhouser @nfeuerstein Removed gars. lots of code removed so I would like coordinate conversion checked pretty extensively to make sure nothing got broken. My preliminary tests seemed good, though.

**Comment by elinz** [comment]
@dfoll @nfeuerstein @lfunkhouser @nfeuerstein new build currently being created. I'll test.

**Comment by elinz** [comment]
@nfeuerstein Changed to Version - Next until I can verify that GARS has been removed from ArcGIS Pro and ArcMap and that Coordinate Conversion is still working after this change.

**Comment by dfoll** [comment]
If GARS is not going to be in, then this is not for the known issues list, if GARS is going to be in, we need to put this in the known issues list.

**Comment by nfeuerstein** [comment]
Notes for tomorrow: 
Need to know if GARS has been fully removed/commented out and that it is not in the known issues list.

**Comment by pHill5136** [comment]
Gars has been removed from all repos. Needs top be tested pushing to verify.

**Comment by nfeuerstein** [comment]
Need to scan doc thoroughly for GARS and test to make sure removal of GARS didn't have unintended effects.

**Comment by elinz** [comment]
@nfeuerstein @topowright @NatalieCampos I'm testing the Pro/ArcMap addins and the widget for any side effects of removing GARS.

**Comment by nfeuerstein** [comment]
If side effects are found, continue to add issues.  Closing this issue as GARS was removed.

**Comment by elinz** [comment]
@nfeuerstein Fyi. i did verify that GARS was removed from the Display Coordinate dialog in the addins,  and the Widget. Also verified that you can no longer output GARS from the addins, and the widget. Did some basic testing in the addins, and widgets and so far have not found any issues that I believe could be attributed to the removal of GARS.
