### ISSUE TITLE
Units do not match in some spatial referances in ArcGIS Pro

### ISSUE THREAD

**Issue by topowright** [Esri/coordinate-conversion-addin-dotnet#258]
![image](https://cloud.githubusercontent.com/assets/5488313/21897622/0bbd52b6-d89f-11e6-9054-b7cfa6a188b3.png)

When setting the display units and the tool units to the same the coordinates should match perfectly the way they do in ArcMap. 

![image](https://cloud.githubusercontent.com/assets/5488313/21897951/fe290b6c-d89f-11e6-9b35-69ba9d782da5.png)

**Comment by topowright** [comment]
@dhagens you were right this morning. It has to do with the spatial location. Here is a image to prove that it is correct: 

![image](https://cloud.githubusercontent.com/assets/5488313/21907474/94fa7a20-d8c4-11e6-9d20-561aaaa7291a.png)

**Comment by dhagens** [comment]
@topowright - I think that I have a solution for this.  It is a rounding issue.  I should be able to check in a fix shortly after verifying

**Comment by dhagens** [comment]
@topowright, ready for testing once @kgonzago merges.

**Comment by topowright** [comment]
verified
