### ISSUE TITLE
When inputting a coordinate out of the map view ArcMap Crashes

### ISSUE THREAD

**Issue by topowright** [Esri/coordinate-conversion-addin-dotnet#269]
If you are in a projected coordinate system and you input a location that is outside of that projection ArcMap crashes.

**Comment by topowright** [comment]
On my system this crashed. On @Dbarnes1 system the tool did not convert or flash the outputs.

**Comment by Dbarnes1** [comment]
@topowright and I were unable to reproduce this issue today, closing out.
