### ISSUE TITLE
Issue copying and pasting coordinates 

### ISSUE THREAD

**Issue by topowright** [Esri/coordinate-conversion-addin-dotnet#271]
If I input a location any way and then input a new location by typing or pasting the first location that is flashed is the last location. You must hit enter one more time and then the new location is highlighted. 

This is a new issues since yesterday: 

@nfeuerstein @elinz

**Comment by elinz** [comment]
For example, I click on Coordinate Conversion tool.
- My map is currently centered on the US.
- In the Input box, type the coordinates 45N 120E and hit return. The map is not panned to the coordinates 45N 120E.  I have to click back into the Input textbox and hit return again for the map to to pan and center on this coordinates and the flash and the point are drawn on the map.
- Now type the coordinates 45S 120W in the Input textbox and hit return. The flash and point are drawn on the map, but it's located on the previous entered coordinate of 45N 120E. You have to click in the Input textbox and hit return again for the map to pan and the flash and point to draw on the map on coordinate that's currently in the Input textbox.

**Comment by topowright** [comment]
It does not matter if the point is on the screen or not it always flashes the last location

**Comment by elinz** [comment]
The point is you always have to hit return twice in the Input textbox for the flash/point to be drawn in the correct location.

**Comment by topowright** [comment]
@elinz correct. I have also tested this at the single add-in level and the component level.

**Comment by kgonzago** [comment]
@topowright Added a fix for this issue in this [PR](https://github.com/Esri/coordinate-conversion-addin-dotnet/pull/274). Can you confirm the fix when you get a chance?

**Comment by topowright** [comment]
@kgonzago you are awesome. I have verified this fix.
