### ISSUE TITLE
Coordinate Conversion: add support to output UTM using latitude band as well hemisphere (ArcGIS Pro)

### ISSUE THREAD

**Issue by elinz** [Esri/coordinate-conversion-addin-dotnet#275]
See https://github.com/Esri/solutions-webappbuilder-widgets/issues/718

**Comment by topowright** [comment]
This has now been implemented. 
![image](https://user-images.githubusercontent.com/5488313/46952810-d41db080-d040-11e8-81fc-a364106b17d5.png)

This can be closed because it has not been listed as a known issue and does not require any documentation. @lfunkhouser
