### ISSUE TITLE
Doc - Supported notation formats section - typo in choice list (ArcMap)

### ISSUE THREAD

**Issue by elinz** [Esri/coordinate-conversion-addin-dotnet#278]
The example choice list has a typo. First right hand bracket should be a pipe. Instead of [+]-|N|S] it should be [+|-|N|S]:
![image](https://cloud.githubusercontent.com/assets/4635490/22002381/a2dfcf7a-dc00-11e6-9c8a-9baf8183f341.png)

**Comment by lfunkhouser** [comment]
Fixed in build 1137.

**Comment by elinz** [comment]
Verified in ArcMap addin .pdf build 1137 (17 jan 2017 09:11). Closing issue.
