### ISSUE TITLE
Doc - Supported notation formats content issues (ArcGIS Pro and ArcMap)

### ISSUE THREAD

**Issue by elinz** [Esri/coordinate-conversion-addin-dotnet#279]
The following apply to both the ArcGIS Pro and ArcMap addin documentation:

## Decimal Degrees
- [x] Remove spaces between hemisphere designator prefix, DD.dd, DDD.dd, and suffix since spaces at these locations are not supported by the addins:
![image](https://cloud.githubusercontent.com/assets/4635490/22003670/26d78a08-dc0a-11e6-9481-6f567f6ae2e8.png)

## Degree Decimal Minutes
- [x] Add "(DDM)" to section header since DDM is the abbreviation used in the output control.

- [x] Remove spaces between hemisphere designator prefix, DD.dd, DDD.dd,  and suffix since spaces at these locations are not supported by the addins.
- [x] Change DD.dd in table to DD MM.mmm
- [x] Change DDD.dd in table to DDD MM.mmm
![image](https://cloud.githubusercontent.com/assets/4635490/22003726/c592b032-dc0a-11e6-970c-b6a345f90deb.png)

## Degrees Minutes Seconds (DMS)
- [x] Remove spaces between hemisphere designator prefix, DD.dd, DDD.dd, and suffix since spaces at these locations are not supported by the addins.
- [x] Change DD.dd in table to DD MM SS.sss
- [x] Change DDD.dd in table to DDD MM SS.ss
![image](https://cloud.githubusercontent.com/assets/4635490/22003761/197d812c-dc0b-11e6-90c8-54e673f24539.png)

- [x] Change DD MM.mmm and DDD MM.mmm in the following sentence to: DD MM SS.sss and DDD MM SS.sss, respectively:
![image](https://cloud.githubusercontent.com/assets/4635490/22003864/c9f4aa6c-dc0b-11e6-920a-9ef341f44039.png)

- [x] Change the formatting info shown the following screenshot...
![image](https://cloud.githubusercontent.com/assets/4635490/22003917/2b6d5fa0-dc0c-11e6-8cad-d833995f57bb.png)
TO:
![image](https://cloud.githubusercontent.com/assets/4635490/22003968/7ea55be6-dc0c-11e6-894f-6da08aff76be.png)

## Universal Traverse Mercator (UTM)
- [x] Change to "...spaces must be embedded between..."
![image](https://cloud.githubusercontent.com/assets/4635490/22006684/069dd6b2-dc22-11e6-9d19-dea5d90f35be.png)

**Comment by lfunkhouser** [comment]
Fixed in build 1137

**Comment by elinz** [comment]
- Verified in ArcGIS Pro addin .pdf build 1137 (17 Jan 2017 09:11).
- Verified in ArcMap addin .pdf build 1137 (17 Jan 2017 09:11).
Closing issue.
