### ISSUE TITLE
When Display Coordinate is changed to USNG, the input coordinate now has embedded spaces (ArcGIS Pro)

### ISSUE THREAD

**Issue by elinz** [Esri/coordinate-conversion-addin-dotnet#283]
Tested build 17 Jan 2017 13:13.
When you change Display Coordinate to USNG the input coordinate value has embedded spaces. This should not have spaces. It should match the formatting of the default output.
![image](https://cloud.githubusercontent.com/assets/4635490/22044423/80de1b6a-dcc9-11e6-9ed6-4784c03f4e40.png)

**Comment by adgiles** [comment]
Fixed in this pull request https://github.com/Esri/coordinate-conversion-addin-dotnet/pull/310

**Comment by lfunkhouser** [comment]
Assigning to MT PEs and @elinz who originally submitted the issue to verify

**Comment by NatalieCampos** [comment]
Verified.
