### ISSUE TITLE
When Display Coordinate is changed to USNG, the input coordinate now has embedded spaces (ArcMap)

### ISSUE THREAD

**Issue by elinz** [Esri/coordinate-conversion-addin-dotnet#284]
Tested build 17 Jan 2017 13:13.
When you change Display Coordinate to USNG the input coordinate value has embedded spaces. This should not have spaces. It should match the formatting of the default output.
![image](https://cloud.githubusercontent.com/assets/4635490/22044423/80de1b6a-dcc9-11e6-9ed6-4784c03f4e40.png)

**Comment by adgiles** [comment]
fixed in this pull request https://github.com/Esri/coordinate-conversion-addin-dotnet/pull/310

**Comment by Dbarnes1** [comment]
@adgiles @kgonzago @elinz verified fixed during holistic testing for 10.5.1.
