### ISSUE TITLE
Input USNG value collected using Map Point Tool do not match output USNG value (ArcGIS Pro)

### ISSUE THREAD

**Issue by elinz** [Esri/coordinate-conversion-addin-dotnet#285]
Build 17 Jan 2017 13:13.

Set display coordinate to USNG, then used Map Point tool to collect coordinate off my. The USNG displayed in Input textbox does not match output USNG (and MGRS) coordinate.
![image](https://cloud.githubusercontent.com/assets/4635490/22044858/b0dcd1ec-dccb-11e6-8a7c-92c9b07fe977.png)

NOTE: if I then click return in the input textbox the output coordinate will match input.
![image](https://cloud.githubusercontent.com/assets/4635490/22044892/ec7550e4-dccb-11e6-8043-cac6095a35b1.png)

Also compared the "read-out" at bottom of map with the input and output coordinates...
![image](https://cloud.githubusercontent.com/assets/4635490/22044969/68540bce-dccc-11e6-8f85-9b1c4641d6f2.png)

**Comment by nfeuerstein** [comment]
@elinz  what were the steps again?  You said "to collect coordinate off my."  Off the map?  Is this because we now require the user to hit Enter?

**Comment by elinz** [comment]
@nfeuerstein haha. Tracking too many things in my head and didn't complete my sentence. Should be "Set display coordinate to USNG, then used Map Point tool to collect coordinate off the map."

**Comment by dhagens** [comment]
Ready for testing once the PR is merged.

**Comment by elinz** [comment]
Verified fixed in build 18 Jan 2017 10:14. Closing issue.
