### ISSUE TITLE
Map Point tool issues (ArcGIS Pro)

### ISSUE THREAD

**Issue by elinz** [Esri/coordinate-conversion-addin-dotnet#287]
Tested build 17 Jan 2017 13:13.

When the Map Point tool is disabled, the cursor icon does not change back to the cursor icon that was set before the Map Point tool was enabled.

FYI: All other behavior is what I would expect:
- When tool tab is clicked, the Map Point tool isdisabled by default.
- User clicks the tool to enable.  Result: the tool is enabled; the look of the button changes to indicate that's it's active; the cursor icon changes to the crosshairs with center dot. (other behavior is the same...i.e. interact with map, etc).
- User clicks the tool to disable. Result: the tool is disabled; the look of the button changes to indicate that's it's active; just need the cursor icon to be changed back to what it was before the Map Point tool was enabled.

**Comment by dhagens** [comment]
Ready for testing once the PR is merged.

**Comment by elinz** [comment]
Verified fixed in build 18 Jan 2017 10:14. Closing issue.
