### ISSUE TITLE
ArcMap crash when using the Coordinate Conversion tool (ArcMap)

### ISSUE THREAD

**Issue by elinz** [Esri/coordinate-conversion-addin-dotnet#290]
I was testing the fix for #285 when ArcMap crashed. I haven't been able to replicate what steps caused it to crash, but I think it's some combination of using the Map Point tool and change the Display Coordinates units.

**Comment by nfeuerstein** [comment]
We need to be able to replicate the steps and crash it semi-consistently to know how to fix it.  Removing showstopper until/if it can be replicated.

**Comment by dhagens** [comment]
@elinz, ready for testing once the merge is completed.

**Comment by lfunkhouser** [comment]
Assigned to MT PEs to verify. @ACueva @dfoll @topowright @NatalieCampos

**Comment by NatalieCampos** [comment]
Unable to reproduce this issue.  Closing it for now.

**Comment by topowright** [comment]
We think that this issue might have been fixed when we addressed issue #319
