### ISSUE TITLE
Doc - Coordinate Notation section - clean up comments under "Degree-based formats" (ArcGIS Pro, ArcMap)

### ISSUE THREAD

**Issue by elinz** [Esri/coordinate-conversion-addin-dotnet#291]
![image](https://cloud.githubusercontent.com/assets/4635490/22085819/969e587c-dd8a-11e6-8228-ba0562752587.png)

![image](https://cloud.githubusercontent.com/assets/4635490/22085712/1da9e5c6-dd8a-11e6-8471-9d01c60eed97.png)

**Comment by nfeuerstein** [comment]
@topowright @Dbarnes1 where are we at on this issue?  Is the doc complete?

**Comment by elinz** [comment]
@nfeuerstein @topowright @Dbarnes1 This should all be completed. Started a build before lunch so I can verify against the .pdfs in the build. I'll change to verify.

**Comment by elinz** [comment]
@nfeuerstein @topowright @Dbarnes1 
- Verified that this was fixed in Pro addin doc in build 19 Jan 2017 11:54.
- Verified that this was fixed in ArcMap addin doc in build 19 Jan 2017 11:54.
Closing issue.

**Comment by Dbarnes1** [comment]
thanks @elinz
