### ISSUE TITLE
When Coordinate Conversion tool is clicked ArcMap crashes (ArcMap)

### ISSUE THREAD

**Issue by elinz** [Esri/coordinate-conversion-addin-dotnet#292]
- Install 01-18-2017_1143 build of Military Tools for ArcGIS addin.
- Open ArcMap
- Click Cancel on "ArcMap - Getting Started" dialog.
- Click on Coordinate Conversion tool in Military for ArcGIS Tools toolbar.
- ArcMap crashes

I was able to reproduce the crash multiple times on two different machines (one physical, on VM).

**Comment by nfeuerstein** [comment]
@dhagens @kgonzago please look into this asap.

**Comment by dhagens** [comment]
@elinz @nfeuerstein - I installed the latest build from \\redarchive2\disl\Development\Commercial\MilitaryToolsForArcGIS\_current\ArcGISPro\Addins and had no issues when clicking on the Coordinate Conversion tool.  Could someone else please test this out to verify that there is an issue?  @kgonzago @csmoore

**Comment by csmoore** [comment]
I could repro using the exact steps provided (i.e. hitting cancel from getting started, when toolbar already opened) - still looking into...

**Comment by dhagens** [comment]
I see the crash also.  I was testing with Pro... duh.  Looking into it.

**Comment by kgonzago** [comment]
@dhagens and I traced the crash to build 1142. Last build where CC didn't crash ArcMap was build 1141. It looks like something was introduced between builds 1141 and 1142 that's causing CC add-in to crash. Still looking into it...

**Comment by kgonzago** [comment]
we are reverting back to this commit f2b7e683015e5885e17ac0a93160f76f89bdd9d6 to get the build going again. Changes to address the map tool issue for CC will be lost but we will address it ASAP.

**Comment by dhagens** [comment]
@elinz @nfeuerstein @topowright 
The single addin (Military Tools for ArcGIS toolbar) should function properly now.  @kgonzago reverted back to the PR before the last one I made yesterday for Coordinate Conversion that fixed the MapPoint tool in ArcMap.  For some reason that change caused the CC tool to not work in the single addin, although it still worked fine in the standalone addin.  I'll have to figure out how to make that fix work w/o breaking the single addin.  Other than that, should be good to go.

**Comment by elinz** [comment]
@nfeuerstein @dhagens @topowright Thank you. I'll start a Jenkins build and verify that CC no longer crashes ArcMap.

**Comment by dhagens** [comment]
@elinz, the current build was tested using the latest code.  You can verify again if you'd like though by doing another build.

**Comment by elinz** [comment]
@nfeuerstein @dhagens Verified on build #1151, dated 19 Jan 2017 11:51 that clicking on the CC tool does not crash ArcMap. Closing issue.
