### ISSUE TITLE
Doc - Coordinate Conversion - Supported Notation Formats has invalid MGRS coordinates (ArcGIS Pro)

### ISSUE THREAD

**Issue by elinz** [Esri/coordinate-conversion-addin-dotnet#303]
@nfeuerstein FYI.

All of the MGRS coordinates in the doc are using invalid Zone/Lat Band, 100k grid designator. There was a typo added when the xmetal topic was written.

All MGRS coordinates in doc that start with...
115WC

Should be change to 11SWC

people are going to try and cut and past from the doc as they try things out, so we should correct this.

**Comment by Dbarnes1** [comment]
@elinz good catch, just fixed this, I'm going to build the doc in a bit so you can verify.

**Comment by elinz** [comment]
Verified on final 1172 build. Closing issue.
