### ISSUE TITLE
Map Point Tool should stay enabled

### ISSUE THREAD

**Issue by dfoll** [Esri/coordinate-conversion-addin-dotnet#316]
I asked around a little bit and no one was aware of a reason for this design choice so i would like to see this enhancement.

Map Point Tool should stay enabled whether on the Convert tab or the Collect (not currently implemented) tab. 

If I am trying to collect the coordinates for a point on the eastern end of Lake Erie, but I absentmindedly click on the western end, I now need to go back to the Coordinate Conversion pane, re-enable the Map Point Tool and then go back and click on the correct point on the map again. Seems trivial, but I suggest this enhancement for the sake of minimizing mouse clicks.

**Comment by dfoll** [comment]
@nfeuerstein @kgonzago  no assignee or milestone for now, submitting for your consideration

**Comment by topowright** [comment]
This can be closed. We only have one tab.
