### ISSUE TITLE
Select [an] existing feature(s) as inputs

### ISSUE THREAD

**Issue by joebayles** [Esri/coordinate-conversion-addin-dotnet#318]
As a user, I want to the ability to choose existing features as inputs to populate the Collect Tab.

**Comment by topowright** [comment]
A user can currently use the map point tool and with snapping on it will collect that feature. I am almost certain this was a issue that was addressed with allowing the constant collection of points with the map point tool. 

![image](https://user-images.githubusercontent.com/5488313/35404729-d6ee0604-01b8-11e8-837e-3809e311ffe0.png)
