### ISSUE TITLE
Coordinate Conversion: Input becomes unresponsive after Ambiguous Coordinate dialog ignored. (ArcMap)

### ISSUE THREAD

**Issue by ACueva** [Esri/coordinate-conversion-addin-dotnet#320]
Version
ArcGIS Desktop10.5.

Tested against Build: 1413

Steps to reproduce:
1.  Open ArcMap and Coordinate Conversion Addin
2. Add DD, DDM, DMS are new output coordinates.
3. In the Input box, enter: 45.0+ 100.0-
4.  You should get a the Ambiguous Coordinates dialog box pop up.
5.  Close the window without hitting the "OK" button.
6. Enter another ambiguous coordinate such as: 45.0+ 100.0+
7. Note it no longer gives you a coordinate.
8. Close ArcMap and enter the same ambiguous coordinate as above.  It now works.

**Comment by ACueva** [comment]
FYI @nfeuerstein @lfunkhouser @kgonzago

**Comment by kgonzago** [comment]
@ACueva Will look into it.
