### ISSUE TITLE
Remove the Convert Tab

### ISSUE THREAD

**Issue by topowright** [Esri/coordinate-conversion-addin-dotnet#329]
Going forward the CC tool - add-in does not need to have a tabbed approach. To allow more real estate room for other things remove the convert tab to allow room to be made for the batch functionality. 

![image](https://cloud.githubusercontent.com/assets/5488313/25768190/5e4c614c-31b5-11e7-95d1-b9bd12eb7b23.png)

**Comment by topowright** [comment]
Just for clarification, the capability that is on the collect tab will be moved to the coordinate tab.

**Comment by dfoll** [comment]
moved out of verify because the convert tab is still in arcmap

![image](https://cloud.githubusercontent.com/assets/5322669/26130288/cda7b24e-3a48-11e7-9762-7d6627cd4e2a.png)

**Comment by dfoll** [comment]
added affects documentation because we may need to remove references to the convert tab

**Comment by kgonzago** [comment]
@dfoll The tab is no longer there at component level of the CC add-in but still persists at the MT level as part of the toolbar. I will need to update that repo.

**Comment by kgonzago** [comment]
@dfoll the single-addin repo has been updated and should be part of the next build.

**Comment by ACueva** [comment]
@kgonzago I'm assuming you moved to Verify for the PE's to test.  Assigning to @dfoll and myself to test ArcGIS Pro, and ArcMap, respectively.

**Comment by dfoll** [comment]
in Pro build 1484 it's gone
