### ISSUE TITLE
Change “copy all” to “copy last”

### ISSUE THREAD

**Issue by topowright** [Esri/coordinate-conversion-addin-dotnet#331]
When I want to copy notations from the output list of the tool it should say Copy Last instead of Copy all with the additions of the batch section on this tool. 

![image](https://cloud.githubusercontent.com/assets/5488313/25768151/e4c16282-31b4-11e7-8c34-0397ac13538e.png)

**Comment by dfoll** [comment]
i like this idea, however i would change the verbage to "Copy Outputs" to be explicit about what the user is putting onto the clipboard when they copy, to me "Copy Last" is not the clearest way to convey to the user what they are copying. @topowright , thoughts?

**Comment by ACueva** [comment]
This may be a non issue if @kgonzago/ @adgiles are able to move the copy icon to the output header row. It should make more sense what you're copying at that point.

**Comment by kgonzago** [comment]
FYI: Based on #343, the buttons have been moved to the output header row.

**Comment by dfoll** [comment]
closing this. verified that @kgonzago moved the copy button and add format button to the output header, no need to change the verbage of the button, since it is now in the output header, i feel it is obvious what it is copying
