### ISSUE TITLE
Add a clear button to clear the list of collected points

### ISSUE THREAD

**Issue by topowright** [Esri/coordinate-conversion-addin-dotnet#332]
The clear button will be used to clear the listed of imported or collected points. Imported points are collected using the map point tool and the import button brings in locations based on a kml, xls, xlst,txt,  and csv. 

When a user hits the clear button they will be asked if they are sure they would like to clear the list. 

![image](https://cloud.githubusercontent.com/assets/5488313/25809684/a110deea-33c2-11e7-994a-b5abcf54d26a.png)

**Comment by kgonzago** [comment]
@topowright This is now available from PR #344

**Comment by ACueva** [comment]
ArcMap behavior has a "Clear All" button.  This does exactly what it says, clears the whole list.
For deleting single items you are able to select the item from the list and delete it with the keyboard delete key, or right clicking and selecting "delete".

**Comment by dfoll** [comment]
Clear button clears all the points from the list in ArcGIS Pro
