### ISSUE TITLE
Map pointer drops points (graphics) on map.

### ISSUE THREAD

**Issue by topowright** [Esri/coordinate-conversion-addin-dotnet#333]
When a user uses the map point tool and selects a location on the map a graphic of that location will be placed on the map. Also, that location will be populated to the batch list. The batch list will be based on the type of coordinate that has been selected from the output table. The user should be able to collect mutiple points without having to click on the map point tool between selecting locations. 

![image](https://cloud.githubusercontent.com/assets/5488313/25811237/6bfbba54-33c7-11e7-8a44-19b492ef8ab2.png)

See the sequence diagram for further information.

**Comment by kgonzago** [comment]
I discussed this with @ACueva. Currently, if you want to change the notation format of coordinates in the batch list, you will need to click on the `Edit Properties` button in the `Input` section, choose your new notation, then click `OK`. Clicking on a row in the `Output` data grid may not be intuitive to a user. Also, if you click on the far left of a row in the data grid, you will see a brief image by your mouse cursor invoking the behavior of dragging or sorting in the data grid. Based on our discussion, we will temporarily table this issue.

FYI @nfeuerstein @lfunkhouser

**Comment by ACueva** [comment]
As a follow up.  The functionality is there, perhaps not in the best location.  However, it works.  Asked @kgonzago to focus on other functionality.

**Comment by topowright** [comment]
This issue is no longer valid as we have designed the tool and shipped it multiple times with the current configuration.

**Comment by topowright** [comment]
closing this as invalid.
