### ISSUE TITLE
Move the list box off of the collect tab

### ISSUE THREAD

**Issue by topowright** [Esri/coordinate-conversion-addin-dotnet#334]
The list box needs to be placed in the main part of the CC tool: 

![image](https://cloud.githubusercontent.com/assets/5488313/25811315/bb887b98-33c7-11e7-841e-7f3369655067.png)
This is what the tool should look like when done.

**Comment by ACueva** [comment]
This UI change has been properly implemented in ArcMap.

**Comment by dfoll** [comment]
in ArcGIS Pro, the collect tab is gone and the "List" now appears on the (only) pane. Looks like @ACueva verified this in  ArcMap.
