### ISSUE TITLE
UI Enhancement design

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/coordinate-conversion-addin-dotnet#339]
@lfunkhouser , @nfeuerstein On 5/9/10 the team (PEs and Devs) met to discuss the batch conversion functionality.  We came up with an enhancement to the UI. See the graphic below.  Devs discussed that the moving of buttons would be difficult and a reach for the next release.  

![image](https://cloud.githubusercontent.com/assets/5116835/25863581/3f294ae8-34a1-11e7-8331-51a7aa95d587.png)

@topowright , @ACueva , @dfoll , @kgonzago , @csmoore , @adgiles

**Comment by kgonzago** [comment]
@nfeuerstein moving buttons from input to output data grid was already tackled in #343 in is part of the larger effort related to #334.

**Comment by dfoll** [comment]
@kgonzago  i realize this is not moved to verify yet, so i'm just sorta sticking my nose where it doesn't belong, but is work still pending on getting rid of the convert tab  in ArcMap, was playing with some stuff today, and noticed with build 1476, it's gone from Pro already, but not ArcMap

**Comment by kgonzago** [comment]
@dfoll You are correct that it wasn't removed from AM since I didn't update the single-addin repo. It's done now and will be reflected in the next build.

**Comment by ACueva** [comment]
Initial load (ArcMap):
![2017-05-18_13-38-56](https://cloud.githubusercontent.com/assets/3093940/26222575/63391e10-3bcf-11e7-9fbc-92f8dc585ff2.png)

From strictly a UI perspective.  The look and feel is acceptable. GJ @kgonzago 

Assigning to @dfoll for ArcGIS Pro verification.
These UI changes will require updates to documentation.

**Comment by dfoll** [comment]
UI verified in Pro.

**Comment by dfoll** [comment]
- [ ] Write import section for ArcMap
- [ ] Tech review/test import section for ArcMap
- [ ] Add Import section to ArcMap pdf map
- [ ] Add Import section to ArcMap solutions page
- [ ] Write export section for ArcMap
- [ ] Tech review/test export section for ArcMap
- [ ] Add Export section to ArcMap pdf
- [ ] Add Export section to ArcMap solutions page
- [ ] Write import section for ArcGIS Pro
- [ ] Tech review/test import section for ArcGIS Pro
- [ ] Add Import section to ArcGIS Pro pdf map
- [ ] Add Import section to ArcGIS Pro solutions page
- [ ] Write export section for ArcGIS Pro
- [ ] Tech review/test export section for ArcGIS Pro
- [ ] Add Export section to ArcGIS Pro pdf map
- [ ] Add Export section to ArcGIS Pro solutions page

**Comment by topowright** [comment]
I am doing the tech review of the import functionality for coordinate conversion.

**Comment by topowright** [comment]
@dfoll finding major issues with stability when using the batch tool.

**Comment by lfunkhouser** [comment]
This has been implemented. Can this issue be closed @dfoll @ACueva @topowright ?

**Comment by topowright** [comment]
Closing this issue.
