### ISSUE TITLE
BUG-000102904  The Coordinate Conversion tool of Military Tools for ArcGIS crashes ArcMap when changing the display coordinates after using the Map Point Tool.

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/coordinate-conversion-addin-dotnet#342]
<div><div>
<span><b>Salesforce ID:</b> BUG-000102904</span><br/>
<span><b>Salesforce Submitter:</b> Kory Kramer</span><br/>
<span><b>Salesforce Submit Date:</b> 2/14/2017 5:20 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Crash</span><br/>
<span><b>Salesforce Severity:</b> Medium</span><br/>
<span><b>Repro Data:</b> \\esri.com\sf_filestore\PRD\Attachments\Defects\BUG-000102904</span><br/>
<span><b>Work Around:</b> (n/a)</span><br/>
<span><b>Product:</b> ArcGIS for Desktop</span><br/>
<span><b>Functional Category:</b> ArcGIS for Defense</span><br/>
<span><b>Client Platform:</b> (n/a)</span><br/>
<span><b>Version Found:</b> 10.3.1</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> This issue will be fixed in the next release. A basemap or layer will be required before the map point tool can be enabled.</span><br/>
</div></div>

**Comment by lfunkhouser** [comment]
Duplicate of #319

**Comment by kgonzago** [comment]
Closing since it's a duplicate.
