### ISSUE TITLE
Bottom toolbar expands past screen display.  (ArcMap)

### ISSUE THREAD

**Issue by ACueva** [Esri/coordinate-conversion-addin-dotnet#345]
Populating the list of coordinates will eventually expand the display so the buttons on the bottom are no longer visible.
![2017-05-18_13-46-14](https://cloud.githubusercontent.com/assets/3093940/26222854/623046e6-3bd0-11e7-8d6d-802a08e69099.png)

**Comment by ACueva** [comment]
FYI @dfoll

**Comment by dfoll** [comment]
saw the same thing in Pro #346

**Comment by NatalieCampos** [comment]
As of the 1509 build this does not occur in either the Pro or ArcMap version of the add-in

**Comment by adgiles** [comment]
A limit has been put on the list but the window will still scroll past the bottom of the screen if the outputs are expanded:

![capture](https://user-images.githubusercontent.com/3740334/27534507-0c6cb39c-5a1c-11e7-86d7-256344aa81d1.PNG)

**Comment by topowright** [comment]
This has been verified : 
![image](https://user-images.githubusercontent.com/5488313/35403442-938ec87a-01b4-11e8-8b2b-8e31efe404d6.png)

**Comment by adgiles** [comment]
@topowight have you checked this with all the outputs expanded?

**Comment by topowright** [comment]
To test this correctly you need to expand the output sections and then see if the list expands past the buttons for export and save as.

**Comment by topowright** [comment]
Looking at this further I feel like it works as desined and we should not change the way the add-in pane is laid out. Here is my screen capture that will help explain my thoughts: 
![image](https://user-images.githubusercontent.com/5488313/35651217-c1713726-0693-11e8-8189-acdb9a528a92.png)
Currently I would not expect a user to have all of the coordinate types expanded and want to export points from the list. This list section moves down very nicely until it cannot be seen. I think we should close this as a as designed. @dfoll and @ACueva please share your thoughts.
