### ISSUE TITLE
Bottom toolbar expands past screen display. (ArcGIS Pro)

### ISSUE THREAD

**Issue by dfoll** [Esri/coordinate-conversion-addin-dotnet#346]
Populating the list of coordinates will eventually expand the display so the buttons on the bottom are no longer visible.
![image](https://cloud.githubusercontent.com/assets/5322669/26224215/360742d0-3bd6-11e7-9321-4cf25d850d63.png)

**Comment by dfoll** [comment]
same thing happens in ArcMap #345

**Comment by ACueva** [comment]
@kgonzago Not a deal breaker, just not thrilled the add-in isn't using up all the real estate it has.
![2017-05-23_15-47-12](https://cloud.githubusercontent.com/assets/3093940/26379659/35795b3a-3fcf-11e7-9593-e1231d04897f.png)

**Comment by kgonzago** [comment]
@ACueva The approach taken is the simplest but the drawback is what you experienced. Having it fill the entire dock window will require more time. I suggest we log it as a version after next issue.

**Comment by dfoll** [comment]
@kgonzago @nfeuerstein can we discuss this a bit before we decide for certain that it is an enhancement for version after next

**Comment by dfoll** [comment]
(moving back to backlog just for tracking purposes, will discuss in war room)

**Comment by NatalieCampos** [comment]
As seen in @ACueva  comment, the original issue has been fixed.  In regards to @ACueva comment about extening the list dialog, that has been placed in the enhancement request below.

https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/425

Closing issue.
