### ISSUE TITLE
Provide ability to format the Input coordinate (ArcGIS Pro)

### ISSUE THREAD

**Issue by dfoll** [Esri/coordinate-conversion-addin-dotnet#347]
Currently you can change the format of the Input, but you can not edit the notation in the way that you can use the Advanced options in the Add New Output Coordinate dialog. This is important, because the style of the Input box also controls the way coordinates in the "List" box are shown. In short I want some control over how coordinates are formatted in the "List" box.
![image](https://cloud.githubusercontent.com/assets/5322669/26224996/f0459aa4-3bd9-11e7-8307-207d2ebc14e3.png)

## Current Behavior (video attached)

Note in the video...
1. The video starts with the **Input** set to MGRS, a point is collected and it displays as MGRS.
2. DMS is added as an  **Output**, the list still only displays as MGRS
3. **Input ** is changed to DMS, the **List ** changes to DMS
4. A point is collected and both the **List** and **Input** display DMS 
5. A second **Output** is added and formatted to have no separators, degree-marks, minute-marks, or second-marks
6. The cursor then shows the newly added **Output**
6. The cursor then collects another point to show that coordinates are being collected and displayed in the **Output** properly, according to the newly added **Output**, but the **List** retains the formatting from the **Input** and moves back to the "Edit Properties" button for the **Input**
7. _Observe_ that you cannot edit the formatting of the **Input**

## Expected Behavior
You should be able to edit the **Input** so that the **List** will display the same coordinate notation as was set in the **Output**

![image](https://user-images.githubusercontent.com/5322669/42742671-80f68402-8871-11e8-8574-8fc8d8f46873.png)
The **Add New Output Coordinate** dialog has a drop-down for **Advanced** that allows you to edit the notation, 

![image](https://user-images.githubusercontent.com/5322669/42742682-a12ce806-8871-11e8-8167-16b6373f77e8.png)
the  **Edit Properties** dialog for the **Input** should have the same

[2018-07-15_20-23-43.zip](https://github.com/Esri/coordinate-conversion-addin-dotnet/files/2196503/2018-07-15_20-23-43.zip)

**Comment by dfoll** [comment]
requested for ArcMap as well #348

**Comment by topowright** [comment]
I do not think that this is needed. If a user is going to need to format the input format type that type can be added to the output list.

**Comment by topowright** [comment]
@saip please place the proper label on this issue so that we understand where in the development process this issue is.

**Comment by dfoll** [comment]
Recently rebuilt CC build 19 and MT build 122 to test

**Comment by kgonzago** [comment]
I verified the original [issue](https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/347#issue-229816192) is fixed. I also verified @BobBooth's findings of custom format from the `Edit Properties` dialog does crash or hangs Pro.

**Comment by kgonzago** [comment]
I misread the issue. I confirmed @dfoll's findings of the `Input` textbox does not update if a custom DMS notation is entered. The list of points do update but not the coordinate in the `Input` textbox.

**Comment by dfoll** [comment]
This issue needs to be sent back to @CTLocalGovTeam. Described functionality is not working. The buttons are in place to do this but the functionality does not exist.

### Additional repro steps
1. On the Coordinate Conversion pane click the `Edit Properties` button next to the input text box.
2. Highlight `MGRS` and `Custom`
3. Expand `Advanced` if it is not already expanded
4. Format the MGRS coordinate with spaces in between each piece of the MGRS coordinate (this is a supported way of supporting coordinates for the output box)
5. Click `OK`
6. Click some points in the map. 
_Note that both the `Input` box and `List` retain old formatting.

**Comment by dfoll** [comment]
@lfunkhouser this looks like an issue that was not delivered

**Comment by dfoll** [comment]
#528 was logged which is a byproduct of this needing to be completed. When this is completed #528 should be resolved.

**Comment by dfoll** [comment]
Delivery of this issue introduced #528

**Comment by BobBooth** [comment]
Rebuilt Dev branch of CC and MT to verify that the PDFs have picked up the change. They have:
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/8ab8e352-7754-4031-b5c3-0a811491abc5)
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/6ebfb5fc-d606-4a19-a73f-32d37848b57a)
