### ISSUE TITLE
Provide ability to format the Input coordinate (ArcMap)

### ISSUE THREAD

**Issue by dfoll** [Esri/coordinate-conversion-addin-dotnet#348]
Currently you can change the format of the Input, but you can not edit the notation in the way that you can use the Advanced options in the Add New Output Coordinate dialog. This is important, because the style of the Input box also controls the way coordinates in the "List" box are shown. In short. In short I want some control over how coordinates are formatted in the "List" box.
![image](https://cloud.githubusercontent.com/assets/5322669/26225112/82f22534-3bda-11e7-975a-ee26b9eceb6d.png)

## Current Behavior (video attached)

Note in the video...
1. The video starts with the **Input** set to MGRS, a point is collected and it displays as MGRS.
2. DMS is added as an  **Output**, the list still only displays as MGRS
3. **Input ** is changed to DMS, the **List ** changes to DMS
4. A point is collected and both the **List** and **Input** display DMS 
5. A second **Output** is added and formatted to have no separators, degree-marks, minute-marks, or second-marks
6. The cursor then shows the newly added **Output**
6. The cursor then collects another point to show that coordinates are being collected and displayed in the **Output** properly, according to the newly added **Output**, but the **List** retains the formatting from the **Input** and moves back to the "Edit Properties" button for the **Input**
7. _Observe_ that you cannot edit the formatting of the **Input**

## Expected Behavior
You should be able to edit the **Input** so that the **List** will display the same coordinate notation as was set in the **Output**

![image](https://user-images.githubusercontent.com/5322669/42742671-80f68402-8871-11e8-8574-8fc8d8f46873.png)
The **Add New Output Coordinate** dialog has a drop-down for **Advanced** that allows you to edit the notation, 

![image](https://user-images.githubusercontent.com/5322669/42742682-a12ce806-8871-11e8-8167-16b6373f77e8.png)
the  **Edit Properties** dialog for the **Input** should have the same

[2018-07-15_20-23-43.zip](https://github.com/Esri/coordinate-conversion-addin-dotnet/files/2196503/2018-07-15_20-23-43.zip)

**Comment by dfoll** [comment]
requested for ArcGIS Pro as well. #347

**Comment by mcalamito** [comment]
@dfoll agree with you completely. It is of huge value to have the Output List reflect the coordinate format and notation set by the user. I would be interested and open to talking through approaches to do so should this become a high priority item for a near future release.

**Comment by topowright** [comment]
I do not think that this is needed. If a user is going to need to format the input format type that type can be added to the output list.

**Comment by topowright** [comment]
@dfoll  based on my last comment do you think this still needs to be done?

**Comment by dfoll** [comment]
this still needs to be done

**Comment by topowright** [comment]
After speaking with @saip tonight the input coordinate box will allow a user to format coordinates the same way that they are allowed to format coordinates in the output list. The only difference is input coordinate box has a selection called default map units, which is set by the map. The default map coordinates will not be able to be formatted. @dfoll @lfunkhouser

**Comment by dfoll** [comment]
If it's only the default map units that cannot be formatted, I think that is acceptable

**Comment by dfoll** [comment]
Recently rebuilt CC build 19 and MT build 122 to test

**Comment by BobBooth** [comment]
I found that the custom formatted input coordinates are inconsistently applied in ArcMap 10.6 with the latest CC build.
DMS seems to work correctly.
DDM sometimes works.
MGRS never works.
https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/532

**Comment by kgonzago** [comment]
Using MT build 126, I verified @BobBooth's [comments](https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/348#issuecomment-435449655)

**Comment by dfoll** [comment]
This issue needs to be sent back to @CTLocalGovTeam. Described functionality is not working. The buttons are in place to do this but the functionality does not exist.

### Additional repro steps
1. On the Coordinate Conversion pane click the `Edit Properties` button next to the input text box.
2. Highlight `MGRS` and `Custom`
3. Expand `Advanced` if it is not already expanded
4. Format the MGRS coordinate with spaces in between each piece of the MGRS coordinate (this is a supported way of supporting coordinates for the output box)
![image](https://user-images.githubusercontent.com/5322669/48278858-b9aadd00-e41c-11e8-9733-75ee646dea67.png)
_This is what the `Edit Properties` window looks like after making changes_
5. Click `OK`
6. Click some points in the map. 
_Note that both the `Input` box and `List` retain old formatting.  
![image](https://user-images.githubusercontent.com/5322669/48278945-0ee6ee80-e41d-11e8-91a6-8b0f6a7528b6.png)
7. Click the `Edit Properties` button next to the `Input` box again.
_Note that the formatting that was set in step 4  is still  applied in the `Edit Properties` window_

**Comment by dfoll** [comment]
@lfunkhouser this looks like an issue that was not delivered

**Comment by lfunkhouser** [comment]
@dfoll have you discussed this with @saip to provide guidance?

**Comment by lfunkhouser** [comment]
From #532, MGRS not working for ArcMap. Coordinate Conversion ArcMap custom formatting not applied to MGRS, partially applied DDM

The latest build of Coordinate Conversion supports customization of the format of Input Coordinates (and their display in the List view) if the coordinates are DMS notation.
![image](https://user-images.githubusercontent.com/3801392/47930091-50b5e900-dea1-11e8-9f0b-aaf2525031b9.png)

For other notations the support is inconsistent.
For example, some coordinates in DDM are displayed with the added dashes, and others are not:
![image](https://user-images.githubusercontent.com/3801392/47930046-2cf2a300-dea1-11e8-9af1-da3f7d20a986.png)

None of the customized coordinates are displayed correctly in MGRS:
![image](https://user-images.githubusercontent.com/3801392/47930151-76db8900-dea1-11e8-9bc8-1eec9b5144ed.png)


ArcMap 10.6.0
Coordinate Conversion Add In 2.3.1.19 (10/30/18)

**Comment by BobBooth** [comment]
Doc updates complete, see 347.
