### ISSUE TITLE
Import on Coordinate Conversion pane is not working (ArcGIS Pro)

### ISSUE THREAD

**Issue by dfoll** [Esri/coordinate-conversion-addin-dotnet#349]
Coordinate Conversion build 1484

1. Click Import
2. Point to a .csv 
3. If using the cities.csv select the DD field (these are decimal degree values that were created using the coordinate conversion pane).
4. Click OK
     all four points from the table are placed on the map at the exact spot... which does not match any of the 
     points that were input.
![image](https://cloud.githubusercontent.com/assets/5322669/26226311/7a73ade6-3be0-11e7-973b-649611e802af.png)

[cities.zip](https://github.com/Esri/coordinate-conversion-addin-dotnet/files/1012630/cities.zip)

 if using TabletoPoint, you need to use two fields for input
TabletoPoint_single has a single field coordinate

**Comment by NatalieCampos** [comment]
import is currently working. closing issue
