### ISSUE TITLE
Import on Coordinate Conversion pane is not working (ArcMap)

### ISSUE THREAD

**Issue by dfoll** [Esri/coordinate-conversion-addin-dotnet#350]
Coordinate Conversion build 1484

1. Click Import
2. Point to a .csv
3. If using cities.csv select the DD field (these are decimal degree values that were created using the 
    coordinate conversion pane).
4. Click OK

Nothing happens
included .zip with three .csv to use 
[cities.zip](https://github.com/Esri/coordinate-conversion-addin-dotnet/files/1012624/cities.zip)

**Comment by NatalieCampos** [comment]
Import seems to be working now.  Closing issue.
