### ISSUE TITLE
Clicking outside map boundary populates blank coordinate list item.

### ISSUE THREAD

**Issue by ACueva** [Esri/coordinate-conversion-addin-dotnet#351]
Steps to reproduce:

1. Add a basemap to your new project.
2. From Coordinate Conversion add-in select map point tool.
3. Click a few points on the map.
4. Now click outside the map boundary. Notice a blank space appears in the list.
5. If you attempt to right click and perform any actions on the blank items in the list, ArcMap will crash.

![2017-05-18_16-07-34](https://cloud.githubusercontent.com/assets/3093940/26226934/21344ae8-3be4-11e7-8834-81e108bb84dd.png)

**Comment by ACueva** [comment]
FYI @dfoll

**Comment by kgonzago** [comment]
@ACueva good catch. I will add in some checks for empty coordinates.

**Comment by kgonzago** [comment]
@ACueva Empty items in the list are created when a user captures a coordinate that is out of bounds or off the map entirely. The batch conversion list didn't know how to display those coordinates hence the empty items. Added logic to handle that and now it displays a "NA" for those coordinates.

**Comment by ACueva** [comment]
@kgonzago My initial thoughts are if it's an invalid coordinate it shouldn't appear in the list at all.  Let me talk the workflow through with @dfoll and @NatalieCampos.  We'll let you know.

**Comment by kgonzago** [comment]
@ACueva When a user selects `Default Map Units` from the `Edit Properties` dialog and capture coordinates off the map, those coordinates are still valid. When you change to `MGRS` for example, that's when those coordinates are invalid and`NA` implemented as the display. When you change it back to `Default Map Units`, then those `NA`'s are changed back accordingly to valid coordinates.

**Comment by ACueva** [comment]
@kgonzago That makes sense.  My initial thoughts is why are we capturing stuff we don't need.  It sounds like their is a possibility it is valid, just maybe not in the coordinate selected.  I'm good.  I'll test it and let you know.

**Comment by ACueva** [comment]
@kgonzago This is the behavior I'm experiencing:
If the Display Coordinate is in DD, DDM, DMS, MGRS, USNG, or UTM.  Basically anything other than the "Default Map Unit"
It will not let me click outside of the boundary area.  No new items are added to the list.

If the Display Coordinate is set to "Default Map Unit", then I'm able to add items to the list even though they are outside the map boundaries.  The items show up on the list as NA.

Thoughts?

**Comment by kgonzago** [comment]
@ACueva I tested the add-in using `Default Map Unit` and valid coordinates are added to the list when I clicked off the map. I then switched to `MGRS` and it wouldn't allow me to add coordinates off the map. Then switched back to `Default Map Unit` and it added those coordinates and displays valid coordinates instead of `NA`. Is this the workflow you used to test the add-in?

**Comment by ACueva** [comment]
@kgonzago The workflow you mentioned is correct.  I'm wondering if there is ever a valid case for a point to be added outside of the map boundary.  If so, I'd expect all the coordinates to be able to be added.  True, they may show up as "N/A", this would mimic the behavior of the `Default Map Unit`.

I'm okay with it either way, or perhaps this becomes an enhancement.  Thoughts?

**Comment by kgonzago** [comment]
@ACueva If a basemap is added to ArcMap, the data frame takes on coordinate system of that basemap which is generally web mercator auxillary sphere if it's from AGO. The recently added basemap will also affect the display units which is set to `meters`. If you move your mouse outside of the extent of the basemap, ArcMap will still display coordinates which can be seen as valid coordinates. `Default Map Unit` option will take on that behavior based on the basemap. Hope that makes sense.

**Comment by NatalieCampos** [comment]
closing issue. This is the current behavior:

1. If the Display Coordinates are set to Default Map Units.... then coordinates will be collected even if they are outside of the map (ie basemap).  

2. If the Display Coordinates are NOT set to Default Map Units (ie anything other than Default Map Units)... then no coordinates are collected and nothing is added to the coordinate list.
