### ISSUE TITLE
BUG-000098739  The Coordinate Conversion Add-In for ArcGIS Pro 1.0.1 does not display the correct latitudinal zone letters in ArcGIS Pro 1.3.

### ISSUE THREAD

**Issue by nfeuerstein** [Esri/coordinate-conversion-addin-dotnet#354]
<div><div>
<span><b>Salesforce ID:</b> BUG-000098739</span><br/>
<span><b>Salesforce Submitter:</b> Md-Afiq Azim Md-Darom</span><br/>
<span><b>Salesforce Submit Date:</b> 8/19/2016 7:57 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Failure/Error</span><br/>
<span><b>Salesforce Severity:</b> Medium</span><br/>
<span><b>Repro Data:</b> \\esri.com\sf_filestore\PRD\Attachments\Defects\BUG-000098739</span><br/>
<span><b>Work Around:</b> (n/a)</span><br/>
<span><b>Product:</b> ArcGIS for Defense</span><br/>
<span><b>Functional Category:</b> ArcGIS for Defense</span><br/>
<span><b>Client Platform:</b> (n/a)</span><br/>
<span><b>Version Found:</b> N/A</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> (n/a)</span><br/>
</div></div>

**Comment by kgonzago** [comment]
I tested using Pro 1.4.1 and MT Builder 1508. 

CC add-in converts `33N 509027 2532665` to `33QWF0902632665`. Additionally, the Locate tool in Pro also produces the same behavior. I believe this isn't a bug but need additional eyes for verification.

FYI @NatalieCampos @ACueva @dfoll @topowright

**Comment by NatalieCampos** [comment]
Unable to test on 1.3 as the bug suggests.  
![image](https://cloud.githubusercontent.com/assets/5116835/26473515/a6d851a4-4160-11e7-87cf-c6ff53f9681a.png)
I will test on 1.4

**Comment by NatalieCampos** [comment]
In Pro 1.4 I used these coordinates for New York 

> 40.7128N 74.0059W

These were my results.
![image](https://cloud.githubusercontent.com/assets/5116835/26473670/b2b752da-4161-11e7-8c7f-52f34b296781.png)

Based on this website, I think there is not bug here. 

http://www.latlong.net/place/new-york-city-ny-usa-1848.html

Closing issue.
