### ISSUE TITLE
Import dialog should ask "Latitude Field"/"Longitude Field" instead of X/Y ArcMap

### ISSUE THREAD

**Issue by dfoll** [Esri/coordinate-conversion-addin-dotnet#357]
In the dialog to import (latitude) or (longitude) should be appended after the X and Y values when the box is checked to use two fields.

This avoids confusion and is consistent with the way core labels things parameters. In the example below when a single field is selected it is still labeled as X field (longitude) but the Y field is grayed out. When a two-field style is selected, and the parameters are labeled as X field (longitude) and Y field (latitude).

![image](https://cloud.githubusercontent.com/assets/5322669/26269405/099d2aba-3ca9-11e7-9fdd-61cd1f0c7034.png)
single field style is selected... Y Field (latitude is grayed out)

![image](https://cloud.githubusercontent.com/assets/5322669/26269415/2190c898-3ca9-11e7-900b-2c2c008ba5b0.png)
two-field style is selected, both X Field (longitude) is enabled Y Field (latitude) is enabled

**Comment by NatalieCampos** [comment]
below is the new dialog.

![image](https://cloud.githubusercontent.com/assets/5116835/26472309/4c9656d8-415a-11e7-8dc2-833cce411009.png)


Closing
