### ISSUE TITLE
Import dialog should ask "Latitude Field"/"Longitude Field" instead of X/Y ArcGIS Pro

### ISSUE THREAD

**Issue by dfoll** [Esri/coordinate-conversion-addin-dotnet#358]
In the dialog to import (latitude) or (longitude) should be appended after the X and Y values when the box is checked to use two fields.

This avoids confusion and is consistent with the way core labels things parameters. In the example below when a single field is selected it is still labeled as X field (longitude) but the Y field is grayed out. When a two-field style is selected, and the parameters are labeled as X field (longitude) and Y field (latitude).

![image](https://cloud.githubusercontent.com/assets/5322669/26269541/099d631c-3caa-11e7-8898-10a988e6286a.png)
single field style is selected... Y Field (latitude) not shown

![image](https://cloud.githubusercontent.com/assets/5322669/26269548/13a30b64-3caa-11e7-8e98-b562394e179a.png)
two-field style is selected, both X Field (longitude) is enabled Y Field (latitude) is enabled

**Comment by NatalieCampos** [comment]
@dfoll This is the new dialog.  
![image](https://cloud.githubusercontent.com/assets/5116835/26472159/cb396a44-4159-11e7-9a29-021c3d62cc20.png)
Closing this issue.
