### ISSUE TITLE
User should be able to select a point on the map and have the point highlight in the list (ArcMap)

### ISSUE THREAD

**Issue by dfoll** [Esri/coordinate-conversion-addin-dotnet#359]
After populating multiple points in the map with the Coordinate Conversion pane, the user should then be able to select one of those points on the map and have that coordinate highlighted in the list.

**Comment by topowright** [comment]
I think having the user do the opposite is good enough for now. especially since they have the ability to right click the button and use the context menu to understand the point.

**Comment by dfoll** [comment]
Recently rebuilt CC build 19 and MT build 122 to test

**Comment by kgonzago** [comment]
Will test this issue with MT build 126.

**Comment by kgonzago** [comment]
Pro:
![image](https://user-images.githubusercontent.com/6391826/48066354-565e4800-e19b-11e8-94f7-e7de7e6e624e.png)

**Comment by kgonzago** [comment]
ArcMap:
![image](https://user-images.githubusercontent.com/6391826/48066677-3e3af880-e19c-11e8-8f2e-4d54d6d26219.png)

**Comment by dfoll** [comment]
@CTLocalGovTeam In ArcMap (testing with 10.3.1) this needs some revision:  When you select points in the map, it adds to the highlighted list in the map, instead of highlighting that single coordinate.
1. Create three points in the map
2. Use the `Select Point`  tool to select a point in the map
_the point highlights, this is correct_
3. Use the `Select Point' tool to select a different point
_there are now two points highlighted in the list. This is not correct._

Both points should only be selected if the user used `Ctrl`+click when selecting the second point. If the user did just a regular single click on the map, only that point should be highlighted in the list. This is the way the list functions when you click points on the list.

**Comment by kgonzago** [comment]
@dfoll When I tested it, I just assumed the select tool just adds newly selected points to the collection of selected points. I thought the tool was designed like that. Your [comment](https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/359#issuecomment-436277868) makes sense. 

Also, since it's a select tool, should it have the ability to click and drag to create a bounding box for selection? Currently, you have to click precisely on the point to have it selected.

**Comment by BobBooth** [comment]
I agree with @dfoll - click one point should make that the selected point. CTRL-Click can add additional points to the selection. @kgonzago - I think we should add an issue to make a bounding box selection. Seems like a good enhancement, once we get the basic function working right.

**Comment by dfoll** [comment]
agreed ... bounding box is an enhancement as a new issue. fixing this behavior i think we need to have a discussion about.... i proposed yesterday that we close these issues that brought in new functionality, and log new issues for the specifics about them that don't work .... don't know if the team 100% agreed with that proposal or not

**Comment by dfoll** [comment]
Issue #536 has been logged for extra work against this issue. Documentation for the original work done by @CTLocalGovTeam has been done.
http://solutionsdev.arcgis.com/defense/help/coordinate-conversion/workflows/selecting-coordinates.htm
http://solutionsdev.arcgis.com/defense/help/coordinate-conversion/resources/january-2019-coordinate-conversion.htm
