### ISSUE TITLE
User should be able to select a point on the map and have the point highlight in the list (ArcGIS Pro)

### ISSUE THREAD

**Issue by dfoll** [Esri/coordinate-conversion-addin-dotnet#360]
After populating multiple points in the map with the Coordinate Conversion pane, the user should then be able to select one of those points on the map and have that coordinate highlighted in the list.

**Comment by topowright** [comment]
@saip please place the proper label on this issue so that we understand where in the development process this issue is.

**Comment by dfoll** [comment]
I think this is acceptable, I question if it is even useful to be able to do this with multiple points. The whole point of the issue is to select one point you have placed and be able to pick it out from the list. If this functionality works on multiple points, we are back to the same problem this issue intended to fix of "which graphic belongs to which coordinate in the list?"

**Comment by dfoll** [comment]
Recently rebuilt CC build 19 and MT build 122 to test

**Comment by BobBooth** [comment]
With ArcGIS Pro  2.2.0 and the rebuilt CC add-in, I can highlight points on the map by clicking in the list. When I click a new item in the list, it becomes "selected" in the list and the corresponding point on the map is highlighted. The previously selected item on the list becomes unselected, and the previous point loses highlight. This is good. 
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/395cd9ad-1d8c-48d3-9afc-655442ee3165)
However, when I click points on the map, each point I click stays highlighted, and the rows in the list stay highlighted. 
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/981fcb2e-0742-4709-b689-f7d2b9780214)
This seems wrong.

**Comment by BobBooth** [comment]
@dfoll - see comment above. Does this seem like the expected behavior?

**Comment by dfoll** [comment]
@BobBooth it should be go backwards of that, you should be able to select a point on the map and get it to highlight in the list. I have not started on this... i can start back helping with this today

**Comment by BobBooth** [comment]
@dfoll  - I have logged this issue: https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/530

**Comment by dfoll** [comment]
@CTLocalGovTeam In ArcGIS Pro (testing with 2,1) this needs some revision:  When you select points in the map, it adds to the highlighted list in the map, instead of highlighting that single coordinate.
1. Create three points in the map
2. Use the `Select Point`  tool to select a point in the map
_the point highlights, this is correct_
3. Use the `Select Point' tool to select a different point
_there are now two points highlighted in the list. This is not correct._

Both points should only be selected if the user used `Ctrl`+click when selecting the second point. If the user did just a regular single click on the map, only that point should be highlighted in the list. This is the way the list functions when you click points on the list.
![pointselecting](https://user-images.githubusercontent.com/5322669/48071830-36358580-e1a9-11e8-8028-776037dde6b4.png)

**Comment by dfoll** [comment]
Issue #534 has been logged for more work against the work @CTLocalGovTeam did.
Documentation for this functionality has been done
http://solutionsdev.arcgis.com/defense/help/coordinate-conversion/resources/january-2019-coordinate-conversion.htm
http://solutionsdev.arcgis.com/defense/help/coordinate-conversion/workflows/selecting-coordinates.htm
