### ISSUE TITLE
Map Point Tool is always enabled (ArcGIS Pro)

### ISSUE THREAD

**Issue by dfoll** [Esri/coordinate-conversion-addin-dotnet#368]
with build 1513 the map point tool is always enabled in coordinate conversion (didn't seem to be happening in distance and direction). The tool is always enabled, but the button does not highlight as though it is enabled. Even though the tool appears disabled, it is always enabled and you need to select a different tool, such as the explore tool to disable it.

**Comment by dfoll** [comment]
![image](https://cloud.githubusercontent.com/assets/5322669/26593721/07a99c9c-451a-11e7-9fb5-d9bfb63d5cca.png)

**Comment by kgonzago** [comment]
Spoke with @dfoll and issue will be looked at immediately.

**Comment by csmoore** [comment]
Ready to verify, this should be tested with the combined/toolbar & single add-in - to make sure both work as expected

**Comment by dfoll** [comment]
looks like it works as expected now with build 1526. i click the map point tool and it shows as blue/enabled and i can click points. When i click it again, it goes back to gray/disabled, and no longer makes points.

**Comment by dfoll** [comment]
reopening, because we realized that this was giving us some unforseen behavior, will close again when we see that appropriate issues have been logged to cover this

**Comment by kgonzago** [comment]
@dfoll Changes were added to address this issue in #388
