### ISSUE TITLE
Import Select Fields dialog dark theme visibility issues

### ISSUE THREAD

**Issue by dfoll** [Esri/coordinate-conversion-addin-dotnet#369]
For import functionality, after you click import and select your .csv, you get a select fields dialog window.

- [x] X Field (Longitude) drop down displays black text on a very dark gray background, this is extremely hard to read the drop down should be the same as other dark theme drop-downs
![image](https://cloud.githubusercontent.com/assets/5322669/26562753/14ffbb5c-447e-11e7-8cdd-f2df26a7ee94.png)
(currently)
![image](https://cloud.githubusercontent.com/assets/5322669/26562769/6c4d780e-447e-11e7-8e10-b1b9d28a89a1.png)
(should be this style)

**Comment by dfoll** [comment]
While some one is messing with this dialog there is one other issue with this dialog, however i would say it's "time permitting" and you would decide how much time it will take, as (insert issue) is a bigger deal. If taking the time to fix the overall look of the dialog is too risky, it can be added to (insert issue).

- [ ] Select Fields dialog does not match dark theme dialogs from core. Dark theme dialogs use a dark background, Select Fields does not.
![image](https://cloud.githubusercontent.com/assets/5322669/26562897/a18e88fe-447f-11e7-9b12-75f034f757be.png)
(currently looks like this)
![image](https://cloud.githubusercontent.com/assets/5322669/26562916/c3bf45ee-447f-11e7-8ec2-f6b5fac51b90.png)
(should look like this)

**Comment by csmoore** [comment]
Addressed #372 - here is how it looks now in dark mode

![image](https://cloud.githubusercontent.com/assets/3090809/26594004/0e28d80c-4534-11e7-944f-effc9019267a.png)

Note: this is just a short term fix until we can rewrite the shared arcmap/pro library to better support themes - see: https://github.com/Esri/military-tools-desktop-addins/issues/2#issuecomment-304034371

**Comment by topowright** [comment]
@csmoore I do not think this is usable: 

![image](https://cloud.githubusercontent.com/assets/5488313/26606035/301ba1a4-4545-11e7-97dc-ba6ca26953b5.png)

**Comment by topowright** [comment]
I will check with the latest build

**Comment by dfoll** [comment]
since you assigned yourself, i'll let you stamp off on it, but this is what i'm seeing with 1526.... which is atleast passable for now
![image](https://cloud.githubusercontent.com/assets/5322669/26606198/d8f7fa7a-4545-11e7-89ce-651b5727eff2.png)

**Comment by topowright** [comment]
This is now fixed for the drop down menus

**Comment by topowright** [comment]
verified 
![image](https://user-images.githubusercontent.com/5488313/34506085-9bfdae28-efde-11e7-9cfd-bcc617aa2ae8.png)
