### ISSUE TITLE
Add new Output Coordinate Window does not support dark theme

### ISSUE THREAD

**Issue by dfoll** [Esri/coordinate-conversion-addin-dotnet#371]
#### Tasks to be done June 6th 2018
- [x] Verify CMS issues addressed in CC and MT
-----------------------
**Background**

The Coordinate Conversion add-in needs to support the dark theme when opening the  properties. 
Steps to replicate: 

1. Open the Coordinate Conversion add-in
2. Click the Add Coordinate button in the output section

**Expectations:** 
The blue hover color will match the style set by ArcGIS Pro
The Properties window for adding a new coordinate will follow the Dark Theme style

**Current state:** 

![image](https://user-images.githubusercontent.com/5488313/36830760-db48aa38-1cd9-11e8-9059-eb30ef9a589f.png)

**Definition of Done:** 
The dark theme window for properties will look like similar to this: 
![image](https://user-images.githubusercontent.com/5488313/36830464-90f191e4-1cd8-11e8-84de-7992c8ac1623.png)

This might be useful. We addressed this issue for another add-in in this pull request: 
https://github.com/Esri/distance-direction-addin-dotnet/pull/493

**Comment by dfoll** [comment]
issues #369 and #370  were entered as Version-Next, I feel that we should fix those before release. This issue I think can be pushed to Version-After Next, given our current timeline.

**Comment by topowright** [comment]
Changing the title of this issue from: 
Dark Theme support for issues related to non ArcGIS Pro WPF controls
To : 
Add new Output Coordinate Window does not support dark theme

**Comment by topowright** [comment]
Being that this is a duplicate issue of #464 I am changing this issue to just focus on the window for new output coordinate.

**Comment by topowright** [comment]
@dfoll @ACueva @lfunkhouser wanted to make sure everyone sees this change.

**Comment by topowright** [comment]
This has been addressed and verified.
