### ISSUE TITLE
CC is asking for format of coordinate after it has been converted

### ISSUE THREAD

**Issue by topowright** [Esri/coordinate-conversion-addin-dotnet#374]
When you import coordinates from a spreadsheet the tool asks the format of the coordinate after it has already been added to the list. 

![image](https://cloud.githubusercontent.com/assets/5488313/26601941/aeebef98-4536-11e7-8594-18e5fc750393.png)

Reproduce this by : 
1. import a list of coordinates
2. right click on the list and select flash

The problem is the tool should not be asking where the coordinate is after it has already been marked by a graphic on the map. Also, no matter what you choose the flash happens in the same place.

**Comment by kgonzago** [comment]
This issue was fixed in #389

**Comment by dfoll** [comment]
in arcmap and arcgis pro, i am importing a .csv. the import happens as expected. there is no dialog for ambiguous coordinates. with the points imported to the list, i can flash each point, and it is flashing for a different point for each different coordinate from the list that i click. also the points are being added to the list as expected in that the tool treats the list as the first row in the input is treated like it was the first point clicked. closing
