### ISSUE TITLE
ArcGIS Pro crashes when changing the coordinate type after importing a list

### ISSUE THREAD

**Issue by topowright** [Esri/coordinate-conversion-addin-dotnet#375]
Ways to reproduce: 

1. Import a table to CC
2. Flash some of the coordinates
3. Hit the change coordinate button

Hitting this button will crash ArcGIS Pro
![image](https://cloud.githubusercontent.com/assets/5488313/26602623/ec6fdb48-4538-11e7-8297-87be52c1ebc2.png)

Also, clicking around while the tool is trying to load the data will also make it fail.

**Comment by csmoore** [comment]
I'll have a look at this one

**Comment by csmoore** [comment]
This was crashing while trying to get a UI property from the closed AmbiguousCoordsView. Switching this to a non-UI property seems to fix. 

Fixed in #387

**Comment by dfoll** [comment]
followed these exact repro steps in arcmap and arcgis pro, and did not get a crash anymore. closing
