### ISSUE TITLE
Prompting a user for location after import has already happened. 

### ISSUE THREAD

**Issue by topowright** [Esri/coordinate-conversion-addin-dotnet#376]
After a user has imported their data the tool will ask the user what the format is if they want to change the notation.

**Comment by ACueva** [comment]
I was able to get it to fail. 

![2017-05-30_16-38-29](https://cloud.githubusercontent.com/assets/3093940/26609527/706e38aa-4556-11e7-94b5-eb96007e9da8.png)

**Comment by kgonzago** [comment]
@topowright @ACueva Can you supply repro steps? Thanks.

**Comment by csmoore** [comment]
I am also intermittently seeing this issue: the Ambiguous Coordinate Dialog is being called on the CIM Thread (instead of UI thread) and failing - is there any reason to show this dialog on import? The user already supplied X, Y. Can we just disable it for import?

**Comment by dfoll** [comment]
this sounds like it was closely tied to, if not the same issue as #374
