### ISSUE TITLE
Unable to export 

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/coordinate-conversion-addin-dotnet#377]
To reproduce:
1.  collect pts
2. attempt to export point as either FC, SHP, KMZ  

All will fail.  The error thrown is below. 

![image](https://cloud.githubusercontent.com/assets/5116835/26604469/5f3b6c68-453f-11e7-8328-2d5db2ffc66c.png)

**Comment by topowright** [comment]
I have tested this on build 05-30-2017_1529 and I get the following message fro shapefile, featureclass and kml:

![image](https://cloud.githubusercontent.com/assets/5488313/26616579/84db00c4-4584-11e7-99bc-585b751cdbc9.png)

**Comment by kgonzago** [comment]
@topowright Can you supply steps when you tested this function? Thanks.

**Comment by kgonzago** [comment]
@topowright I tested with build 1535 and I didn't get that error. Please test with latest build when you get a chance. Thanks.

**Comment by topowright** [comment]
@kgonzago I did this before your pull request was merged. I have now verified that this works with today's build 05-31-2017_1535.
