### ISSUE TITLE
Ambiguous Coordinates warning given when trying to add a new output format

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/coordinate-conversion-addin-dotnet#378]
The Ambiguous Coordinates warning is thrown when attempting to add a new coordinate format output. To reproduce:
1. collect some coordinates
2. Click the add coordinate output button
3. You will recieve the Ambguous Coordiantes warning
![image](https://cloud.githubusercontent.com/assets/5116835/26605846/777fb914-4544-11e7-8555-22fa5eec54d5.png)

4. You must click ok 3 times to add a coordiante format

![image](https://cloud.githubusercontent.com/assets/5116835/26605869/8eb6332e-4544-11e7-867c-4280bef98288.png)

**Comment by kgonzago** [comment]
@NatalieCampos This issue was addressed in this PR #388

**Comment by dfoll** [comment]
this is the same as #381 with the exception that the repro steps here do not ask you to customize your coordinate. so i followed the repro steps here, no dialog about ambiguous coordinates. closing
