### ISSUE TITLE
unable to format coordinate notation

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/coordinate-conversion-addin-dotnet#381]
1.  click the new output button
2. on the new output coordinate format dialogue, select the advanced option
3. Try to adjust the notation by adding or removing a character
4.  The ambiguous corrdinates dialog will be thrown.
![image](https://cloud.githubusercontent.com/assets/5116835/26606213/ed842338-4545-11e7-9882-a0083760df9d.png)
5. Click ok on the ambiguous coordinates dialog
6. Finally, change the coordinate format

side note: for every attempt/change in the coordinate format the ambiguous coordinates warning will apear... ie adding two spaces mean that the warning will be thrown twice once for each change

**Comment by topowright** [comment]
I have verified that I also can see this bug. @dfoll has also done this.  The dialog box comes up three times before allowing a user to add a new format type.

**Comment by dfoll** [comment]
with build 1535 i have points in the list. with points in the list, i add a new output format. used the advanced drop-down to edit mgrs, remove the grid zone designator. click ok. new format adds to the output list. no dialog about ambiguous coordinates. closing.
