### ISSUE TITLE
Last location selected from the map should be on top of the list

### ISSUE THREAD

**Issue by topowright** [Esri/coordinate-conversion-addin-dotnet#382]
Currently the last location collected is placed at the bottom of the list: 

![image](https://cloud.githubusercontent.com/assets/5488313/26606919/c0c7ed0e-4548-11e7-9630-0b140e41a6fb.png)

**Comment by topowright** [comment]
The bottom coordinate that is highlighted is the last point I selected.

**Comment by dfoll** [comment]
i have verified that the last coordinate entered is added to the top of the list
