### ISSUE TITLE
Coordinate Conversion is constantly updating the values in the Output window (ArcGIS Pro)

### ISSUE THREAD

**Issue by dfoll** [Esri/coordinate-conversion-addin-dotnet#383]
When using coordinate conversion, the values in the output box are constantly updating when you move the cursor around the map. This is a problem, because if you ever want to use the copy or copy all buttons, the last point that registers in the output window is just the edge of the map.
The output section values should only be updating on click, not on constant mouse movement, Those values should stay there until the section is updated again with another Map Point Tool click on the map

**Comment by dfoll** [comment]
Just as a general broad overview of how the three pieces should be fitting together... Input should be updating dynamically, output should be static from map click to map click, and the list should have  values added to it upon click

**Comment by dfoll** [comment]
looks like we were able to get the functionality we wanted, sooner than expected thanks to @kgonzago . keep an eye on #385 for more detaisl, but most likely we will be able to be set to verify and closed soon.

**Comment by kgonzago** [comment]
@dfoll PR #388 has the changes you and other PEs requested.

**Comment by dfoll** [comment]
@nfeuerstein this is no longer an issue. I think i just forgot to close it when it was fixed.
