### ISSUE TITLE
Unable to change the coordinates in the list

### ISSUE THREAD

**Issue by topowright** [Esri/coordinate-conversion-addin-dotnet#384]
Currently in ArcMap a user cannot change the coordinate type in the list: 

![image](https://cloud.githubusercontent.com/assets/5488313/26608273/8b209668-454f-11e7-8d44-dc10e682514e.png)

This works in ArcGIS Pro, but not in ArcMap

**Comment by kgonzago** [comment]
Tested with build 1535 and coordinates do change in the batch conversion list. Please verify.

**Comment by topowright** [comment]
I have verified this on build 05-31-2017_1535. 
![image](https://cloud.githubusercontent.com/assets/5488313/26643642/d77a57d2-45e6-11e7-9365-13404309bcd6.png)
