### ISSUE TITLE
Map Point Tool needs to roll back to version 1.0 functionality

### ISSUE THREAD

**Issue by topowright** [Esri/coordinate-conversion-addin-dotnet#385]
To allow the output section to be useful we need the map point tool to function the way that it did for Military Tool for ArcGIS.  

**Current Functionality:** 
The map point tool allows a user to collect more than one location without depressing the map point tool; however, the output section does not stop updating. 

**Needed Functionality**
The map point tool function the same way it did at Military Tools 1.0

**Comment by dfoll** [comment]
@topowright spoke with @kgonzago  looks like he was able to get us what we wanted for this release, instead of having this work around and waiting until version after-next for what we really wanted
