### ISSUE TITLE
Dark Theme- Ambiguous Coordinates Box not displaying properly

### ISSUE THREAD

**Issue by ACueva** [Esri/coordinate-conversion-addin-dotnet#386]
This is what is currently displaying when in Dark Theme.
![2017-05-30_16-40-25](https://cloud.githubusercontent.com/assets/3093940/26609573/b485e858-4556-11e7-9957-50b90dfaf39b.png)

**Comment by csmoore** [comment]
I noticed this also & fixed while working on #375

**Comment by ACueva** [comment]
I can read it now. 
![2017-05-31_10-13-20](https://cloud.githubusercontent.com/assets/3093940/26644513/d1bdf616-45e9-11e7-90fb-923b3c83c851.png)
