### ISSUE TITLE
Pro crashes when saving to .txt and tab file / Export dialog misleading

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/coordinate-conversion-addin-dotnet#392]
Pro 1.4 crashes when saving to .txt file in both the single add-in and the MT. To reproduce:
1.  Collect pts.
2.  Attempt to export the pts as a txt file.  

Though exporting to .txt is not supported in the 1.1 release The Select output has the option to save as txt, csv, tab.  See screen grab.  When saving a files as file.txt or file.tab causes Pro to crash.   A fix would be to remove/clean the output dialog to remove the txt and tab options.

![image](https://cloud.githubusercontent.com/assets/5116835/26700694/267957c4-46d3-11e7-9e58-a8427fe38d2e.png)

**Comment by kgonzago** [comment]
@NatalieCampos `TXT, CSV, TAB` filter was removed. Unfortunately, there isn't just a `CSV` filter so now the fix is simply `All Types`. See below.

![image](https://user-images.githubusercontent.com/6391826/27314053-448a235e-553f-11e7-9fc1-a906134665c5.png)

By default, if a user chooses to export to `CSV`, the Save-As dialog will only export to a `CSV` file. It isn't necessary to add a file extension after the file name. For example, the above image has `test` and coordinates will be exported to `test.csv`. Please let me know your thoughts on this fix.

**Comment by NatalieCampos** [comment]
@kgonzago I am unable to test this.  When I try to export collected  coordinates as a csv Pro just crashes.  @ACueva @dfoll @topowright can you guys test this as well.  I am working on todays daily build of Pro and the 1pm build of the addin.  To reproduce:

1.  open CC
2. Collect Points
3. export point as csv
4. name file
5. click save.... this is where pro crashes.

**Comment by ACueva** [comment]
Tested the workflow.  It appears to work for me.
Daily Pro build 8934
Using Addin Build 1592

![2017-06-20_14-48-11](https://user-images.githubusercontent.com/3093940/27357577-8aeed460-55c7-11e7-9ec2-4259bd7b6462.png)

**Comment by ACueva** [comment]
@kgonzago Not trilled by auto populating the .csv extension.
I'd expect the Menu to list CSV and the name not to have the .csv appended.

It works for now but I think this would be an enhancement for a future release.

**Comment by NatalieCampos** [comment]
@ACueva ..... idk.  let me uninstall and reinstall.  Because it doesn't work for me.

**Comment by kgonzago** [comment]
@ACueva The save dialog offered to users is a Pro component. I could use the Windows save dialog that allows a user to specify the CSV file extension. Downfall to that is that a user will be offered different dialogs: the Pro one for KML, Feature classes, and Shapefiles, and a separate one for just CSV. Thoughts?

@NatalieCampos What build of Pro 2.0 are you using?

**Comment by NatalieCampos** [comment]
retired it today with the last MT build and the final pro build.  no crashes.  closing issue.

**Comment by ACueva** [comment]
@kgonzago Let's go with the way it is.  If needed we can log an issue and address the save as workflow at a later release.
