### ISSUE TITLE
CC has Export Button whereas other addins have save as

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/coordinate-conversion-addin-dotnet#393]
Coordinate conversion has export instead of save as.  Do we want CC to match the rest of Military Tools?

![image](https://cloud.githubusercontent.com/assets/5116835/26704754/2d3cb0d4-46e6-11e7-8680-a512ad18fd4a.png)

**Comment by topowright** [comment]
I think this is just a bit of a different workflow than the other add-ins. I think this should be closed with as designed.
