### ISSUE TITLE
Coordinate Conversion does not work :(

### ISSUE THREAD

**Issue by topowright** [Esri/coordinate-conversion-addin-dotnet#401]
Coordinate conversion does not allow any input to come from selecting locations on the map. I am using build: 
06-20-2017_1590

@dfoll @ACueva @NatalieCampos  Please see if you are having the same experience.

**Comment by topowright** [comment]
I have been able to get the tool to work successfully now, but this still happens every now and then. This being that the tool just does not function what so ever.

**Comment by kgonzago** [comment]
@topowright Can you provide detailed steps to repro this bug?

**Comment by topowright** [comment]
@kgonzago This is my mistake. I updated to a newer build and things were fine. I thought i closed this issue. my mistake.
