### ISSUE TITLE
Input boxes in the input section needs to support dark theme

### ISSUE THREAD

**Issue by topowright** [Esri/coordinate-conversion-addin-dotnet#402]
Here is an example of how our tool looks different compared to a GP tool: 

![image](https://user-images.githubusercontent.com/5488313/27396912-6f98397a-5669-11e7-856f-8d7e195dff84.png)
The buttons used by core do not have any surrounding element until you hover over the button: 
![image](https://user-images.githubusercontent.com/5488313/27397019-c65bdcc6-5669-11e7-800a-d36475acae46.png)

The only challenge with this example is that some of our buttons are considered on and off such as the map point tool. I will share more thoughts once I have them.

**Comment by csmoore** [comment]
Setting overridden styles to use the default resolved a few issues, but most of the larger issues (buttons, window styles) will likely need to be resolved by a redesign:

After changes in branch https://github.com/Esri/coordinate-conversion-addin-dotnet/tree/csm/%23402-pro-dark-theme :

![image](https://user-images.githubusercontent.com/3090809/34445939-54264b3c-eca5-11e7-9df5-07a89630565a.png)

Before changes:

![image](https://user-images.githubusercontent.com/3090809/34445948-63cb5d02-eca5-11e7-877b-9e1fa940243a.png)

**Comment by csmoore** [comment]
Note: the last comment applies to all of the dark theme issues - https://github.com/Esri/coordinate-conversion-addin-dotnet/issues?q=is%3Aissue+is%3Aopen+label%3A%22F-+Dark+Theme%22 

#369, #371, #379 , #400, #402

**Comment by topowright** [comment]
Can you merge your code for the input box and the list area @csmoore

**Comment by csmoore** [comment]
@topowright - PR at https://github.com/Esri/coordinate-conversion-addin-dotnet/pull/463 (note: requires review before can be merged)

**Comment by topowright** [comment]
changing this issue to only focus on the input box of the input section of the tool

**Comment by topowright** [comment]
verified : 
![image](https://user-images.githubusercontent.com/5488313/34506117-c0b4c800-efde-11e7-8d64-73b79fd7c948.png)
