### ISSUE TITLE
Ambiguous Coordinates dialog box showing for coordinates that are not ambiguous

### ISSUE THREAD

**Issue by adgiles** [Esri/coordinate-conversion-addin-dotnet#403]
**Background**
As users enter coordinates we want to support those coordinates when they enter the coordinates in either lat long or long lat. Currently this is offered, but the dialog comes up on coordinate types that it should not be present for. 

**Current state**
When adding a coordinate to the output list the Ambiguous Coordinates window comes up no matter what type of input coordinate is in the input section. 

**Expectation**
This dialog box should only show up when a user in inputting a new coordinate that could possibly be two locations in the world. It should  not show up when adding a new coordinate to the output list. 

**Two issues are in this issue:** 
1. Coordinates should be validated upon entry and then asked if the coordinate is possibly two locations
2. When adding coordinate types to the output list there does not need to be a prompt for this new type

**Replication Steps**
1. Open the add in pane
2. add coordinates to the list by using the map point tool
3. using the edit properties button in the input section change the coordinate to MGRS
4. click the add button inside the output list section
5. The user will be asked the question about ambiguous coordinates  even though this does not apply to MGRS

**Sample of what the add-in looks like when the add button is clicked**
![image](https://user-images.githubusercontent.com/5488313/36920685-63e2948e-1e16-11e8-8ab5-adbbc7e1915b.png)

**Original Issue Test**
The ambiguous dialog box gets shown when it is not required. To reproduce open up Coordinate Conversion and for the input enter 0 100.

![capture](https://user-images.githubusercontent.com/3740334/27530438-87ce9118-5a0d-11e7-93f3-ae77845d22a8.PNG)

There is no requirement to show the confirm dialog box here as the input must be lat - long as latitude cannot be above 90

**Comment by NatalieCampos** [comment]
This was seen in both ArcMap and Pro

**Comment by topowright** [comment]
I have updated the first comment of this issue with more informaiton. @adgiles if I have missed something please add to this issue.

**Comment by topowright** [comment]
@CTLocalGovTeam I have updated the first comment in this issue to hopefully provide more clarity.

**Comment by dfoll** [comment]
confirmed this is no longer happening in
  - ArcMap
  - ArcGIS Pro
added issue addressed to 
  - CC June 2018 release (cms)
  - MT June 2018 release (cms)

**Comment by ACueva** [comment]
Worked with @dfoll to verify doc changes:
- [ ] Resources tab on both single addin and MT
- [ ] PDF for Coordinate Conversion
- [ ] PDF for Military Tools
