### ISSUE TITLE
Manual inputs are not added to the Batch Conversion List

### ISSUE THREAD

**Issue by adgiles** [Esri/coordinate-conversion-addin-dotnet#404]
If you manually enter coordinates through the input field they do not get added to the list. I would expect the list to behave the same way for manual entry as it does for Map Point Tool.

**Comment by NatalieCampos** [comment]
Additionally, if coordinates are pasted into the input field the do not apear in the List.  This was tested in ArcMap 10.3.1

**Comment by dfoll** [comment]
edited the issue title, for clarification, manual entry could be either typing, or copy/paste

**Comment by lfunkhouser** [comment]
Closing. This is a duplicate of #457.
