### ISSUE TITLE
Edit output coordinate box - Sample Sample

### ISSUE THREAD

**Issue by adgiles** [Esri/coordinate-conversion-addin-dotnet#405]
When you edit the output coordinate the dialog has the words Sample Sample. Should the second sample be replaced with an example of the notation you are setting up?

![capture](https://user-images.githubusercontent.com/3740334/27530893-67aeb866-5a0f-11e7-81e9-33e1d1c4b23f.PNG)

So for example if I was setting up MGRS with a custom notation of Z S X 00000 Y 00000 then the dialog should show, something like:

Sample 31U DR 14263 12234

**Comment by dfoll** [comment]
verified fixed in build 1612
