### ISSUE TITLE
Column heading error when exporting to .csv

### ISSUE THREAD

**Issue by adgiles** [Esri/coordinate-conversion-addin-dotnet#406]
#### Tasks to be done June 6th 2018
- [x] Verify CMS issues addressed in CC and MT

----------------
If you export the list to a csv file then try to import the same csv file back in the column heading shows up in the tool dialog as sep=,

![capture](https://user-images.githubusercontent.com/3740334/27531828-e7881e94-5a12-11e7-9545-d8ed28669143.PNG)

heading in the csv file when opened in excel:

![capture](https://user-images.githubusercontent.com/3740334/27531881-0bb78ef8-5a13-11e7-95a9-6a6247edd2c7.PNG)

when opened in notepad

![capture](https://user-images.githubusercontent.com/3740334/27532176-3a4f2e0a-5a14-11e7-98b5-fa334e9b6347.PNG)

You then get an error importing, but it does work:

![capture](https://user-images.githubusercontent.com/3740334/27532020-add782c4-5a13-11e7-8d7b-c1f69569eeff.PNG)

**Comment by dfoll** [comment]
I am getting a crash when I am getting a crash when I try to verify this.

**Comment by dfoll** [comment]
verified. extraneous "sep=." column name is no longer showing up

**Comment by dfoll** [comment]
I verified this was fixed when it was first an issue, something has happened that it has been reintroduced

**Comment by kgonzago** [comment]
@dfoll Which build are you testing with?

**Comment by NatalieCampos** [comment]
This is not seen in ArcMap see screen grab below.  
![image](https://user-images.githubusercontent.com/5116835/30175824-fe64575a-93b4-11e7-9391-ec0c1dbcd2a2.png)


However is seen in Pro see screen grab below.

![image](https://user-images.githubusercontent.com/5116835/30175855-1831b042-93b5-11e7-9d8a-71dc58d51430.png)

**Comment by BobBooth** [comment]
I'm seeing the  sep=, first line in the CSV file. This also makes the default output tables not work as inputs to the convert coordinates GP tool.

**Comment by topowright** [comment]
Talking to @CTLocalGovTeam they cannot reproduce this.

**Comment by BobBooth** [comment]
I can repro this Pro 2.1.0, Coordinate Conversion Add-in 4.0.0.14 (3/6/2018).
![image](https://user-images.githubusercontent.com/3801392/37161132-e0d3f296-22bf-11e8-8beb-d11a51152112.png)
@topowright

**Comment by topowright** [comment]
@BobBooth can you give step by step instructions?

@dfoll and @ACueva I cannot replicate this with the latest build of CC using ArcGIS Pro 2.1. @llsjr2 could you also take a look at this issue?

**Comment by BobBooth** [comment]
Install the Pro 2.1.0, Coordinate Conversion Add-in 4.0.0.14 (3/6/2018).
Launch Pro.
Start a new project.
Add a map.
Open the add in.
Interactively add some points by clicking on the map.
Optionally, add some output formats.
The points on the list in my case were in Web Mercator.
Export the list to CSV.
Open the CSV file in Notepad++.
view "sep=," first line of file.

**Comment by dfoll** [comment]
confirmed @BobBooth  repo steps are good. To confirm my comments from above this was at one point tested and I verified, but it found it's way back in somehow

**Comment by CTLocalGovTeam** [comment]
@topowright @BobBooth We see a "sep=," in the CSV, when we export from the tool.

However, when we try to import the same CSV back to the tool, it does show the field name correctly as _Coordinates_ instead of _sep=,_. Please let us know whether you see the same behavior.

We could change code to export CSV without "sep=," if that is the only issue needs to be fixed. Please confirm.

We are seeing this on ArcGIS Pro 2.1.2, Coordinate Conversion Add-in 3.0 & 4.0 on a windows 7 machine.

**Comment by topowright** [comment]
This has been verified and pushed to dev

**Comment by BobBooth** [comment]
Added item to table in Military Tools June 2018 topic in CMS.
Removing Doc(CMS) tag.
