### ISSUE TITLE
Exporting to CSV to KMZ locks that as your file type option until restarting session

### ISSUE THREAD

**Issue by adgiles** [Esri/coordinate-conversion-addin-dotnet#408]
#### Background
If you try and export your list to CSV or KML the first export works correctly. If you then try and export the list again using the other file type (i.e. KML first then CSV or CSV first then KML) the file type filter remains on the first file type.

ArcMap 10.6.1 MT build 48

#### Steps to reproduce: 

1. Add points into the output list of the coordinate conversion tool
2. Export the output list to a kmz
3. Export the output list to a csv

Note: In choose location window, the save as type only allows the option to choose KMZ
#### Expected behavior
The format type in the drop down menu item of the export should be set to csv or the type that was chosen by the user

**Comment by dfoll** [comment]
just a small update to add a little more to this.... the only way out of this is to close out your arcmap session. also, it seems that exporting to feature class/shapefile is not affected by this.

**Comment by NatalieCampos** [comment]
also seen in 10.4.1

**Comment by NatalieCampos** [comment]
Not seen in ArcGIS Pro

**Comment by topowright** [comment]
This is no longer an issue.

**Comment by lfunkhouser** [comment]
@topowright Please update what version of ArcMap tested that you were able to validate that this is no longer an issue.

**Comment by topowright** [comment]
This has been added to the known issues section. This needs to be moved out of this release.
