### ISSUE TITLE
Export to KMZ

### ISSUE THREAD

**Issue by adgiles** [Esri/coordinate-conversion-addin-dotnet#409]
- [ ] Change the output type in the UI to reflect KMZ

### Original Message: 
The dialog box says export to KML but the resulting file is actually a KMZ (a zipped KML file). Either the tool should be export to KMZ or the file created should be a KML

**Comment by topowright** [comment]
I spoke to the sales engineers on this and they stated that supporting a KMZ is the right way to go. We just need to change the UI for this.

**Comment by topowright** [comment]
Currently we export to a KMZ, the dialog needs to be changed from KML to KMZ

**Comment by topowright** [comment]
switched the estimate on this issue to a one based on the fact that it is us changing a dialog prompt.

**Comment by topowright** [comment]
Based on speaking with @ScottCecilio and @jfrygeo they stated that KMZ or KML does not matter. We can keeps this KMZ and just update the UI
