### ISSUE TITLE
UTM using incorrect zone identifier

### ISSUE THREAD

**Issue by adgiles** [Esri/coordinate-conversion-addin-dotnet#410]
If you expand the coordinate parts for a UTM coordinate the Zone is using the UTM Hemisphere Band (N or S) not the UTM Band:

![capture](https://user-images.githubusercontent.com/3740334/27534187-050832da-5a1b-11e7-9da3-d53fe5d828a0.PNG)

![capture](https://user-images.githubusercontent.com/3740334/27534229-20070502-5a1b-11e7-8b35-af609cad3b3c.PNG)

**Comment by topowright** [comment]
This needs to be verified.

**Comment by topowright** [comment]
@kgonzago @jmccausland   I do not see anything showing the user to pick utm zone  band or hemi based on output. Can someone help me with this?

**Comment by topowright** [comment]
We need to provide clarity on this issue.

**Comment by topowright** [comment]
Tested this on build 4 ArcGIS Pro 2.1 and it is no longer an issue.

**Comment by lfunkhouser** [comment]
This needs to be removed from the known issues, http://solutions.arcgis.com/defense/help/coordinate-conversion/resources/release-notes.htm before the closing label can be applied. Removing the E-verified label until this is addressed in the documentation.

**Comment by BobBooth** [comment]
NGA has a caution:
"...
CAUTION: IN MANY SYSTEMS, THE LETTER AFTER THE ZONE NUMBER DESIGNATES A LATITUDINAL BAND, NOT A HEMISPHERE.
..."
http://earth-info.nga.mil/GandG/coordsys/grids/utm.html
That indicates to me that NGA has a preference for Hemisphere Zone, not a Latitudinal Band method.

**Comment by topowright** [comment]
At first I was thinking that we should go off of what NGA states, but their documentation shows that they support both, but with a warning from one. Checking how ArcGIS Pro does it I found that they use bands and we are using bands in our addin. I feel like this issue should be closed and we can readdresss this if a customer comes back to share this same issue. 

![image](https://user-images.githubusercontent.com/5488313/41678917-50c9a8d0-7481-11e8-8a31-9ae73ee63658.png)

**Comment by topowright** [comment]
There are no documentation tasks that I feel like need to be done on this issue.

**Comment by dfoll** [comment]
This was list as a [known issue](http://solutions.arcgis.com/defense/help/coordinate-conversion/resources/release-notes.htm) so I added it to the issues addressed for the June 2018 release
