### ISSUE TITLE
Flash functionality does not work for imported coordinates

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/coordinate-conversion-addin-dotnet#412]
The flash does not seem to work with coordinates that were imported.  The points highlight but the flashing cross hairs does not occur.  The flash does occur with collected coordinates. To reproduce:

1.  import coordinates from csv
2. select a coordinate from the list
3. right click and flash
4.  the coordinate will highlight green but the flash will not occur

**Comment by lfunkhouser** [comment]
This will need to be logged as a known issue. Adding the `Known Issue` and `Affects Documentation` labels. Assigning to @NatalieCampos and @dfoll to document.

**Comment by lfunkhouser** [comment]
@NatalieCampos Please update this issue with what has been done.

**Comment by NatalieCampos** [comment]
The following statement was added to the CC Known issues for ArcMap.

" Using the Flash option on imported coordinates does not work.  "

**Comment by topowright** [comment]
From my understanding we are going to change the way that we flash a coordinate in ArcGIS Pro 2.2, which means that this issue is no longer valid. @lfunkhouser I feel like this is no longer an issue. @csmoore  do you agree?

**Comment by csmoore** [comment]
@topowright - changing to highlight(green ring)/pan-to - was mentioned in passing (mainly, so the change would be backward compatible to 2.0) - but I didn't know this was the plan (and I am also about to submit a PR for fix to #428, #460)

**Comment by csmoore** [comment]
This seems to be working with changes in #465 to fix #428, #460

**Comment by topowright** [comment]
Looking into this now

**Comment by topowright** [comment]
@dfoll and I took a quick look at this. It looks good to us.

**Comment by lfunkhouser** [comment]
@topowright has the documentation been updated to remove this known issue from the release notes?

**Comment by topowright** [comment]
I have removed the known issues from Coordinate Conversion and Military tools. I have also added the statement to issues addressed for the next release of Coordinate Conversion. @dfoll I am not aware of where this is for Military Tools so I have not updated the issues addressed, but I have removed this from known issues.

**Comment by topowright** [comment]
@dfoll please help in finishing how to close this issue.

**Comment by dfoll** [comment]
documentation changes have been made by @topowright in cms.  This issue can be closed. As part of the release of Military Tools and Coordinate Conversion, all documentation will need to be republished.
