### ISSUE TITLE
Crash upon importing a previously created .csv file - ArcMap

### ISSUE THREAD

**Issue by dfoll** [Esri/coordinate-conversion-addin-dotnet#413]
1. Create some points in the map to populate the batch conversion list.
2. Export to a .csv
3. Clear all graphics
4. Import the .csv created in step 2
*crash*

I'm fairly certain it is not import functionality that is broken, because the cities.csv file in the attached folder still imports ok. I don't know what might be going on behind the scenes though when the .csv is created now, that is causing a .csv that arcmap does not like

[UPDATE]
upon looking at the cities.csv file, which works, and the testissue406.csv that causes a crash, the only difference that is obvious to me is that in the cities.csv file, has two or more fields and the testissue406.csv has only one field

to illustrate this in action, here are somethings i did....
-add a dummy column to the beginning of testissue406.csv.... now it works, 
or 
-simply duplicate the column and name column B in the .csv as coordinates2, then use the field name coordinates2 to do the import, and it works... now use "coordinates" (column A) tool still works
or
-add a dummy column in for column B (after the coordinates column) ... tool works again

[UPDATE]
the problem seems like it might be deeper than "only have one field" ... if you remove all columns from cities.csv except for "DD" it still works

[testingpoints.zip](https://github.com/Esri/coordinate-conversion-addin-dotnet/files/1103508/testingpoints.zip)

**Comment by dfoll** [comment]
found this while trying to verify #406

**Comment by dfoll** [comment]
@lfunkhouser @nfeuerstein @kgonzago my vote is that #406 stays in and there is a known issue that when you want to do an import, your .csv must have two or more fields, and in the future the tools gets enhanced to deal with a .csv that only has one field, or the tool intelligently adds a field to the output in addition to the actual coordinates, that is not intrusive to the user .... of course this is assuming that @kgonzago looks at it, and can confirm that the problem is definitely caused by having only one field, and not something else i am missing, but as stated above, it seems to me that the issue lies in having only one field in the .csv you want to import

**Comment by adgiles** [comment]
Same issue happening in Pro 2.0

**Comment by dfoll** [comment]
verified with build 1614 in Pro and ArcMap.
