### ISSUE TITLE
add build number to add in similar to ArcMap 

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/coordinate-conversion-addin-dotnet#415]
It would be useful for the add in to have the build number associated with it similar to ArcMap.  This will help ensure we know what build number we are testing or what build we found the issues in.

This is the about ArcGIS Desktop dialog.  It contains the build number 6491.  
![image](https://user-images.githubusercontent.com/5116835/27596508-98b06a26-5b14-11e7-8ef3-d69c44eea936.png)
Adding the build number to the add-ins would make it easier to identify which build we are testing/finding issues in.   I think the build number should go in the red highlighted box below.

![image](https://user-images.githubusercontent.com/5116835/27598267-cc722494-5b19-11e7-9e54-06567d332c6f.png)

**Comment by topowright** [comment]
I am working on this, but I have started this, but my last build failed.

**Comment by topowright** [comment]
- [ ] Adding Build Number to the project file
- [ ] Adding the delete staging to the pipeline
- [ ] Add the solution files to the Solutions Defense Repo

**Comment by topowright** [comment]
![image](https://user-images.githubusercontent.com/5488313/36201155-ebbeb738-1133-11e8-8f08-43c977c7b6b7.png)

This is completed
