### ISSUE TITLE
Exporting to .kml crashes Pro

### ISSUE THREAD

**Issue by dfoll** [Esri/coordinate-conversion-addin-dotnet#416]
Try exporting to KML and you get a crash, using the repro steps below, you can see that it is specifically exporting to KML that causes the crash

1. Open Coordinate Conversion
2. Collect some points with map point tool, have not noticed that the count actually matters
3. Click Export
4. Use the CSV radio button
5. Name it and click OK
(with the same points still in the batch conversion list)
6. Click Export
7. Use the Feature Class button
8. Name it in a gdb and click OK
(with the same points still in the batch conversion list)
9. Click Export
10. Use the KML radio button
11. Name it and click OK 
*crash*

**Comment by dfoll** [comment]
this may be related to #408 but the behavior is different in ArcMap, in arcmap you just get stuck with the file type being stuck on either .kmz or .csv

**Comment by NatalieCampos** [comment]
unable to reproduce this bug following @dfoll 's steps.

**Comment by dfoll** [comment]
could not reproduce with build 1615
