### ISSUE TITLE
ArcGIS Pro crashes when inputting information

### ISSUE THREAD

**Issue by topowright** [Esri/coordinate-conversion-addin-dotnet#421]
ArcGIS Pro crashes when inputting coordinates with text after inputting points on the map with the map point tool: 

Ways to replicate: 
1. Drop point on the map by using the map point tool
2. paste in the following coordinate:  39.446556, -76.085299

Result: ArcGIS Pro will fail
@lfunkhouser @nfeuerstein

**Comment by topowright** [comment]
Not all coordinates are created the same. These coordinates work: 
36° 40' 37.2"N 116° 35' 27.12"W
11SNA3655659119

**Comment by NatalieCampos** [comment]
I am unable to verify this bug. I followed @topowright 's reproduction step and used his coordiantes.  Pro 1.4 does not crash.  Closing issue.
