### ISSUE TITLE
Coordinate Conversion - User should be able to select a point on the map and have the point highlight in the list

### ISSUE THREAD

**Issue by topowright** [Esri/coordinate-conversion-addin-dotnet#426]
https://github.com/Esri/solutions-webappbuilder-widgets/issues/880
This is an issue that was documented by @dfoll in the widget, but I think it should live in the add-in. This also might not be an issue anymore.

**Comment by adgiles** [comment]
@topowright there is no coordinate list for batch conversion in the widget

**Comment by topowright** [comment]
I feel like this issue should be closed. I feel like the ability to flash a coordinate from the list satisfies this requirement, which is what we currently have in the tool.
