### ISSUE TITLE
Output List Flash Menu Item does not flash at Pro 2.1

### ISSUE THREAD

**Issue by csmoore** [Esri/coordinate-conversion-addin-dotnet#428]
Testing on Pro 2.1, selecting the Flash pop-up menu command from the Output List does not flash the coordinate marker on the map.

Repro steps:

1. Add some coordinates to the Output List using the Map Point Tool
2. Select a coordinate from the Output List.
3. Right-click and execute the Flash pop-up menu command
4. No map flash

![image](https://user-images.githubusercontent.com/3090809/30920476-0e2b539c-a372-11e7-8723-2cac1e74c3da.png)

**Comment by BobBooth** [comment]
This is a Pro-specific problem, works in ArcMap.

**Comment by topowright** [comment]
@csmoore is there any update on this item? Were you able to get feedback from @jmccausland or was he free to work on this issue with you?

**Comment by csmoore** [comment]
@topowright - I'll get with @jmccausland today.

The issue is that starting at Pro 2.1 EmbeddableControl's no longer contain a Canvas (this was never public so not sure how we knew it was there to use).

I started a fix at https://github.com/Esri/coordinate-conversion-addin-dotnet/tree/csm/%23428-flash-broke-at-Pro2.1 that just [adds a Canvas to the  control](https://github.com/Esri/coordinate-conversion-addin-dotnet/blob/csm/%23428-flash-broke-at-Pro2.1/source/CoordinateConversion/ProAppCoordConversionModule/UI/FlashEmbeddedControl.xaml#L160) 

This somewhat works but still has some issues:

1. The code seems to create the Storyboard before the control but the StoryBoard has dependencies on the control being created/visible ( this worked before because the EmbeddableControl.Canvas was always available ) so not all of the properties get set
2. Seems to only work on 2.1

So still don't have a complete fix

**Comment by csmoore** [comment]
This is fixed in https://github.com/Esri/coordinate-conversion-addin-dotnet/commit/44c65a4e6375ef102cf6cda3f0deded38104aefb - however this fix only works in Pro 2.1 - because of some possible bugs with EmbeddableControl's and canvases in Pro 2.0 (that seems to be fixed at 2.1) - so we should discuss (at scrum) how to proceed. 

If dev branches are moving to Pro 2.1 this won't be an issue, but if you want the same code to work on 2.0 and 2.1 we would have to evaluate some alternatives ( primarily (1) using patching mechanism or (2) rewriting control from scratch)

**Comment by csmoore** [comment]
Test pre-built addin added at: https://esri.box.com/s/cqn4no9vlzffj5tve1ad2digwf6knbhn

**Comment by topowright** [comment]
When testing build 10248 i find the following weird behavior. Not sure if this was in previous issues: 

Enter in the following location: 36RUU1943417239

When trying to change that coordinate with text input the flash happens in the top corner

**Comment by topowright** [comment]
Need to find out if this is an issue that was present in ArcGIS Pro 2.0

**Comment by topowright** [comment]
I opened a new issue because I feel like this is a issue that was probably already present. That information is captured in the following issue: 
https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/460

**Comment by csmoore** [comment]
Addressed in #465 - there were a few different problems going on here:

1. The implementation of the Pro SDK tool overlay changed at Pro 2.1 (and we were using an canvas object that was not public to begin with)
2. There were several bugs in how the Map Point tool was being activated generally which were now showing up in the flash since the tool had to be active to show the overlay now (before 2.1, using the internal canvas, it still worked even when not active) 

Also addresses #460
