### ISSUE TITLE
Renaming Coordinate Name does not update Edit Properties list

### ISSUE THREAD

**Issue by csmoore** [Esri/coordinate-conversion-addin-dotnet#429]
Renaming Coordinate Name does not update the coordinate names shown in the Edit Properties list. So there does not seem to be a way to make the output list follow the renamed/custom format

*Not sure if this is an issue or not, but running through the exact sequence in the certification tests, noticed this issue. Feel free to close if this is by design*

Repro steps:

1. Right-click on an output coordinate format and click Configure; expand the Advanced button.
2. From the Edit Output Coordinate Form:
    1. Change the output coordinate name
    2. Change the output coordinate format
3. Click on the edit properties button (to the right of the Input Box), and change the Input Box Display Coordinate format.

Results: 
1. The new coordinate name does not appear in this list 
2. So there is no way to set the Output List to appear in this new format/new name (this may be intended)

![image](https://user-images.githubusercontent.com/3090809/30921291-21d9988e-a374-11e7-94e3-08d9873b8bbd.png)

![image](https://user-images.githubusercontent.com/3090809/30922263-9c85f26a-a376-11e7-831e-e7f1e29411b0.png)

**Comment by BobBooth** [comment]
@csmoore - isn't the list controlled by the Input coordinate format, not the Output format?
It would be nice to be able to make the default Input format match a customized output format.

**Comment by csmoore** [comment]
@BobBooth - sounds good to me (that the input format has to be in one of those fixed formats) - so probably just a misunderstanding on my part. Closing
