### ISSUE TITLE
Export coordinate list to CSV could add comma separator between Lat/Lon values on export, and header

### ISSUE THREAD

**Issue by BobBooth** [Esri/coordinate-conversion-addin-dotnet#430]
Currently, when I export a CSV of the list of clicked locations, I get a file with rows for each value in the list.
For example:
sep=, 
Coordinates
41.407694N 084.423753W
41.585715N 083.853322W
41.086025N 083.282890W
40.762774N 082.855067W
40.906636N 082.403475W
41.229185N 082.142028W
41.407694N 081.666668W

It might be more helpful to users if we offered the option to export to CSV with the components of the coordinate pair in their own columns, e.g. comma separated values... 
41.407694N,084.423753W
41.585715N,083.853322W
41.086025N,083.282890W
40.762774N,082.855067W

Should we do this, it would be good to have a header too, e.g:
Latitude,Longitude
41.407694N,084.423753W
41.585715N,083.853322W
...

 I'm also seeing this issue: https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/406
Testing on ArcMap 10.6 (8184) with Military Tools 2.0

**Comment by topowright** [comment]
@lfunkhouser can we give this to CyberTech?

**Comment by CTLocalGovTeam** [comment]
@topowright As per our understanding, this issue is not valid anymore considering the implementation of #356, #491.
So, not adding this to list of tickets for estimation. Please confirm

**Comment by topowright** [comment]
Agreed. This issue can be closed based on the fixes that have been submitted in #491. The latest PR needs to be reviewed and then this issue can be closed.

**Comment by topowright** [comment]
@lfunkhouser @dfoll @ACueva

**Comment by lfunkhouser** [comment]
Closing. This issue is no longer valid based on #491.
