### ISSUE TITLE
Reversed (Lon/Lat) coordinate input not accepted by Distance Direction starting point box

### ISSUE THREAD

**Issue by BobBooth** [Esri/coordinate-conversion-addin-dotnet#431]
While checklist testing the coordinate conversion tool, I used this test pair:
20.82S 45.47E and 45.47E 20.82S.
The second of these (45.47E 20.82) is rejected by the input box of the Distance and Direction Line tool.
![image](https://user-images.githubusercontent.com/3801392/31028346-888d8d4e-a51b-11e7-81af-a20749a969e4.png)
Shouldn't the same code from CC work in this input box?

Testing with ArcMap 10.6, (8184) and Military Tools 2.0

**Comment by lfunkhouser** [comment]
This issue was moved to Esri/distance-direction-addin-dotnet#467
