### ISSUE TITLE
Static Code Analyzer : Streams

### ISSUE THREAD

**Issue by jmccausland** [Esri/coordinate-conversion-addin-dotnet#443]
- fix with using() statement

```using( var fs = new Stream())```
```{```
```    // do something```
```}```

**Comment by csmoore** [comment]
This appears to have already been fixed

**Comment by lfunkhouser** [comment]
@csmoore is there a way to show the verified fix? It looks like when @jmccausland logged this, the fix was proposed but I can't find the PR/commit where it was actually fixed.

**Comment by csmoore** [comment]
There were 2 methods with this condition mentioned in the report - OnImportCSVFileCommand(), LoadConfiguration() :

For this one I can't seem to link to the commit either - it seems to be a permission problem with where the commit was made (perhaps a private repo?)
https://github.com/Esri/coordinate-conversion-addin-dotnet/blob/dev/source/CoordinateConversion/CoordinateConversionLibrary/ViewModels/TabBaseViewModel.cs#L167

The other one - I did change in commit https://github.com/Esri/coordinate-conversion-addin-dotnet/commit/cc43203b064d535b649c6742ca56196bcd00a3bd - 
https://github.com/Esri/coordinate-conversion-addin-dotnet/blob/dev/source/CoordinateConversion/CoordinateConversionLibrary/Models/CoordinateConversionLibraryConfig.cs#L95
