### ISSUE TITLE
Right Click gives different UTM anwser than add-in pane

### ISSUE THREAD

**Issue by topowright** [Esri/coordinate-conversion-addin-dotnet#451]
**Background:** 
If you right click on a map and use the right click menu context to copy a UTM coordinate it is a different coordinate than what is on the coordinate view pane. 

Example: 
Coordinate Pane (This is also the coordinate ArcGIS Pro populates with the cursor on the point)
10S 600788 4051011
What is retrieved from the right click
10N 600788 4051026

**Expectation:** 

The value in the add-in pane and the value in the right click retrieve  method return the same coordinate.  Coordinates should match the default coordinate from ArcGIS Pro

Another way to validate that you are receiving the right coordinate it can be checked using GeoTrans, which can be downloaded from the following location: 
http://earth-info.nga.mil/GandG/geotrans/

**Comment by lfunkhouser** [comment]
@topowright Have you tested this in ArcMap? What version was this tested on in ArcGIS Pro?

**Comment by lfunkhouser** [comment]
Similar to #410

**Comment by topowright** [comment]
We need to give more clarity on this issue and issue #410

**Comment by topowright** [comment]
I can no longer reproduce this issue. Moving this to done to allow it to be shown in the next review.
