### ISSUE TITLE
Similar Functionality for Right-Click in Core at Pro 2.1

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/coordinate-conversion-addin-dotnet#455]
When you right-click on a coordinate in the map in 2.1, you'll see that Core developed functionality to copy coordinates. In addition, we have our copy coordinate functionality, which further allows you to select which coordinate notation you want, not just the default map units. Is this something we should be concerned with? Did core take our code to do this or did this happen simultaneously? Seems like users might get confused with two buttons that seemingly do the same thing but actually provide slightly different functionality. 

![image](https://user-images.githubusercontent.com/13024357/33438771-96da3216-d5a0-11e7-9089-66efe0734b48.png)

@lfunkhouser @topowright fyi

**Comment by joebayles** [comment]
So, can they take this and combine the two? Basically, take the icon, plural, and the ability to click on the Copy Coordinates and get the coordinate for whatever the map's system is from Core, and merge it with the mouse-over menu we developed?

**Comment by topowright** [comment]
Good catch. I will see if I can get feedback from the core team. I think combining the functionality into one location is easy and key for less confusion. @Dbarnes1 I am not sure if they used our code, but I would think the answer is no.

**Comment by jmccausland** [comment]
They are just updating the clipboard with the current coordinate readout that appears at the bottom on the map view status bar.

**Comment by topowright** [comment]
This issue was moved to ArcGIS/solutions-defense#515
