### ISSUE TITLE
Inputting coordinates manually do not populate the list function

### ISSUE THREAD

**Issue by topowright** [Esri/coordinate-conversion-addin-dotnet#457]
#### Tasks to be done June 6th 2018
- [x] Verify CMS issues addressed in CC and MT
-----------------------
@nfeuerstein found that when a user enters in coordinates via keyboard the location is not populated to the batch list: 

![image](https://user-images.githubusercontent.com/5488313/33506250-eb8130fe-d6a3-11e7-8032-c58af4c93e95.png)

The location flashes , but is not added to the list.

**Comment by nfeuerstein** [comment]
I don't know what's up but I installed the latest build of 2.1 today (10248), installed the released version of Military Tools 2.0 and now the list is being populated...

![image](https://user-images.githubusercontent.com/4732590/33860640-04cdc7e8-de97-11e7-9a05-ce36fc6b5ed9.png)

**Comment by lfunkhouser** [comment]
Adding steps from @topowright from duplicate issue #461 

Currently if you enter coordinates manually they do not add to the list. As a user anything that I enter into the input box should add to the list box. 

Steps to replicate: 
Copy coordinate into the input box- 36RUU1898318280

Nothing will add to the map or the list

**Comment by lfunkhouser** [comment]
Issue #404 was closed as a duplicate. The CMS needs to be updated to remove this issue from the Known Issues and add to the Issues Addressed in the release notes.
