### ISSUE TITLE
Unable to "Flash" the last coordinate entered

### ISSUE THREAD

**Issue by topowright** [Esri/coordinate-conversion-addin-dotnet#460]
Currently we show the last coordinate persisted in the input box; however, if you just wanted to change one or two digits of that coordinate and resubmit to get a new location the flash happens in the top left of the map. 

Ways to reproduce: 

1. Ensure that the CC Map Point Tool is not enabled (ex. click on Navigate/Explore Tool)
2. Enter in a coordinate (press enter)
3. After that coordinate has been added to the map change just parts of that coordinate and try to submit (press enter).

**Comment by csmoore** [comment]
This is new at Pro 2.1 with the test addin/fix for #428 - I see what is happening, but not sure how to fix: there is a delay from when the "flash" tool is enabled (overlays have to be associated with active tools) until when the overlay is ready to draw .

Perhaps with the changes for #457 (to make a manually entered coord do the same as a map click coord)- we can just get rid of the "flash" for this manually entered case? 

Also I noticed that the "flash" causes the CC Map Tool button to become in an invalid state (the button is depressed but Explore tool get activated) - this particular issue existed before 2.1 - will create a new issue for this

**Comment by topowright** [comment]
@csmoore Is there something that we can do to fix this using the ArcGIS Pro 2.0 build? Also should we break this into two issues?

**Comment by csmoore** [comment]
@topowright - not that I know of, the UI/XAML code actually has to be changed for 2.1 since the internal canvas that was used is no longer available. So I don't currently know how to have a solution that works on both pre-2.1, and post-2.1

**Comment by csmoore** [comment]
Addressed in #465 - see additional details at: https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/428#issuecomment-359900167
