### ISSUE TITLE
Manually inputed text to list does not function properly

### ISSUE THREAD

**Issue by topowright** [Esri/coordinate-conversion-addin-dotnet#461]
Currently if you enter coordinates manually they do not add to the list. As a user anything that I enter into the input box should add to the list box. 

Steps to replicate: 
Copy coordinate into the input box- 36RUU1898318280

Nothing will add to the map or the list

**Comment by csmoore** [comment]
Is this different from #457 - (except for the bug reported in #460 with the test addin) ?

**Comment by lfunkhouser** [comment]
Closing. Duplicate of #457
