### ISSUE TITLE
Support dark theme in Output section of Coordinate Conversion Add-in

### ISSUE THREAD

**Issue by topowright** [Esri/coordinate-conversion-addin-dotnet#464]
**Background:** 
The Coordinate Conversion add-in needs to support the dark theme when opening the  properties. 

**Steps to replicate:** 

1. Open the Coordinate Conversion add-in with Dark Theme in ArcGIS Pro
2. View the output table
3. add a input location in the Coordainte Conversion add-in and expand a output coordinate section

**Current state:** 

![image](https://user-images.githubusercontent.com/5488313/36830937-963fa080-1cda-11e8-83bd-0c4f57631388.png)

**Definition of Done:** 
The dark theme is fully supported and the table does not look foreign to ArcGIS Pro when using the dark theme. The only example I can find to help with an expected outcome is the attribute table: 
![image](https://user-images.githubusercontent.com/5488313/36831321-26302268-1cdc-11e8-9963-258a1254b5a0.png)
This would allow the header sections to be gray and the rest would be black.

**Comment by topowright** [comment]
@lfunkhouser we are not able to finish this item this sprint and we need to re estimate the work being that we do not have a clear path forward.

**Comment by topowright** [comment]
We need to make our hover for the Map Point Tool match the rest of ArcGIS Pro: 

![image](https://user-images.githubusercontent.com/5488313/36172229-0fe3ac6a-10ba-11e8-90d9-b2dd7bfea39f.png)

**Comment by lfunkhouser** [comment]
@csmoore Changing course with this issue. I'm going to have CyberTech focus on all Coordinate Conversion to keep it clean. Unassigning you based on no open PRs for updates or comments.

**Comment by csmoore** [comment]
OK - I just opened PR https://github.com/Esri/coordinate-conversion-addin-dotnet/pull/476 with where I got to yesterday. The custom datagrid and child windows remain issues.

Here is how this now looks with this PR:

![image](https://user-images.githubusercontent.com/3090809/36204637-0667cbbc-115a-11e8-8c82-7b63264f23c2.png)

**Comment by lfunkhouser** [comment]
Great! Thanks @csmoore this gives them a good starting point. @kgonzago, please review and merge if everything looks good.

**Comment by topowright** [comment]
Changed the name of this from: 
Support dark theme in Coordinate Conversion Add-in
To: 
Support dark theme in Output section of Coordinate Conversion Add-in

Also, changed the issue to just focus on the Output table of the add-in

**Comment by topowright** [comment]
This has been verified. 
![image](https://user-images.githubusercontent.com/5488313/38600192-87768e7c-3d20-11e8-96da-c4b6a3b33fe5.png)
