### ISSUE TITLE
Poor performance with large number of collect points in Output List

### ISSUE THREAD

**Issue by csmoore** [Esri/coordinate-conversion-addin-dotnet#466]
If the user adds or imports a large number of points (>200), performance degrades precipitously.

After adding a large number of points, it is also possible to crash if the (1) Map Point Tool is selected, and (2) you click both on the Output List and Map in quick succession.

To repro:

1. Obtain the import csv dataset (with 1000 points) at: https://github.com/Esri/military-tools-geoprocessing-toolbox/blob/dev/testdata/CSV/TabletoPoint.csv 
2. Import the csv 
3. Click on items in the list, it takes a long time for the halo to update.
4. Select the Map Point Tool - click on the map and items in the list - crash can occur

Crash/performance degradation occurs in [ProCollectTabViewModel.UpdateHighlightedGraphics](https://github.com/Esri/coordinate-conversion-addin-dotnet/blob/dev/source/CoordinateConversion/ProAppCoordConversionModule/ViewModels/ProCollectTabViewModel.cs#L283)

![image](https://user-images.githubusercontent.com/3090809/35303326-8dfaa308-005f-11e8-8b4e-5c4ed2aa246e.png)

**Comment by topowright** [comment]
I see the same behavior.

**Comment by CTLocalGovTeam** [comment]
@topowright While working on this issue, when working with hundreds and thousands of points retaining the list box selections(as well as on map) is degrading performance when we upload another CSV. As per our discussion, we cleared the selection when a user clicks on ImportCSV button. Please confirm.

**Comment by topowright** [comment]
This has been verified.
