### ISSUE TITLE
Removing references to the collect tab

### ISSUE THREAD

**Issue by topowright** [Esri/coordinate-conversion-addin-dotnet#467]
Currently we have moved away from having two tabs in the Coordinate Conversion add in; however, we still have references to that tab in our code: 

Here is an example of some things I have found: 
![image](https://user-images.githubusercontent.com/5488313/35404193-f1f26910-01b6-11e8-9e4b-fa6b6e75d00b.png)

We should remove this code that is not needed. If we are still relying on parts of the code form these locations, moving those elements to allow the code to be cleaner would be the desired outcome.

**Comment by lfunkhouser** [comment]
@topowright Has this been addressed by @CTLocalGovTeam?

**Comment by topowright** [comment]
This will not be captured in the release notes. Just code updates.
