### ISSUE TITLE
RegExs from DD Widget applied to all Military Tools add-ins

### ISSUE THREAD

**Issue by kgonzago** [Esri/coordinate-conversion-addin-dotnet#470]
- [x] Review RegEx used in ~~Coordinate Conversion~~ Distance and Direction Widget
- Reconfigure each notation's regular expression in the add-in to mirror what's in the widget
  - [x] DD
  - [x] DMS
  - [x] DDM
  - [x] GARS
  - [x] MGRS
  - [x] USNG
  - [x] UTM
- Use test json files from the widget in unit tests in add-in
  - [x] DD
  - [x] DMS
  - [x] DDM
  - [x] GARS
  - [x] MGRS
  - [x] USNG
  - [x] UTM

~~If needed, refactor code to accommodate for new entries added to add-in regular expressions~~

**Comment by topowright** [comment]
@kgonzago can you give an update on where we are with this task?

**Comment by kgonzago** [comment]
@topowright combining regex's now. somewhat tedious process.

**Comment by kgonzago** [comment]
The use of regex group names in the add-in is tightly coupled with the the logic of parsing coordinates for each notation. This is the same situation for the widget utilizing indexes instead. I recommend we leave them as is for now and work towards a common .net and JS libraries for regexs.  

@topowright @lfunkhouser @dfoll @ACueva Whare are your thoughts?

**Comment by kgonzago** [comment]
After talking with @csmoore, the approach going forward is to compile the CC library dll as a nuget package. The CC nuget package will then be uploaded to the MS nuget repository. Any subsequent changes will be reflected in a newly created CC nuget that will be available in the MS nuget repository. Any developer that wants to enhance any of our add-ins will be required to download via nuget the CC dll. Here is infomation on [nuget](https://docs.microsoft.com/en-us/nuget/what-is-nuget).

**Comment by topowright** [comment]
@kgonzago I am interested in understanding in how we will track this work. Are we able to use this issue as the issue to track the workings on getting the library into Nuget?
 If so does this link identify that process:
https://docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-visual-studio

If that is the process to get our library into Nuget do we need to do anything else before moving forward? It sounds pretty clear on what the approach is, but I am confused on the steps that we will have to take in order to finish this effort.

**Comment by kgonzago** [comment]
Yes that link you provided is the process for packaging the CC dll. Here are the high-level steps whenever a change is made to CC:
1. Create nuget package in VS
2. Upload to nuget repository (this can be tied into a build event)
3. Internal and externals devs will need to download the latest package using nuget package manager in VS

As for our build process, we can use the nuget api to download, unzip, and copy the dll in the appropriate directory for our add-ins to reference. Currently, the symbol editor has a directory called `dependency` that houses this dll. We can follow that same convention with the D&D and Viz add-ins.

**Comment by topowright** [comment]
- [ ] Add coordinate conversion  library as a referance

**Comment by kgonzago** [comment]
After talking with @csmoore, nuget approach would not work in a classified environment. Pivoted to the approach of adding CC as a project reference. This approach is used for [Military Tools add-ins](https://github.com/Esri/military-tools-desktop-addins).

**Comment by kgonzago** [comment]
Add CC project reference to there add-ins:
- [ ] MSE
- [ ] D&D
- [ ] VIz

**Comment by topowright** [comment]
Starting to build MSE with Jenkins

**Comment by topowright** [comment]
We found an issue with the Jenkins build that calls for a change in the CC library which @kgonzago has figured out and is working on. This took some time, but we now are moving forward.

**Comment by kgonzago** [comment]
MSE Pro add-in, Viz Pro and ArcMap add-in are complete. Tackling D&D Pro and ArcMap add-in now.

**Comment by kgonzago** [comment]
Add-ins (Pro and ArcMap) for MSE, Viz, and D&D have been updated to use the Coordinate Conversion library.

**Comment by kgonzago** [comment]
@topowright I removed the list for Jenkins build since that can be moved into a separate issue.

**Comment by kgonzago** [comment]
@ACueva @dfoll testing can commence once the build is updated.

**Comment by kgonzago** [comment]
FYI @topowright 

**Update Jenkins Build to pull CC Library for these Add-ins**
- [ ] Distance and Direction
- [ ] Visibility
- [ ] Military Symbol Editor (in progress)

**Comment by topowright** [comment]
Currently finishing up MSE

**Comment by topowright** [comment]
Finished working on MSE and moving on to Distance and Direction. @ACueva is working on Visibility.

**Comment by topowright** [comment]
@BobBooth @ACueva @dfoll MSE can now be tested from the build location on the server.

**Comment by topowright** [comment]
Distance and Direction has been finished and can be tested for Dark Theme and Reg Ex expressions

**Comment by lfunkhouser** [comment]
Updating title of issue.The DD widget RegExs were used because they were more up to date than CC widget RegExs. JSON files were used from the widget to test  CC library.

**Comment by lfunkhouser** [comment]
This issue was moved to Esri/military-tools-desktop-addins#43
