### ISSUE TITLE
Add in certificate expires soon

### ISSUE THREAD

**Issue by tpcolson** [Esri/coordinate-conversion-addin-dotnet#471]
The digital signature for the Pro 2.0 version of this add in shows it expires on 10/2018, which means this add in will not be allowed on many corporate installations after that date.

**Comment by lfunkhouser** [comment]
Certificates for code signing need to be used (code needs to be signed) while they are valid/before they expire. The expiration date just limits when the certificate is valid for signing, not how long the code will run.

**Comment by lfunkhouser** [comment]
@tpcolson thank you for reaching out. I hope our answer helped. Closing this issue.
