### ISSUE TITLE
Default Map Units isn't being parsed appropriately

### ISSUE THREAD

**Issue by kgonzago** [Esri/coordinate-conversion-addin-dotnet#477]
`Default Map Units` is currently not an option for parsing. This affects Visibility, Military Symbol Editor and Distance and Direction add-ins. Issues tied to these are:
1. [265](https://github.com/Esri/visibility-addin-dotnet/issues/265)

**Comment by topowright** [comment]
I feel like this issue can be closed and is not valid. Visibility had this issue, but I am not sure if any of the other components did or still do. @kgonzago can you clarify if this is still an issue?

**Comment by kgonzago** [comment]
This can be closed since visibility add-in now references coordinate conversion library for parsing `Default Units`.
