### ISSUE TITLE
Update target version

### ISSUE THREAD

**Issue by topowright** [Esri/coordinate-conversion-addin-dotnet#479]
We need to update the target version to be 2.1 based on the version that we are targeting for this release: 
![image](https://user-images.githubusercontent.com/5488313/36297211-502d9e5a-12a6-11e8-892d-bc933630f48d.png)

**Comment by csmoore** [comment]
Updated in PR #482 with Issue #482

**Comment by topowright** [comment]
![image](https://user-images.githubusercontent.com/5488313/36913075-963c9a2e-1dfd-11e8-909b-18d2b460d5c0.png)
This has been fixed.
