### ISSUE TITLE
Update Pro Add-in Installation description

### ISSUE THREAD

**Issue by ACueva** [Esri/coordinate-conversion-addin-dotnet#482]
Current wording looks like this:

![2018-02-28_15-15-32](https://user-images.githubusercontent.com/3093940/36818519-3bc1b23c-1c9a-11e8-9e8d-0d4f61ad3527.png)

Recommended way forward.
Add an "s" to coordinates, or re-word the sentence.

**Comment by csmoore** [comment]
Updated in PR #482 with Issue #479

**Comment by ACueva** [comment]
Adding Dev-Jenkins label as Coordinate Conversion build needs to be updated to pick up updated folder structure and location of files.

**Comment by ACueva** [comment]
PR in to address build. https://github.com/ArcGIS/solutions-defense/pull/765
FYI @topowright

**Comment by ACueva** [comment]
Found an issue where the ArcMap addin did not get updated.
Modified the file in the solution to now read:
"Quickly convert coordinates between several formats"
PR https://github.com/Esri/coordinate-conversion-addin-dotnet/pull/503
@topowright merged

**Comment by ACueva** [comment]
Changes made did not fix the issue.  Moving back for now.  @csmoore @kgonzago.  Still an issue in ArcMap.

**Comment by kgonzago** [comment]
[PR](https://github.com/Esri/coordinate-conversion-addin-dotnet/pull/504/files) submitted to fix this issue.

**Comment by dfoll** [comment]
![image](https://user-images.githubusercontent.com/5322669/41856224-6809d170-7849-11e8-9917-f4222c2647f6.png)
![image](https://user-images.githubusercontent.com/5322669/41856237-6dad131c-7849-11e8-885f-779a6a435996.png)
