### ISSUE TITLE
Entering a coordinate in the input box with no map in the project causes a crash

### ISSUE THREAD

**Issue by ACueva** [Esri/coordinate-conversion-addin-dotnet#484]
Environment tested:
Windows 10
ArcGIS Pro 2.2 Build 11658

Steps to reproduce:
1. Open ArcGIS Pro (Do not add a map to the project)
2. Open Coordinate Conversion addin
3. Paste or type the following coordinate in the input box: 39.774975N 105.037314W
4. Observe ArcGIS Pro crash.

#### Expected behavior
Users should be promoted with a statement saying would you like to add a map to allow the tool to convert coordinates.  The best case scenario would be to add the map to the project for the customer.

**Comment by topowright** [comment]
This enhancement was put in here being that this crash happens if there is not a map in place: 
https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/328
