### ISSUE TITLE
Paste multiple coordinates at one time

### ISSUE THREAD

**Issue by dfoll** [Esri/coordinate-conversion-addin-dotnet#485]
**Background:** 
Users have many ways that they receive coordinates. Some come in through chat messages or emails just to list two examples. 

**Requested enhancement:** 
A user needs to be able to copy coordinates from the clipboard to the list. This list will then be added to the map the same what it happens when a user imports coordinates from a spreadsheet. 

**Steps to create workflow:** 
Have a list of coordiantes in a text file, email or chat window
Highlight that list and copy it to the clipboard with control C or right click copy
Open the CC add in pane
right click the list window pane and select paste
click a paste/import button on the pane. 

**Requested Outcome:**
Coordinates in the clipboard can be copied to the list with a right click in the list window and a button next to the import button. 

**Work to be done:**  
- [x] Develop the feature
- [x] Document the workflow - bb/df
- [x] Update the checklist
- [x] Verify Doc
- [x] Verify the feature enhancement

**Comment by dfoll** [comment]
@topowright

**Comment by topowright** [comment]
@CTLocalGovTeam could you give a level of effort for this issue?

**Comment by CTLocalGovTeam** [comment]
@topowright Could you also add information about accepted inputs and validations if any required ?

**Comment by topowright** [comment]
**Best result if possible:** 

To have the add-in read the format automatically so the user would not have to any other action other than pasting in the coordinate. 

The system should be able to understand that there is a space, comma, or any of the other separators in the coordinate that are supported by the addin. 
![image](https://user-images.githubusercontent.com/5488313/38658116-eab8824a-3de0-11e8-98a4-ba87299aa457.png)

This can be found here; 
http://solutions.arcgis.com/defense/help/coordinate-conversion/arcmap/supported-notation-formats.htm

**Next Best Solutions (least desired)**
Prompt the user for the type of coordiante and the format.

**Comment by dfoll** [comment]
- added to Defense What's New page under Coordinate Conversion June 2018 release
- added to Coordinate Conversion June 2018 release page
- added to the Military Tools June 2018 release page
