### ISSUE TITLE
Export all coordinate types from the output section to CSV

### ISSUE THREAD

**Issue by topowright** [Esri/coordinate-conversion-addin-dotnet#491]
#### Goal
The coordinate conversion output list needs to write all outputted coordinates from the list to given file type. In that file type the output coordinate section will drive the information captured in the attribute list. The formatting chosen by the user must be preserved in the output file. 

#### Reality - Current State
The output only grabs the coordinates that are in the list not the formatted types that are in the output list

#### Expected Result
The CSV should have all coordinates from the output list populated to the output file type. This issue will focus on CSV

**Comment by CTLocalGovTeam** [comment]
@topowright As per our conversation yesterday, all the output formats are exported as single column in the exported CSV. Instead of DD, DDLat, DDLon, the CSV would contain a single column DD (name as mentioned in the output section of the add-in).

**Comment by lfunkhouser** [comment]
The feature enhancement will be added to the doc. It will include exporting to feature class #492, shapefile #493 , and kmz #495 in addition to csv.
