### ISSUE TITLE
Copying a coordinate manually causes ArcGIS Pro to crash

### ISSUE THREAD

**Issue by topowright** [Esri/coordinate-conversion-addin-dotnet#512]
#### Repo steps
Have a open map 
click a point on the map
copy the new point out of the list
clear the list
paste that coordinate into the input box 

The coordinate will show up on the map; however, ArcGIS Pro will crash

**Comment by csmoore** [comment]
I can reproduce this issue - for some reason in this scenario the list modification was happening from the CIM thread instead of Main/UI thread, change thread affinity in PR: #513

**Comment by topowright** [comment]
This was addressed in the August release.
