### ISSUE TITLE
Convert Coordinates script output is Text Data Type; therefore, not able to be used to 'Display XY Data'

### ISSUE THREAD

**Issue by nfeuerstein** [Esri/coordinate-conversion-addin-dotnet#521]
Steps to reproduce:

1. Bring in table with MGRS field
2. Use Convert Coordinates script to convert MGRS coordinates to other coordinate formats
3. Attempt to use 'Display XY Data' to add data to map.

You will be unable to use the 'Display XY Data' with the fields that were the output of the Convert Coordinates script because they're in Text format.

@lfunkhouser

**Comment by topowright** [comment]
@lfunkhouser this should be moved to the gp repo.

**Comment by lfunkhouser** [comment]
This issue was moved to Esri/military-tools-geoprocessing-toolbox#407
