### ISSUE TITLE
Retrieve/copy different formats for coordinates already in the List

### ISSUE THREAD

**Issue by dfoll** [Esri/coordinate-conversion-addin-dotnet#522]
### Background
Coordinate Conversion can be set to display multiple formats in the list for an individual point as it is collected. After it is collected, there is no elegant way to access all the coordinate formats again for an individual point from the list. Coordinate Conversion should have a simple and quick way to convert an exact point that was collected to other formats.

### Enhancement
On the list when you right-click a point a context menu pops, up that displays the coordinates listed in the output box, for the coordinate clicked on in the list.

### Current behavior
Coordinate conversion collects a point and displays it in as many different formats as have been added to the output box and also adds it to the list in the same format as what the input format is set to. Once a new point is collected the output box is updated to the newly collected point. If you want to view the set outputs for a point already collected in the list you have to
a.) collect that **exact** point again (not very precise or quick)
b.) export your entire list and get the output format from the output (not quick)
c.) right-click the **exact** point again

### Expected behavior

![image](https://user-images.githubusercontent.com/5322669/46572228-ef006e80-c936-11e8-9e97-c48df2880ef8.png)
_I want to be able to access these values later on, after I have collected more points into my list_

![image](https://user-images.githubusercontent.com/5322669/46572244-3b4bae80-c937-11e8-8272-0e8ba70e5251.png)
_I want to see what the output values were for this point_

![image](https://user-images.githubusercontent.com/5322669/46572384-ad24f780-c939-11e8-959c-0829d170c302.png)
_right-clicking the point brings up a context menu, "Output" is one of the options in that menu, when you hover over "Output" the window expands and shows what was in the output for that point_

![image](https://user-images.githubusercontent.com/5322669/46572427-58ce4780-c93a-11e8-8966-a797d74c3eac.png)
_right-clicking one of these coordinates gives the option to copy just that output to the clipboard, or copy all outputs to the clipboard_

enhancement is for ArcGIS Pro and ArcMap

**Comment by dfoll** [comment]
@lfunkhouser for prioritization

**Comment by topowright** [comment]
This capability can be done by right highlighting the point in the list and right clicking that point on the map. You cannot copy all coordinates with this workflow, but you would be able to copy at least the highlighted coordinate.

**Comment by dfoll** [comment]
The capability currently offered in the add-in does not support the requirement of this issue. What @topowright described is bullet C in the current behavior. This issue should either be worked on, or closed as won't fix, saying we have this capability is misleading.

**Comment by dfoll** [comment]
This is functioning as requested in ArcMap and ArcGIS Pro

**Comment by BobBooth** [comment]
@dfoll - this seemed to be working yesterday, but I grabbed build 58 and it seems not to  be now.
![image](https://user-images.githubusercontent.com/3801392/54292503-b4a19a00-4584-11e9-9caa-e9ded7f802da.png)

**Comment by BobBooth** [comment]
@dfoll - the View Details function works if you import a table with additional fields, but not if you have several output formats specified and you collect some point manually.

**Comment by BobBooth** [comment]
Doc changes visible in What's new, CC, and MT Release page on STG.
