### ISSUE TITLE
CC crashes when entering 45,45 (ambiguous) coordinate values in text box at Pro 2.3

### ISSUE THREAD

**Issue by BobBooth** [Esri/coordinate-conversion-addin-dotnet#525]
With the latest (10/30/18) build of CC, on ArcGIS Pro 2.3 (2.3.0-beta.1+build 14448), when I enter coordinate values in the input box and hit enter, ArcGIS Pro crashes sometimes.
To repro, in the Input box, type 0,0 and press the Enter key.
Pro crashes.
45,128 worked, but then when I tried 45,45 it crashed Pro again.
The Ambiguous coordinate dialog was not displayed.

The same build of the add-in worked correctly with values such as 0,0 and 45,45 on ArcGISPro 2.2.0.  The ambiguous coordinate dialog does appear, and it creates the points correctly.
This seems to be something that changed in Pro at 2.3.  Using today's daily of Pro and the September build 16 of CC, I am seeing a crash on entering 45,45 and pressing Enter.

This is not a problem in the ArcMap version of the add-in, on ArcMap 10.6.0 (8184)

**Comment by BobBooth** [comment]
@dfoll

**Comment by BobBooth** [comment]
@csmoore - this seems to be a Pro 2.3 vs Pro 2.2 difference that could be taken to the core folks. Can you look at what is going on?  Repro case: in CC on 2.3, enter 45,45  or 0,0 in the input text box.

**Comment by dfoll** [comment]
agree with @BobBooth it seems that anything ambiguous is crashing Pro.

**Comment by csmoore** [comment]
@BobBooth - thanks for the repro case - this one looks like a crash in CC when the ambiguous coord form is loaded (so probably not a Pro issue) - looking into cause now

**Comment by BobBooth** [comment]
@csmoore - Thanks.  The form loads in Pro 2.2, FYI.

**Comment by BobBooth** [comment]
@csmoore - I wonder if the crash when clicking "Search" button when no search term is entered (on the Edit Properties >> Symbology tab) is has a similar cause? (calling a Form from the CIM Thread instead of the UI Thread)
https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/526

**Comment by csmoore** [comment]
@BobBooth - I checked #526 and it was just a plain old null string bug vs. threading bug - https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/526#issuecomment-437993272

**Comment by csmoore** [comment]
@dfoll @saip - adding crash line: https://github.com/Esri/coordinate-conversion-addin-dotnet/blame/dev/source/CoordinateConversion/ProAppCoordConversionModule/ViewModels/ProTabBaseViewModel.cs#L806 

And Call Stack - UI is now being created on CIM Thread (source of crash):

![image](https://user-images.githubusercontent.com/3090809/48736822-5db13700-ec1a-11e8-9b1c-f0230a000804.png)

**Comment by lfunkhouser** [comment]
@saip please take a look at this one. This is seen in Pro 2.3 from the code changes. It is not a core issue.

**Comment by dfoll** [comment]
To add to what @lfunkhouser stated the PR that had this delivery was https://github.com/Esri/coordinate-conversion-addin-dotnet/pull/518

**Comment by csmoore** [comment]
PR #549 created to address the issue.

**Comment by dfoll** [comment]
Solutions\DefenseSolutions\CoordinateConversion\Testing\csm-525-crash-at-2-3-if-ambig\40 was built to test this

**Comment by dfoll** [comment]
Tested on Pro 2.3.0.15723 CC testing build 41 (see [comment](https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/525#issuecomment-450027314)).

### Cases tested 
- 0 0 
- 0 0 [DMS]
- 45 45 [DDM]
- 78 22 [DD]
- confirmed ambig coord dialog does display if `Show Ambiguous Coordinates Dialog` is checked

![image](https://user-images.githubusercontent.com/5322669/50484517-deecae00-09be-11e9-8d0f-d8b8c0a9321c.png)
_Ambig coords dialog is showing. Also, some test coordinates I used._

**Comment by dfoll** [comment]
...\Solutions\DefenseSolutions\CoordinateConversion\January2019\Dev\41 was built post-merge to test this

**Comment by dfoll** [comment]
Looks good from ..\Dev\41. I did not test on ArcMap as this problem was listed only for Pro. @BobBooth can you also take a look and move to Done and add verified label if it looks good to you.

**Comment by BobBooth** [comment]
I tested from \Dev\41 and I'm seeing the ambiguous coordinate panel pop up when needed, no crashing.

**Comment by lfunkhouser** [comment]
Need to test on Pro 2.2 to verify this is fixed

**Comment by csmoore** [comment]
Testing these repro steps from latest dev branch (Built at `Commercial\Solutions\DefenseSolutions\CoordinateConversion\January2019\Dev\44`), on **Pro 2.2.0**.  I am unable to reproduce this issue.

NOTE: branch `CTLocalGovTeam-dev` for #138 was also tested, and I could not see the issue.

@lfunkhouser @dfoll @saip @kgonzago Can we verify that this is not a configuration issue or there are not additional steps required?

![image](https://user-images.githubusercontent.com/3090809/51138221-83b81980-180e-11e9-8bbe-a19f2c0da0eb.png)

![image](https://user-images.githubusercontent.com/3090809/51137531-c5e05b80-180c-11e9-9435-a27c7b160342.png)
