### ISSUE TITLE
CC crashes when searching for symbol if Search Box Empty

### ISSUE THREAD

**Issue by BobBooth** [Esri/coordinate-conversion-addin-dotnet#526]
With the latest  build of CC (10/30/18) and Pro 2.2.0 (released), I can add a point location to the map, then open the Properties pane for the input points and click the Symbology tab.
When I interact with this tab, Pro becomes unstable.
On several occasions, when I click the "Search" button to search for a symbol (and no text has been entered in the search box), I get an an error message that "Object reference is not set to an instance of an object"
![image](https://user-images.githubusercontent.com/3801392/47748534-705ece80-dc61-11e8-8350-ebcf85b8a679.png)
Sometimes scrolling down the list of symbols crashes Pro, and sometimes clicking the Search button crashes Pro.
![image](https://user-images.githubusercontent.com/3801392/47748428-2b3a9c80-dc61-11e8-9d3a-c064a760f0f6.png)

If I interact with the symbology, opening and closing the window and choosing different symbols, extra copies of the  Edit Properties window get created and then left behind - if I hover over the Pro item in my task bar, I can see and switch to several of them (which have different symbols).
![image](https://user-images.githubusercontent.com/3801392/47870494-0de00c80-dde0-11e8-865a-bb2b8d8ad99e.png)

Clicking the Search button **when there is nothing in Search Box** results in the  "Object reference is not set to an instance of an object" error, and the Edit Properties window seems to disappear. Actually, it loses focus and goes behind the main ArcGIS Pro window.  You can re-open the Edit Properties window after this, but that is what creates a second (or third, etc...) copy of the window.

**Comment by BobBooth** [comment]
@dfoll

**Comment by csmoore** [comment]
Addressed in PR #543

**Comment by dfoll** [comment]
MT build 159 can be used to test this
