### ISSUE TITLE
Coordinate Conversion custom input format crashes Pro

### ISSUE THREAD

**Issue by BobBooth** [Esri/coordinate-conversion-addin-dotnet#528]
With Pro 2.3 and the latest CC build, if I collect a series of locations, then customize the input format, set it to MGRS and add a couple of dashes for formatting, Pro gives invalid coordinate message and crashes.
1. Collect some locations
![image](https://user-images.githubusercontent.com/3801392/47813994-f131cf00-dd22-11e8-8175-8b012684ef05.png)
2.  Customize Input coordinates. 
3. Set the Display Coordinate to MGRS
4. Click Custom.
5. Change the formatting in the Advanced box to have two dashes between Z and SX
Click OK.
![image](https://user-images.githubusercontent.com/3801392/47814188-62718200-dd23-11e8-8a70-8dc5cbe53d35.png)
![image](https://user-images.githubusercontent.com/3801392/47814293-ac5a6800-dd23-11e8-82e0-ce73cb2952fe.png)

Asterisks also crash Pro
![image](https://user-images.githubusercontent.com/3801392/47815689-6f907000-dd27-11e8-87d6-63cc00906787.png)

If you do not have any coordinates in the list, instead of crashing, you seem to get caught up in an infinite loop of Invalid Coordinate boxes. Try to click on the map, the box pops up, but it cannot be closed.
![image](https://user-images.githubusercontent.com/3801392/47867132-036d4500-ddd7-11e8-96c2-9fb39f370ab0.png)

ArcGIS Pro 2.3.0 beta 1 build 14476
Coordinate Conversion 4.1.1.19 (latest October build)

I am also seeing similar bad behavior on Pro 2.2.0 - Adding -- to a custom MGRS input coordinate format, after locations have been added to the map, causes the Edit Properties pane (and other parts of the Pro UI) to become unresponsive after you click OK and get the Invalid Coordinate message.

**Comment by BobBooth** [comment]
To repro:
Add about 15 locations to the list by clicking on the map.
Change the Input format.
Choose MGRS for the display format.
Choose Custom.
Format the MGRS string with -- as separators.
![image](https://user-images.githubusercontent.com/3801392/48279076-7a30c080-e41d-11e8-9b2d-b541de99f06b.png)

Click OK.
Get a series of invalid coordinate messages.
![image](https://user-images.githubusercontent.com/3801392/48279100-8d439080-e41d-11e8-8d00-e907daf24752.png)

Start clicking OK to close the Invalid Coordinates message boxes.
Pro stops working.
![image](https://user-images.githubusercontent.com/3801392/48279136-a5b3ab00-e41d-11e8-89b6-9f30448c9733.png)

**Comment by dfoll** [comment]
To add to what @lfunkhouser stated the PR that had this delivery was https://github.com/Esri/coordinate-conversion-addin-dotnet/pull/518

**Comment by dfoll** [comment]
Using the testing build in ...\Solutions\DefenseSolutions\CoordinateConversion\Testing\CTLocalGovTeam-dev\39 this looks to be fixed.

### Cases tried
- Z--SX00000Y00000 [MGRS]
- Z*S*X00000*Y00000 [MGRS]
- A0°/B0'/C0.0#"N X0° Y0' Z0.0#"E [DMS]

**Comment by BobBooth** [comment]
I tried it too, did not get the crash.
