### ISSUE TITLE
Coordinate Conversion changing symbol for locations loses selection and location highlight

### ISSUE THREAD

**Issue by BobBooth** [Esri/coordinate-conversion-addin-dotnet#531]
### Current Behavior:
The Coordinate Conversion add-in allows you to add coordinate locations to a map, select the coordinates that have been added from the list (or the map) and change symbology of those locations on the map.
If you have some coordinates added to the map and you select one or more of them, they are highlighted with a green halo.
![image](https://user-images.githubusercontent.com/3801392/47869127-7a590c80-dddc-11e8-8953-ee75bd260128.png)
If you change the symbology for a point feature layer, it retains any selection.
However, if you change the symbology for coordinate locations, it loses the selection on the map and in the table.
![image](https://user-images.githubusercontent.com/3801392/47869275-ef2c4680-dddc-11e8-9532-d696c977160d.png)

### Expected Behavior:
If I change the symbology of the locations I've added with the Coordinate Conversion pane, any selection that I've made on those locations should be persisted. The new symbol should be highlighted, and the selection in the list should remain.

### Repro steps
1. Use the `Map Point Tool` from the Coordinate Conversion pane to add some points to the map.
2. Select a point either with the `Select Point` tool or by clicking a coordinate in the list.
3. Click the `Edit Properties` button on the Coordinate Conversion pane.
4. Click the `Symbology` tab.
5. Click the `Cross 3` symbol
6. Click `Apply` 
_note that all symbols correctly change, but the selection you had is lost_

ArcGIS Pro 2.3.0 beta 1 build 14476
Coordinate Conversion 4.1.1.19 (latest October build)

**Comment by lfunkhouser** [comment]
@CTLocalGovTeam This issue was logged as a result of UAT on delivered functionality on #422

**Comment by dfoll** [comment]
To add to what @lfunkhouser stated the PR that had this delivery was https://github.com/Esri/coordinate-conversion-addin-dotnet/pull/518

**Comment by dfoll** [comment]
@saip this does not look to be fixed. I have added explicit repro steps to highlight the behavior that shows the problem.

**Comment by dfoll** [comment]
This looks to be fixed in #548 following repo steps listed in issue, when you change the symbol while you already have a coordinate selected, that selection persists in ArcGIS Pro.

**Comment by dfoll** [comment]
will test from dev build in CC and MT and move to Done

**Comment by dfoll** [comment]
\Solutions\DefenseSolutions\CoordinateConversion\January2019\Dev\42
_and_
\Solutions\DefenseSolutions\MilitaryToolsForArcGIS\January2019\Dev\177

can be use to test this to move it to Done

**Comment by kgonzago** [comment]
Verified fix using:
1. \Solutions\DefenseSolutions\CoordinateConversion\January2019\Dev\42
2. \Solutions\DefenseSolutions\MilitaryToolsForArcGIS\January2019\Dev\177

**Comment by kgonzago** [comment]
Checklist updated: [PR](https://github.com/ArcGIS/solutions-defense-test-catalog/pull/197)

**Comment by lfunkhouser** [comment]
@BobBooth @dfoll @kgonzago is the `V - Pro 2.3` label accurate? Was it an issue at Pro 2.1 too or just at Pro 2.3? Was this a fix done on Pro 2.1 but only affected the Pro 2.3 functionality? Just confirming if we need two versions of the add-in (Pro 2.1-2.2 and a Pro 2.3) or still just the one.

**Comment by BobBooth** [comment]
@lfunkhouser - this was a fix for an issue with new functionality (changing the symbology of the points) that was not available earlier. It showed up when we were testing on Pro 2.3.  I will test on Pro 2.1 just to make sure, but I believe that the new add-in should work in 2.1/2.2 as well.
