### ISSUE TITLE
Coordinate Conversion ArcMap custom formatting not applied to MGRS, partially applied DDM

### ISSUE THREAD

**Issue by BobBooth** [Esri/coordinate-conversion-addin-dotnet#532]
The latest build of Coordinate Conversion supports customization of the format of Input Coordinates (and their display in the List view) if the coordinates are DMS notation.
![image](https://user-images.githubusercontent.com/3801392/47930091-50b5e900-dea1-11e8-9f0b-aaf2525031b9.png)

For other notations the support is inconsistent.
For example, some coordinates in DDM are displayed with the added dashes, and others are not:
![image](https://user-images.githubusercontent.com/3801392/47930046-2cf2a300-dea1-11e8-9af1-da3f7d20a986.png)

None of the customized coordinates are displayed correctly in MGRS:
![image](https://user-images.githubusercontent.com/3801392/47930151-76db8900-dea1-11e8-9bc8-1eec9b5144ed.png)

ArcMap 10.6.0
Coordinate Conversion Add In 2.3.1.19 (10/30/18)

**Comment by lfunkhouser** [comment]
Expected functionality of #348 Closing as duplicate

**Comment by dfoll** [comment]
To add to what @lfunkhouser stated the PR that had this delivery was https://github.com/Esri/coordinate-conversion-addin-dotnet/pull/518

**Comment by dfoll** [comment]
This issue sounds like it is closely related to issue #528, but is logged for ArcMap. I tried these cases
- Z--SX00000Y00000 [MGRS]
- Z*S*X00000*Y00000 [MGRS]
- A0°/B0'/C0.0#"N X0° Y0' Z0.0#"E [DMS]
- Y0.0#####N??X0.0#####E [DD]
- A0° B0.0###'=?=X0° Y0.0###' [DDM] 
-  X0° Y0.0###'E @ A0° B0.0###'N [DDM]
- Z-S-X00000-Y00000 
in ArcMap with no issues, the List and Input boxes honored what was entered in the `Edit Properties` window.

**Comment by BobBooth** [comment]
Using a dash/hyphen in a DDM custom input, some outputs not displaying correctly.
![image](https://user-images.githubusercontent.com/3801392/50456327-98954180-0921-11e9-9dd7-e6b76f4d4ea8.png)

**Comment by BobBooth** [comment]
Also, dashes don't seem to be showing up in MGRS strings
![image](https://user-images.githubusercontent.com/3801392/50456378-fde93280-0921-11e9-831d-e6f9a64f6743.png)

**Comment by BobBooth** [comment]
@dfoll - ignore previous comments. I reinstalled and am seeing the correct behavior.

**Comment by dfoll** [comment]
@BobBooth I have done documentation for this. Can you please review?

**Comment by BobBooth** [comment]
The https://solutionsdev.arcgis.com/defense/help/coordinate-conversion/workflows/change-the-display-of-input-coordinates.htm topic looks good to me.
