### ISSUE TITLE
Coordinate Conversion highlight difficult to see in ArcMap

### ISSUE THREAD

**Issue by BobBooth** [Esri/coordinate-conversion-addin-dotnet#533]
Using ArcMap 10.6.0
When you select a CC location on the map (or in the List) the point is highlighted with a faint green outline.
![image](https://user-images.githubusercontent.com/3801392/47931778-37636b80-dea6-11e8-8ea9-727fe1d83307.png)

The highlight halo needs to be larger in order to make it more visible, as it is in ArcGIS Pro.
![image](https://user-images.githubusercontent.com/3801392/47931943-9a550280-dea6-11e8-87db-d1e9b5642719.png)

ArcMap 10.6.0
Coordinate Conversion Add In 2.3.1.19 (10/30/18)

**Comment by csmoore** [comment]
Addressed in #572 - Enlarged Halo and selected symbol small in ArcMap.

Should look like this now:

![image](https://user-images.githubusercontent.com/3090809/52348378-2751af80-29f2-11e9-8a21-b678ff46b40a.png)

**Comment by dfoll** [comment]
Tested from feature branch. 
![image](https://user-images.githubusercontent.com/5322669/52350955-ab5a6600-29f7-11e9-9422-4ea7d3d3d2a1.png)
Will build to Dev and test

**Comment by dfoll** [comment]
Built 
Commercial\Solutions\DefenseSolutions\CoordinateConversion\March2019\Dev\39
and 
Commercial\Solutions\DefenseSolutions\MilitaryToolsForArcGIS\March2019\Dev\210

to finish testing

**Comment by dfoll** [comment]
This is what it looks like testing from Commercial\Solutions\DefenseSolutions\MilitaryToolsForArcGIS\March2019\Dev\210
![image](https://user-images.githubusercontent.com/5322669/52352776-3e48cf80-29fb-11e9-9f58-f03d024cbd40.png)

**Comment by dfoll** [comment]
doc is ready for review at
- https://solutionsdev.arcgis.com/defense/help/coordinate-conversion/resources/march-2019-coordinate-conversion.htm
- Commercial\Solutions\DefenseSolutions\CoordinateConversion\March2019\Dev\40
- https://solutionsdev.arcgis.com/defense/help/military-tools/resources/march-2019-military-tools-for-arcgis.htm
- Commercial\Solutions\DefenseSolutions\MilitaryToolsForArcGIS\March2019\Dev\212

also 
- https://solutionsdev.arcgis.com/defense/help/military-tools/
- https://solutionsdev.arcgis.com/defense/help/coordinate-conversion/
- https://solutionsdev.arcgis.com/defense/what-is-new/
after [PR}(https://github.com/ArcGIS/arcgis-solutions-website/pull/7524) is reviewed and merged

**Comment by BobBooth** [comment]
Tab nav works correctly on solutionsDev, March 2019 pages display for CC and MT.
