### ISSUE TITLE
The coordinate Conversion add-in crashes Pro when importing a CSV file of coordinates

### ISSUE THREAD

**Issue by BobBooth** [Esri/coordinate-conversion-addin-dotnet#538]
#### Current behavior:
On Pro 2.3 with the latest CC addin, when I click Import on the CC pane and browse to the CSV file attached file (NewExportTest.zip) I am prompted to choose the field to use. Neither Coordinate nor MGRS works - Pro crashes when I run the import process.

[NewExportTest.zip](https://github.com/Esri/coordinate-conversion-addin-dotnet/files/2558877/NewExportTest.zip)

#### Expected behavior:
The add-in should allow me to import the attached file using either it's coordinates column or its MGRS column. Neither is working now.

I tested this with Pro 2.2 and the released version of CC.
The MRGS field imported correctly, but I got at "please enter a valid coordinate" message if I try to import using the Coordinate field.

ArcGIS Pro 2.3.0-beta.1+build.14496
Coordinate Conversion 4.1.1.16 (9/14/18)

**Comment by BobBooth** [comment]
@dfoll & @lfunkhouser - this seems to be one to take to the core folks.

**Comment by lfunkhouser** [comment]
@BobBooth can you confirm or check how this works on the following:
- [ ] Released version (Sept 2018) of CC on Pro 2.2
- [ ] Released version (Sept 2018) of CC on Pro 2.3
- [ ] Latest build of CC on Pro 2.2
- [ ] Latest build of CC on Pro 2.3

I want to make sure everything has been covered before @dfoll follows up with the core team tomorrow.

**Comment by BobBooth** [comment]
With today's daily, Pro 2.3.0-beta.1+build.14508 I am no longer seeing the crash. I think I had a bad build of Pro 2.3 for CSV files.  Export to CSV is also working.
I am still getting the "please enter a valid coordinate" message when I try to import the contents of the "coordinate" column of that table (issue https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/539), and no results, but no crash.

**Comment by BobBooth** [comment]
@lfunkhouser @dfoll - this is non-repro with today's daily. I've removed the other tags and added non-repro tag.

**Comment by BobBooth** [comment]
@dfoll & @lfunkhouser - actually, I just reproduced it again with the daily Pro 2.3 build.

**Comment by csmoore** [comment]
I tested on Pro.2.3.14508 and could not repro a crash. I do notice that performance seems to have gotten slower using the latest version of the addin, so not sure if that might be related to the problems @BobBooth is seeing on just his machine.

**Comment by dfoll** [comment]
Pro 2.3.0.15723 
CC 42

I am experiencing a crash when I try to import a .csv 

[Airports.zip](https://github.com/Esri/coordinate-conversion-addin-dotnet/files/2741565/Airports.zip)

Will try to get a newer build of Pro and post results here

**Comment by dfoll** [comment]
installed Pro 2.3.0 (build 15768) (build number is no longer showing on About page)

This is still happening with Airports.csv (DMS) and MontereyPointsOfInterest.csv (MGRS)

**Comment by kgonzago** [comment]
I am able to consistently repro this issue in Pro 2.3 using the CSV file @dfoll attached in his [comment](https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/538#issuecomment-452747781). I narrowed it down to how the ambiguous dialog is instantiated during the import of coordinates from a CSV file. This [line](https://github.com/Esri/coordinate-conversion-addin-dotnet/blob/dev/source/CoordinateConversion/ProAppCoordConversionModule/ViewModels/ProTabBaseViewModel.cs#L823) in a QueuedTask thread may be the issue.

@saip @CTLocalGovTeam  Can you take a look at this issue?

**Comment by lfunkhouser** [comment]
@saip please provide an update on this issue. This is critical for the January release.

**Comment by csmoore** [comment]
Dev build created for QC at: `Solutions\DefenseSolutions\CoordinateConversion\January2019\Dev\46`

**Comment by dfoll** [comment]
Tested using CC 46 on Pro 2.3, the file @BobBooth provided and the files I provided are all working now for importing.

Tested using MT 183 on Pro 2.3, the file @BobBooth provided and the files I provided are all working now for importing.
[Testpoints.zip](https://github.com/Esri/coordinate-conversion-addin-dotnet/files/2764395/Testpoints.zip)
