### ISSUE TITLE
Coordinate Conversion addin gives "please enter a valid coordinate" for table of valid coordinates

### ISSUE THREAD

**Issue by BobBooth** [Esri/coordinate-conversion-addin-dotnet#539]
Using the Released version (Sept 2018) as well as the latest build of CC on Pro 2.2, I'm seeing an issue on import of a particular CSV table not working. When I browse to the table and specify the "Coordinate" field (contains values like "36.662872 -121.609567") and run the import process results in "please enter a valid coordinate" message, 
[NewExportTest.zip](https://github.com/Esri/coordinate-conversion-addin-dotnet/files/2558877/NewExportTest.zip)

If I import the MGRS coordinate it works fine.
The table looks like this:

Coordinate,MGRS
36.662872 -121.609567,10S FF 24262 58375
36.682064 -121.764953,10S FF 10347 60314
36.65265 -121.798825,10S FF 07362 57012
36.582895 -121.880858,10S FF 00119 49185
36.597818 -121.873599,10S FF 00750 50849
36.587394 -121.841267,10S FF 03655 49727
36.604657 -121.911156,10S EF 97382 51568
36.615057 -121.899023,10S EF 98453 52735
36.603516 -121.955828,10S EF 93387 51398
36.615887 -121.941907,10S EF 94617 52783
36.57764 -121.670331,10S FF 18962 48842

**Comment by BobBooth** [comment]
Using Pro 2.3.0.15769 (1/10/19) and the Coordinate Conversion add-in built today, at \DefenseSolutions\CoordinateConversion\January2019\Dev\44 this issue seems to be resolved.
I can import both the MGRS column and the Coordinate column, without error messages and with expected point results.

**Comment by BobBooth** [comment]
This problem seems be back in the Dev build, built today, on Pro 2.3.

**Comment by BobBooth** [comment]
OK. I've tried to repro this today, and I can't.  There is some sequence of steps that puts it into this state, but I can't reliably reproduce them.

**Comment by csmoore** [comment]
I could not repro this issue release several different combinations of input/output coordinate display settings and map projections. The issue seems similar to #551 but the issue was reopened after that fix was #554 merged.

Recommend closing again until we have a consistent set of repro steps.

Tested on Pro 2.3 (final) and January, 2018 release
