### ISSUE TITLE
Coordinate Conversion mismatch between location output value and location input value

### ISSUE THREAD

**Issue by dfoll** [Esri/coordinate-conversion-addin-dotnet#545]
### Background
- This is an accuracy issue. We can only place back on the map as accurate as what we originally collected and displayed to the user. This is easiest to understand in the context of working with MGRS coordinates. MGRS measures down to a 1-meter grid square. When we collect a point, only the coordinates of that 1-meter grid square are given to the user. When we go to then place those coordinates, the graphic for coordinate conversion is placed at the corner of that 1-meter grid square.

### Current behavior
![image](https://user-images.githubusercontent.com/5322669/49474819-83b60a00-f7ca-11e8-929b-b3ba032a2e8c.png)

### Repro steps

1. Switch your display coordinate to a format other than default
2. Use Coordinate Conversion pane to collect a location from the map. 
3. Copy those coordinates
4. Clear the Coordinate Conversion pane
5. Paste the same coordinates in and press Enter
6. Location is not placed at the same location as the coordinates were pulled from. 

### Expected behavior
1. If you collect a coordinate location from the map, the coordinates you receive should should appear in the same exact place when you paste those coordinates back into the CC pane.

2. We should have a good business explanation for this behavior to put into documentation.

**Comment by csmoore** [comment]
In the UTM/MGRS case, the location you are collecting is only accurate to the nearest meter, so the coordinate you are pasting back in is on a 1 meter boundary not necessarily the exact coordinate collected with the map point tool.
