### ISSUE TITLE
Ambiguous Coordinates dialog does not honor Lat/Lon vs Lon/Lat radio buttons

### ISSUE THREAD

**Issue by dfoll** [Esri/coordinate-conversion-addin-dotnet#550]
### Background
Found while verifying #525 .

### Current Behavior
If you enter `10 78` in the Coordinate Conversion pane it is treated as 10N 78E regardless of what option you select in the Ambiguous Coordinates dialog box

### Expected behavior
If you enter `10 78`  in the Coordinate Conversion pane the Ambiguous Coordinates dialog box opens. If you select the `Lat/Lon` radio button, it is treated as  `10N 78E`, if you select the `Lon/Lat` radio button it is treated as `78N 10E`

### Repro steps
1. In the `Edit Properties` window, set the coordinate format to any "two-part" coordinate format, ie, DMS. Make sure `Display Ambiguous Coordinates Dialog" check box is checked.
2. Enter `0 0` in the Input leave the radio button for `Lat/Lon` marked, Click OK.
3. Enter `10 78` in the Input, press Enter. Leave the radio button for `Lat/Lon` marked. Click OK.
4. Observe where it is placed. should be somewhere in India, as the coordinate is being read as 10N 78E based on your selection in the Ambiguous Coordinates dialog. Also observe the List, and note that 10 00 00.00N 078 00 00.00E was added to the list.
_do not clear that point_
5. Enter `10 78` in the Input, press Enter. Mark the radio button for `Lon/Lat`. Click OK.
Observe that the coordinate is placed in Southern India again. This is incorrect. The mark should be placed west of the Svalbard archipelago. Also observe the List and note that 10 00 00.00N 078 00 00.00E was added to the list, instead of 078 00 00.00N 10 00 00.00W as it should have been because you marked the radio button saying your coordinate was entered `Lon/Lat`

### Notes
- ArcGIS Pro 2.3.0.15723 | Coordinate Conversion ...\Dev\41
- ArcMap 10.3.1 | Coordinate Conversion ...\Dev\41
- also observed on ArcMap 10.3.1 with the Oct release of CC
- also observed on ArcGIS Pro 2.1.0 with the Oct release of CC. _this functionality caused a crash on ArcGIS Pro 2.3 prior to #525  so the Oct release cannot be tested on ArcGIS Pro 2.3_

**Comment by dfoll** [comment]
@lfunkhouser for priority

**Comment by dfoll** [comment]
create checklist tag added to update tests to do this check

**Comment by kgonzago** [comment]
Issue fixed and in this [PR](https://github.com/Esri/coordinate-conversion-addin-dotnet/pull/552)

**Comment by dfoll** [comment]
- ArcGIS Pro 2.3 CC Commercial\Solutions\DefenseSolutions\CoordinateConversion\January2019\Dev\44
   - looks good
- ArcGIS Pro 2.3 MT
   -
- ArcMap 10.3.1 CC Commercial\Solutions\DefenseSolutions\CoordinateConversion\January2019\Dev\44
   - looks good
- ArcMap 10.3.1 MT
   -

**Comment by dfoll** [comment]
@lfunkhouser I am re-opening this issue. @ljuru is doing certification testing on ArcGIS Pro 2.4 and has found that some how this issue has reverted. We confirmed together that in the last release of Military Tools (3.4/build 227) this is working correctly. Somehow between the last release and build 113 of CC this has reverted. Also tagging @kgonzago for awareness because he did the fix the first time. @lfunkhouser  we need to discuss how to proceed on this... do we have @kgonzago fix or ask CT to fix.

**Comment by kgonzago** [comment]
@dfoll @ljuru You are correct this fix was overwritten with this [commit](https://github.com/Esri/coordinate-conversion-addin-dotnet/commit/10c20d25ed6d0b6ee07788d030fe9d835c0ba067#diff-14a5f733c041b82ff256846fb8ecac21). Easy fix enough to add this [logic](https://github.com/Esri/coordinate-conversion-addin-dotnet/blob/574865bace7876687f100b18913e38c004378251/source/CoordinateConversion/ProAppCoordConversionModule/ViewModels/ProTabBaseViewModel.cs#L963) back.

**Comment by dfoll** [comment]
cool! think we just ask CT to fix, since they are in that code right now anyway?

**Comment by kgonzago** [comment]
Agreed. Let's have CT fix it.

**Comment by dfoll** [comment]
@saip while doing some certification testing for 2.4 we noticed that a previous fix has been overwritten. @kgonzago has detailed the problem in [this comment](https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/550#issuecomment-496685551) could we please have that put back in?

**Comment by lfunkhouser** [comment]
@saip is there an update on this issue?

**Comment by saip** [comment]
@lfunkhouser @dfoll We have committed changes to fix this issue. The commit is added to open [PR](https://github.com/Esri/coordinate-conversion-addin-dotnet/pull/612)

**Comment by dfoll** [comment]
Verified fixed on ArcMap and ArcGIS Pro with CC build 127 built from [this branch](https://github.com/Esri/coordinate-conversion-addin-dotnet/tree/CTLocalGovTeam-dev) in #612
