### ISSUE TITLE
Exporting to feature class when using a custom Display Coordinate causes Pro to become unresponsive

### ISSUE THREAD

**Issue by dfoll** [Esri/coordinate-conversion-addin-dotnet#555]
Exporting to feature class when using a custom Display Coordinate (Input and List) causes the app to become unresponsive.

### Repro steps
1. In Coordinate Conversion pane, set the Display Coordinate to DD
2. Use the Map Point Tool to collect a few points from the map
3. Click Export
4. Use the Feature class radio button.
5. Click OK
6. Name fc.
7. FC is added to TOC
8. Change the Display Coordinate to a custom version of one the coordinate formats, for example, format DD to be `Y0.0#####N/\X0.0#####E`
9. Click Export
_either ArcGIS Pro just hangs or CC gets stuck in a state where the Map Point Tool is active but it does not do anything_

#### Notes
- Happens when exporting to FC, SHP, or KMZ does not seem to happen with CSV
- Could not repro in ArcMap
- Note that while the app does become unresponsive, if you go back after restarting Pro, it seems that the FC was created and is readable in a new instance of Pro

MT 189

**Comment by BobBooth** [comment]
I can repro using DD and the /\ chars together as a separator.

**Comment by lfunkhouser** [comment]
Check build from Jan 7 to see if it was introduced with fix from #551

**Comment by BobBooth** [comment]
It seems to write out the feature classes correctly, even when it freezes.
![image](https://user-images.githubusercontent.com/3801392/51552005-b335da00-1e3d-11e9-954a-6be928f0fe98.png)
MGRS with spaces, MGRS with /\ separator, etc...

**Comment by kgonzago** [comment]
Here are the builds I tested with:
1. Build 42 (CTLocalGovTeam-dev branch) from current pre-release
2. Build 20 from December 2018 release
3. Build 28 from August 2018 release
Issue is still there in all three builds. Also, I confirmed @BobBooth's [comment](https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/555#issuecomment-456478715): feature class was still created when Pro was non-responsive.

**Comment by kgonzago** [comment]
We can dig more into this but given the tight time frame, I suggest push this issue to the next release.

**Comment by dfoll** [comment]
Testing with ArcGIS Pro 2.2 CC build 89
The repro steps listed above no longer cause ArcGIS Pro to hang.

**Comment by dfoll** [comment]
### Doc ready for review at:
- ...\Solutions\DefenseSolutions\CoordinateConversion\Testing\CTLocalGovTeam-dev\91
- https://solutionsdev.arcgis.com/defense/help/coordinate-conversion/resources/june-2019-coordinate-conversion.htm
- ...\Solutions\DefenseSolutions\MilitaryToolsForArcGIS\Dev\267
- https://solutionsdev.arcgis.com/defense/help/military-tools/resources/june-2019-military-tools-for-arcgis.htm
