### ISSUE TITLE
Make enter a keyword to search for a symbol optional

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/coordinate-conversion-addin-dotnet#557]
https://solutions.arcgis.com/defense/help/military-tools/workflows/change-the-symbol.htm

Step 3 is not required. I can either enter a keyword to search or scroll and select a symbol.

**Comment by dfoll** [comment]
- [ ] update topic
- [ ] update CC workflows pub with new version
- [ ] republish CC workflows
- [ ] update CC pdf with new version
- [ ] republish CC pdf
- [ ] update MT workflows pub with new version
- [ ] republish MT workflows
- [ ] update MT pdf version
- [ ] republish MT pdf

**Comment by dfoll** [comment]
### Doc QC work: 
- [ ] [Coordinate Conversion Workflows](https://solutionsdev.arcgis.com/defense/help/coordinate-conversion/workflows/coordinate-conversion-introduction.htm)
- [ ] \DefenseSolutions\CoordinateConversion\October2019\Dev\170\
- [ ] [Military Tools Workflows](https://solutionsdev.arcgis.com/defense/help/military-tools/workflows/coordinate-conversion-introduction.htm)
- [ ] \DefenseSolutions\MilitaryToolsforArcGIS\October2019\Dev\343\

**Comment by lfunkhouser** [comment]
Verified on CC and MT dev pages and CC 175 and MT 345
