### ISSUE TITLE
Update wording in doc for Copying coordinates to include copying a selection of multiple coordinates

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/coordinate-conversion-addin-dotnet#561]
This functionality already has been implemented in https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/330.  The doc should be updated to communicate the ability to select multiple coordinates in the list or on the map.

Current:
Select a coordinate in the List section, then right-click the coordinate and select Copy to copy a single coordinate from the List.

Proposed
Select a coordinate or coordinates in the List section or on the map, then right-click the coordinate in the List and select Copy to copy the selected coordinate(s) from the List.

Military Tools build 3.3.0.195
ArcGIS Pro 2.3
ArcMap 10.6.1

**Comment by BobBooth** [comment]
Made changes to copy coordinates topic.

**Comment by BobBooth** [comment]
Updated publications for CC and MT PDFs and Workflows tabs, republished, verified on Dev. Rebuilt CC and MT addins and verified changes appear in PDFs in solution zips.

**Comment by lfunkhouser** [comment]
This doc change is for the MT 3.4 release - changing the MT label. This also affects ArcMap - adding that label. Adding the verified label to close.
