### ISSUE TITLE
Confirm Removal? dialog box does not support Dark Theme

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/coordinate-conversion-addin-dotnet#562]
Right click at Output format in the Output section
Select Delete

Current: Delete confirmation dialog box does not follow dark theme.
Expected: Delete confirmation dialog box supports dark theme.

MT 3.3.0.195
Pro 2.3

**Comment by Dbarnes1** [comment]
This was also mentioned at the holistic testing for Pro for Intel on 8/9

**Comment by dfoll** [comment]
Verified
![image](https://user-images.githubusercontent.com/5322669/63355293-e983fb00-c333-11e9-9c73-2cacc12ca0d2.png)

**Comment by dfoll** [comment]
G-Doc label can be removed after publishing

**Comment by dfoll** [comment]
### Doc review:
- [ ] [Coordinate Conversion October Resources](https://solutionsdev.arcgis.com/defense/help/coordinate-conversion/resources/october-2019-coordinate-conversion.htm)
- [ ]  [Military Tools October Resources](https://solutionsdev.arcgis.com/defense/help/military-tools/resources/october-2019-military-tools-for-arcgis.htm)
- [ ] \DefenseSolutions\CoordinateConversion\October2019\Dev\167\
- [ ] \DefenseSolutions\MilitaryToolsforArcGIS\October2019\Dev\332\

**Comment by lfunkhouser** [comment]
Doc verified
