### ISSUE TITLE
Export coordinates does not follow doc style of other topics - remove steps that do not apply to Export

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/coordinate-conversion-addin-dotnet#563]
Step 1 and 2: Covered in "Convert a coordinate" topic
Step 3: Covered in "Change the displayed input coordinate format" topic

MT 3.3.0.195
Pro 2.3
ArcMap 10.6.1

**Comment by BobBooth** [comment]
Updated in CMS, republished to dev and changes are present.

**Comment by BobBooth** [comment]
Rebuilt CC and MT solutions, PDFs with updated text are present.
