### ISSUE TITLE
Copy coordinates from List using shortcut Ctrl+C

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/coordinate-conversion-addin-dotnet#564]
Current behavior
Select coordinates in the list can be done by clicking on a single coordinate or selecting multiples using Ctrl or Shift key when you click, or Ctrl+A to select all depending on which entries you want to select. 

User can right-click on the selected coordinates in the List > Select Copy to copy the selected coordinates

User can paste the coordinates into another application by right-click > Paste or using the shortcut Ctrl+V to paste

Expected behavior
In addition to the right-click, allow user the option to use Ctrl+C to copy the selected coordinates from the List

MT 3.3.0.195
ArcGIS Pro 2.3
ArcMap 10.6.1

**Comment by BobBooth** [comment]
I'm seeing an issue where if you select multiple coordinates in the list, then right-click on **one of the selected coordinates**, click Copy, then paste into a text document, you only get the single coordinate that you actually clicked.  
If you make a multiple selection and use Ctrl+C to copy, you get the multiple selection.
![image](https://user-images.githubusercontent.com/3801392/54232678-9898ec80-44e1-11e9-926a-91707f2ab82b.png)
Windows standard behavior would be to get the other selected items if one item of the selected group is right-click/copied. For example, I have files A, B, C, D.  I multiple-select B and D, then right-click file D and click Copy.
In a new location, I paste.  Both file B and D are copied to the new location.
![image](https://user-images.githubusercontent.com/3801392/54233047-7e134300-44e2-11e9-8ef7-a12001511c37.png)
Currently it is treating the case of I have B and D selected, and I right-click A and click Copy. In that case, only A should be copied.

Multiple select, right-click, copy/paste retains all of the selected features in the released version of CC, so this is a new issue with the test build I'm using: CTLocalGovTeam-dev\57

**Comment by dfoll** [comment]
@BobBooth  @sap and i were able to reproduce this. The problem with this one is that this behavior was specifically introduced to deal with #569 in which if you had a point highlighted and right-clicked on a different (not highlighted point) it would always return the details for the point that was highlighted. We will need to log this as a future enhancement to figure out how to work around this.

**Comment by dfoll** [comment]
@BobBooth and I discussed [this comment](https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/564#issuecomment-472503258) for this release we want to leave things as implemented ... when multiple points are selected and you right-click>copy you only get the point you right-clicked on. You can still copy multiple points by selecting multiple points and using ctrl+c. An issue should be logged to address this in the future.

**Comment by BobBooth** [comment]
Doc changes visible in What's new, CC, and MT Release page on STG.
