### ISSUE TITLE
Paste coordinates into the List using keyboard shortcut Ctrl+V 

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/coordinate-conversion-addin-dotnet#565]
Current 
Copy coordinate from source
Right-click in List section and click Paste

Expected 
Add ability to use keyboard shortcut Ctrl+V to paste into the List

MT 3.3.0.195
Pro 2.3
ArcMap 10.6.1

**Comment by dfoll** [comment]
Part of the documentation for this will be including the known issue that ctrl+v does not work in ArcMap if the list is empty

**Comment by BobBooth** [comment]
In ArcMap, I'm seeing an issue where if I paste two MGRS coordinates into the list:
15SUB2902590916
20FLJ4322722249
Using Default Input coordinate format, the List shows one coordinate in DD and one in Web Mercator.
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/0b7ac2b6-fac0-4b1d-85bc-40826aaa259a)

**Comment by dfoll** [comment]
with build 58 I am seeing the issue in [this comment](https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/565#issuecomment-471724520) resolved

**Comment by dfoll** [comment]
@BobBooth @saip were able to reproduce [this](https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/565#issuecomment-472202276) today with build58 and confirmed it is not happening in the released version of MT, so this is something i think we will need fixed in this delivery

**Comment by dfoll** [comment]
Build 61 which pulls in [this commit](https://github.com/Esri/coordinate-conversion-addin-dotnet/pull/580/commits/9e94936c9549264af8eb714114af0f48df60e639) fixed @BobBooth  [comment](https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/565#issuecomment-472202276).

**Comment by BobBooth** [comment]
Doc changes visible in What's new, CC, and MT Release page on STG.
