### ISSUE TITLE
Support .xls and .xlsx as import types for Coordinate Conversion

### ISSUE THREAD

**Issue by dfoll** [Esri/coordinate-conversion-addin-dotnet#567]
### Current behavior
Coordinate conversion works correctly for importing a .csv.

### Expected behavior
Requesting to add .xls and .xlsx to the list of file types that can be imported into Coordinate Conversion.

 
- ArcGIS Pro 2.1-2.3
- Arc Map 10.3.1 -10.6.1

**Comment by dfoll** [comment]
@lfunkhouser depending on when this gets pulled in to work on, we will need to update the supported versions in the original issue.

**Comment by dfoll** [comment]
@saip While testing this, I discovered that when more points are added to the List (either by importing or clicking one at a time) than there is space for, the Coordinate Conversion window becomes too big and needs to have a scroll bar added. This is not the way the behavior should be, in the last release of Military Tools, the List got a scroll bar when there were too many points in the List to display them all, not the pane.

In the screenshot below, you can see the resulting behavior. 
Repro steps:
1. Add the TableToPoint.csv using the `Import` button.
2. Note that when the List is filled up, the List continues to grow in size and a scroll bar is placed on the pane. In the released version the pane stays the same size and the scroll bar is added to the List.
![image](https://user-images.githubusercontent.com/5322669/54165857-e7d71280-4438-11e9-9768-5324f3e4c59b.png)
(left to right: ArcMap released, ArcMap -CCbuild57, ArcGIS Pro CCbuild57)

- this happens when importing a file, or clicking enough points to fill the List
- did not observe this in ArcGIS Pro with the same build (57) that I saw it in ArcMap with
- does not happen with the released version of MT
- this is similar (but I do not know if something was reverted, or similar behavior is being seen again) to #345

**Comment by dfoll** [comment]
@saip while testing this issue, I noticed some very odd behavior in ArcGIS Pro only. When I import a .csv if it is a particularly large file that takes a few seconds to import and I am moving my mouse around inside the map display window, points will (seemingly) randomly be placed where my map cursor is at. 

Repro steps
1. In ArcGIS Pro (so far have not observed in ArcMap) import TabletoPoint.csv
2. While the import is taking place, move your cursor around repeatedly over Eastern Europe (location doesn't matter)
3. Note that at a seemingly random interval, points are being placed and added to the List, while the import of the .csv is happening and simultaneously

I don't think a screenshot of this really helps, but I am available to repro over a screenshare if the steps are not clear, or if you cannot repro.

[TabletoPoint.zip](https://github.com/Esri/coordinate-conversion-addin-dotnet/files/2954704/TabletoPoint.zip)
 adding points to the List.

**Comment by saip** [comment]
@dfoll We are working on these issues and will be ready with a fix soon

**Comment by BobBooth** [comment]
If my XMSX workbook has multiple sheets in it, importing to ArcMap files with "Something went wrong" message.
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/d28d02c7-ffb1-46c0-8c6c-860384496e7c)
Importing the same sheet in Pro seems to work, but I get prompted "Please enter a valid coordinate" with an OK that I have to click a number of times to proceed.
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/fb54d849-d87a-41b2-bb15-2d2de492041f)
For XLSX format, maybe better to request the user to browse to a specific sheet.

**Comment by saip** [comment]
@dfoll Our team could reproduce both the issues with a build from master branch. We have fixed and committed the updates to existing pull request.

**Comment by dfoll** [comment]
@BobBooth @saip and I are looking at this together right now. We could not consistently reproduce the problem you were seeing with either ArcMap or ArcGIS Pro. What we did notice is that when importing an .xlsx with multiple sheets it will only take the first sheet in the workbook. If we want to have the ability to look through multiple sheets within a workbook we will need to create an enhancement for that.

**Comment by dfoll** [comment]
Issue #588 was created for a future enhancement based on @BobBooth suggestion.
