### ISSUE TITLE
When importing files to Coordinate Conversion, persist fields from input

### ISSUE THREAD

**Issue by dfoll** [Esri/coordinate-conversion-addin-dotnet#568]
### Background
This is useful because all fields used from the input are lost once they are imported to CC. Not a big deal for fields that contain simple coordinate formats, as those can be added back in upon export by the CC pane, however those fields that are lost may contain non-coordinate attribute information, or highly customized coordinate notation.

### Current behavior
Coordinate conversion imports from select file types. Only the coordinate fields are used by the CC pane. All other fields whether they are other coordinates or attribute data are lost. 

### Expected behavior
Coordinate Conversion holds all fields associated with a row/entry in memory while that point is in the Coordinate Conversion list.

[design doc tbd]

- ArcGIS Pro 2.1-2.3
- Arc Map 10.3.1 -10.6.1
[CC import fields design.pptx](https://github.com/Esri/coordinate-conversion-addin-dotnet/files/2828761/CC.import.fields.design.pptx)

**Comment by dfoll** [comment]
@saip  has asked when importing values from fields, what should be done about field type. because my understanding is that there is not a reliable one to one connection between excel data types and arcgis data types,  i have given the answer that converting everything to strings will be ok for our first release/mvp

**Comment by BobBooth** [comment]
Can we mimic the behavior of (or reuse code from) the "Table to Table" GP tool?
Seems as though Excel tables usually have a header row with text, so we could also look at the values further down the table to infer data type.
The Incident Analysis sample data is in XLS format, and if you use Table to Table to import it to a GDB table (with default settings, no field mapping), it matches numeric fields to Double, Text to Text, and Dates to Date.
[IncidentsCopy.zip](https://github.com/Esri/coordinate-conversion-addin-dotnet/files/2906373/IncidentsCopy.zip)
 
[MyProject85.gdb.zip](https://github.com/Esri/coordinate-conversion-addin-dotnet/files/2906378/MyProject85.gdb.zip)

**Comment by dfoll** [comment]
Tested this in ArcMap and ArcGIS Pro. Good to merge PR. Should be added as What's New

**Comment by dfoll** [comment]
@saip i just noticed that importing a list with fields works properly. If you manually add to the list using the map point tool (so one point would have no details) and then export the list, none of the imported fields persist to the exported file

**Comment by BobBooth** [comment]
Doc changes visible in What's new, CC, and MT Release page on STG.
