### ISSUE TITLE
Right-click to view values associated with points in the list

### ISSUE THREAD

**Issue by dfoll** [Esri/coordinate-conversion-addin-dotnet#569]
This will be dependent on #568 being implemented first

**Comment by dfoll** [comment]
The current behavior of this displays a table with the "Additional Fields" title of the table and displays the coordinate from the List as the "OutputCoordinate". @saip what would the level of effort/time needed be, to have the coordinate value that was clicked on display as the title of the table instead of the "Additional Fields" text?

**Comment by BobBooth** [comment]
I like the View Details context menu and info window. I think it would be improved if you did not have to close it to see the details of another location. The workflow is needlessly slow.
I suggest if View Details result window is open, you should be able to right-click on another coordinate in the list and view details for that - the details would then update in the View Details window.

**Comment by dfoll** [comment]
@BobBooth agree with your logic. I had the same thought and looked around Pro to see if this was standard behavior. I wanted to spend some time today talking through the entire list. Let's discuss it then

**Comment by dfoll** [comment]
I have asked @saip  for a slight change on this one. @lfunkhouser please let me know what we need to do with dealing with CT, if this is considered an increase in scope, but @saip says it is a quick fix that should be able to be included in this delivery

**Comment by dfoll** [comment]
@BobBooth @lfunkhouser I have spoken with @saip about [this comment](https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/569#issuecomment-472198303) to make this behave the same way as the identify tool would be a considerable amount of work, this should be a future enhancement

**Comment by dfoll** [comment]
Testing with \DefenseSolutions\CoordinateConversion\March2019\Dev\43 this behaves as expected.

**Comment by BobBooth** [comment]
Doc changes visible in What's new, CC, and MT Release page on STG.
