### ISSUE TITLE
Export includes non-coordinate fields that are associated with the List

### ISSUE THREAD

**Issue by dfoll** [Esri/coordinate-conversion-addin-dotnet#570]
This is dependent onf #568 being completed first

**Comment by lfunkhouser** [comment]
After this issue is updated with requirements, #338 will be closed.

**Comment by dfoll** [comment]
we should verify if this is still required. I believe this functionality was covered in the March update.

**Comment by dfoll** [comment]
confirmed this functionality is already there, no development needed
![image](https://user-images.githubusercontent.com/5322669/59696069-4a1e7c80-91b9-11e9-99d5-220dfe6b87a2.png)

**Comment by dfoll** [comment]
Doc Updates:
 - https://solutionsdev.arcgis.com/defense/help/coordinate-conversion/workflows/importing-coordinates.htm
- https://solutionsdev.arcgis.com/defense/help/coordinate-conversion/workflows/export-coordinates.htm
- \\...\DefenseSolutions\CoordinateConversion\Dev\138\
- https://solutionsdev.arcgis.com/defense/help/military-tools/workflows/importing-coordinates.htm
- https://solutionsdev.arcgis.com/defense/help/military-tools/workflows/export-coordinates.htm
-

**Comment by dfoll** [comment]
- added to CC june release page
- added to MT june release page
- added to what's new in [this pr](https://github.com/ArcGIS/arcgis-solutions-website/pull/7897)

**Comment by dfoll** [comment]
- https://solutionsdev.arcgis.com/defense/help/military-tools/resources/june-2019-military-tools-for-arcgis.htm
- \\...\DefenseSolutions\MilitaryToolsforArcGIS\Dev\309\
- https://solutionsdev.arcgis.com/defense/help/coordinate-conversion/resources/june-2019-coordinate-conversion.htm
- \\...\DefenseSolutions\CoordinateConversion\Dev\140\
- [What's new](https://solutionsdev.arcgis.com/defense/what-is-new/)  (will require the 1200 pdt build to happen first)

**Comment by lfunkhouser** [comment]
workflow topics verified
MT release notes verified on dev build 310 and solutionsdev
CC release notes verified on dev build 140 and solutionsdev
