### ISSUE TITLE
Buttons do not support dark theme

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/coordinate-conversion-addin-dotnet#573]
Buttons on the Coordinate Conversion pane do not follow Dark theme schema used by ArcGIS Pro.

Input section of the add-in:
- [x] Select Point
- [x] Edit Properties
- [x] Map Point Tool

MT 3.3.1 February 2018 release
Tested in Pro 2.2 and 2.3
********************************************************************************
![image](https://user-images.githubusercontent.com/5322669/53098106-edec6a00-34f0-11e9-8245-547caeaf1120.png)

**Comment by dfoll** [comment]
This was tested on ArcGIS Pro. Good to merge

**Comment by dfoll** [comment]
Testing from \DefenseSolutions\CoordinateConversion\March2019\Dev\43 looks correct.
