### ISSUE TITLE
Clear All, Import, and Export buttons should have a hover action

### ISSUE THREAD

**Issue by dfoll** [Esri/coordinate-conversion-addin-dotnet#578]
### Current behavior
The `Clear All` `Import` and `Export` buttons on the Coordinate Conversion pane do not have a hover action to indicate to the user that those buttons will do something when clicked. They do have tooltips that appear. 

### Expected behavior
Requesting that they also have a hover action that occurs to help the user understand that the button does something when clicked. These buttons should behave the way the `Add Favorite` button behaves on the Military Symbol Editor pane.

![image](https://user-images.githubusercontent.com/5322669/53257461-36925780-3698-11e9-9ee5-3d6e3e58697f.png)

Screenshot is of Dark theme, but the same example/expected behavior should apply to Light theme

**Comment by dfoll** [comment]
Tested from feature branch for ArcMap and Pro, this one is good to merge. @lfunkhouser I do not think this is one we need to add for What's new

**Comment by BobBooth** [comment]
@dfoll - tested on Pro 2.3 from feature branch, Dark theme and Light theme. Looks good.

**Comment by dfoll** [comment]
@lfunkhouser and I agree this does not need to be in whats new

**Comment by dfoll** [comment]
Testing from \DefenseSolutions\CoordinateConversion\March2019\Dev\43
