### ISSUE TITLE
Right-click in list does not select the coordinate clicked

### ISSUE THREAD

**Issue by dfoll** [Esri/coordinate-conversion-addin-dotnet#581]
### Background
This behavior gives the user a false sense of what coordinate they are interacting with.

### Current behavior
When right-clicking a coordinate in the List, the action is performed on the existing selection [of the List] instead of the coordinate that was right-clicked on.

### Repro steps
1. Add some points to the CC List
2. Select a coordinate in the List
3. Right-click and `Copy` that coordinate
4. Paste it into some text editor (just to have a record of which one you clicked)
5. Right-click a different coordinate and `Copy` that coordinate
6. Paste it into some text editor
**_Note that the coordinate you "copied" the second time is the same as the first one, because it is honoring those behaviors on the selection from the list, not the one you actually right-clicked on_**

### Expected behavior
Right-clicking a coordinate in the List should make that the active selection [of the List] and perform the action from the context menu on that coordinate.

**Comment by dfoll** [comment]
This is expected to be fixed in this [delivery](https://github.com/Esri/coordinate-conversion-addin-dotnet/pull/580), this was an issue that @lfunkhouser identified while getting a preview demo of the delivery from @saip. @saip said he would fix this immediately as part of the delivery. Entering this issue for record keeping.

**Comment by BobBooth** [comment]
There are two cases to consider.
A) Multiple coordinates are selected and you right-click a coordinate that is not a member of the -selected set to copy/paste. -- in this case, you should get the one coordinate that you right-clicked.
B) Multiple coordinates are selected and you right-click a member of the selected set.-- in this case, you should get all of the selected coordinates.
See comment: https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/564#issuecomment-472165576

**Comment by dfoll** [comment]
This came up during development and was handled in #580 does not need to be listed in doc because it was an "in development" problem
