### ISSUE TITLE
Coordinate Conversion does not retain list order when copying multiple coordinates from list

### ISSUE THREAD

**Issue by BobBooth** [Esri/coordinate-conversion-addin-dotnet#582]
With Coordinate Conversion, add ten points to the map.
They are added to the List.
In the list, start near the bottom and work your way up using Ctrl-Click to select several coordinates. 
Press Ctrl-C to copy the selection.
Paste the list into a text document.
The order of coordinates in the text document is inverted with respect to the order in the list.
Select the same coordinates in the list, this time starting high on the list and working down.
Paste the list into a text document.
The order of the coordinates will match the order in the list.
I suggest that when you copy a group of coordinates out of the list, they should be pasted to match the top-down sort order of the list.
I found this confusing when I was attempting to verify that the same values I had copied were the ones showing up in the notepad file.
![image](https://user-images.githubusercontent.com/3801392/54235328-5ffc1180-44e7-11e9-8c34-a05ae1d341ae.png)

The January 2019 released version behaves this way.

**Comment by dfoll** [comment]
Agreed with @BobBooth thoughts that the way this currently works can be confusing to the user. The List is populated in chronological order (oldest at the bottom) but when points are copied out of the list and then pasted, they are pasted in reverse chronological (oldest at the top). With @lfunkhouser approval, the team has decided that the way we want to improve this situation is to have the List populated in reverse chronological order (oldest at the top). This should mean that a group copied/pasted from the List should match the same over they appeared in the List. #601 was opened to make the changes to the List order, this can be closed and this issue does not need to be worked on.

**Comment by dfoll** [comment]
Re-opening because our previous understanding of how this works was incorrect... the "copy" order is based on the order in which the selection of points was made not the order in which they were added to the list.

**Comment by dfoll** [comment]
I think we can close this. #601 has been implemented. Now, if a user has points in the List and does Copy All, the resulting pasted list will appear in the same order as the List. If the user has points in the List and selects individual points the resulting pasted list will retain the order they were selected by the user.

**Comment by lfunkhouser** [comment]
Closing. #601 was opened to address.
