### ISSUE TITLE
View Details window can page through a list of selected points

### ISSUE THREAD

**Issue by dfoll** [Esri/coordinate-conversion-addin-dotnet#585]
When you have multiple points selected in the List and right-click>View details you should be able to "page" through the details for the points selected in the same manner as if multiple points were selected with the identify tool.

**Comment by dfoll** [comment]
spoke with @saip we can build this for Pro with a window like the one below, the buttons in the lower right that apply to features will be disabled. in arcmap we will need to build this window completely from scratch.
![image](https://user-images.githubusercontent.com/5322669/56145628-a45d5000-5f72-11e9-9a77-2d21854d06dc.png)

**Comment by dfoll** [comment]
@lfunkhouser I would like to proceed with this as described in [this coment](https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/585#issuecomment-483304116) and just not have this functionality in ArcMap. What are you  thoughts?

**Comment by lfunkhouser** [comment]
Agreed. Due to the limitation in ArcMap, this will only be implemented for ArcGIS Pro.

**Comment by csmoore** [comment]
Verified:

Pro: (**IMPORTANT NOTE**: On 2.4 requires build 2.4.19921 or later)

![image](https://user-images.githubusercontent.com/3090809/59133686-c8bc2400-8946-11e9-986d-cd64bf7d1ac9.png)

ArcMap:

![image](https://user-images.githubusercontent.com/3090809/59133813-29e3f780-8947-11e9-98ff-bd407aedbe4d.png)

**Comment by dfoll** [comment]
- added to what's new in [PR 7895](https://github.com/ArcGIS/arcgis-solutions-website/pull/7895)

**Comment by dfoll** [comment]
- https://solutionsdev.arcgis.com/defense/help/coordinate-conversion/resources/june-2019-coordinate-conversion.htm
- \\...\DefenseSolutions\CoordinateConversion\Dev\141\
- https://solutionsdev.arcgis.com/defense/help/military-tools/resources/june-2019-military-tools-for-arcgis.htm
- \\...\DefenseSolutions\MilitaryToolsforArcGIS\Dev\311
- https://solutionsdev.arcgis.com/defense/what-is-new/

**Comment by lfunkhouser** [comment]
Doc verified on solutionsstg, CC 143 and MT 314
