### ISSUE TITLE
After right-click > View details, you must close the details window before interacting with the CC pane

### ISSUE THREAD

**Issue by dfoll** [Esri/coordinate-conversion-addin-dotnet#586]
### Current behavior
The right-click > View Details window stays open and prevents you from interacting with the app until you close the window.

### Expected behavior
When the View details window is open, that window should just lose focus is you try to interact with the app in some other way. This includes if you want to view details for a different point, you should be able to right-click a different point in the list and have the details window switch to display the details for that point.

**Comment by dfoll** [comment]
After build 89 the View Details window behaves as an app pane in ArcGIS Pro. While it is open you can interact with other areas of ArcGIS Pro.  As well as right-clicking to select a different point from the list.

**Comment by dfoll** [comment]
@saip can you take a look at this? It seems as though the ability to select points from the map was broken when this was implemented.

**Comment by saip** [comment]
@dfoll @csmoore We have updated the details window content to look similar to pro popup content

![smallimg](https://user-images.githubusercontent.com/2205106/58005807-1ee63600-7b04-11e9-87b6-06d839ecb9a1.png)

**Comment by csmoore** [comment]
Verified original and window sizing issues. 

@dfoll - I wasn't 100% sure about the issue reported: "ability to select points from the map" - I could select items in the Output List and see them green-highlighted on the map if that is what was not working previously.

**Comment by csmoore** [comment]
@dfoll @saip - I do now see the issue where I can't use to "Select Point" tool to select more than one point (can't select multiple points). I did confirm that this used to work in the last released version.

![image](https://user-images.githubusercontent.com/3090809/58186503-05b7c380-7c83-11e9-9486-f11132de3a51.png)

**Comment by dfoll** [comment]
removed G-Development label, because remaining concerns will be addressed through issue #608

**Comment by dfoll** [comment]
### Doc updates:
- ...\Solutions\DefenseSolutions\CoordinateConversion\Testing\csm-build-brokey-broke-on-10-4-1\104
- _MT build is currently broken, so no pdf there_
- https://solutionsdev.arcgis.com/defense/help/military-tools/resources/june-2019-military-tools-for-arcgis.htm
- https://solutionsdev.arcgis.com/defense/help/coordinate-conversion/resources/june-2019-coordinate-conversion.htm

**Comment by lfunkhouser** [comment]
doc updates verified.

@dfoll FYI Buttons on bottom of ArcGIS Pro pop-up are not active. 

![image](https://user-images.githubusercontent.com/3800729/58675515-815fe300-8309-11e9-833c-3d2c048da699.png)

MT 3.4.1.275 
Pro 2.4  (19822)

**Comment by dfoll** [comment]
@lfunkhouser yes, we that is because those buttons act on features. the information contained in the windows is for features

**Comment by lfunkhouser** [comment]
I figured that, but it looks confusing on the UI to have buttons that don't work when a user interacts with the Coordinate Conversion add-in UI.

**Comment by dfoll** [comment]
I can ask @saip  if it's possible to remove them

**Comment by csmoore** [comment]
@dfoll I looked into the issue of the disabled Pop-up Buttons on bottom of Pro Pop-up form:

![image](https://user-images.githubusercontent.com/3800729/58675515-815fe300-8309-11e9-833c-3d2c048da699.png)

These are disabled because there is not an active feature (these are CIMSymbols in a Graphic Overlay) - using this form without active features is somewhat of an outlier case. 

There does not seem to be a way to remove these default buttons (just disable them) - but you can add to these buttons.
