### ISSUE TITLE
If there are points in the List that have fields different than other points in the List, only the fields from the top point are exported to FC/SHP/KMZ

### ISSUE THREAD

**Issue by dfoll** [Esri/coordinate-conversion-addin-dotnet#587]
### Background
Coordinate conversion allows a user to import a .csv or .xlsx and retains the fields from the input file in memory. Another file with different fields can then be imported to the List.

### Current behavior
When exporting from the List the fields exported from in-memory are only the fields associated with the top/most recently added point in the List.

### Expected behavior
All fields that are held in-memory in the List should be included in the export

### Notes/workaround
1. import a .csv that has fields "A" and "B"
2. import a .csv that has field "C" and "D"
_start workaround_
3. export to [filename].csv (.csv will have fields "A", "B", "C", and "D")
4. clear List
5, import [filename].csv (making sure to select fields "A", "B", "C", and "D")
6. export to fc/shp/kml
**output has fields "A", "B", "C", and "D"**

**Comment by dfoll** [comment]
Removing `CyberTech` label because a fix was put in, in the last release to offer this functionality. Suggesting a deep review on functionality before this issue is closed.

**Comment by dfoll** [comment]
Verified

**Comment by dfoll** [comment]
G-Doc label can be removed after publishing

**Comment by dfoll** [comment]
### Doc review:
- [ ] [Coordinate Conversion October Resources](https://solutionsdev.arcgis.com/defense/help/coordinate-conversion/resources/october-2019-coordinate-conversion.htm)
- [ ]  [Military Tools October Resources](https://solutionsdev.arcgis.com/defense/help/military-tools/resources/october-2019-military-tools-for-arcgis.htm)
- [ ] \DefenseSolutions\CoordinateConversion\October2019\Dev\167\
- [ ] \DefenseSolutions\MilitaryToolsforArcGIS\October2019\Dev\332\

**Comment by lfunkhouser** [comment]
Doc verified
