### ISSUE TITLE
Import functionality should look through an Excel workbook to allow the user to select which worksheet to import

### ISSUE THREAD

**Issue by dfoll** [Esri/coordinate-conversion-addin-dotnet#588]
### Current behavior
Using the add-in to import an Excel file only allows the user to select a workbook. By default the first worksheet in the workbook is the one used for import.

### Expected behavior
The add-in should allow the user to select which worksheet they want to import from a workbook. ArcGIS natively allows the user to search through a workbook when adding data, however the add-in only allows the user to select a workbook.

**Comment by dfoll** [comment]
`Excel to table` does not allow user to easily select a sheet? - look into this

**Comment by dfoll** [comment]
For this release we will match the functionality of the gp tool that is used. We will allow the user to explicitly specify a worksheet. The ability to select a worksheet by browsing is something we will evaluate in the future.

**Comment by dfoll** [comment]
- [x] version topic
- [x] update topic
- [ ] update CC workflows pub with new version
- [ ] republish CC workflows
- [ ] update CC pdf with new version
- [ ] republish CC pdf
- [ ] rebuild CC
- [ ] update MT workflows pub with new version
- [ ] republish MT workflows
- [ ] update MT pdf version
- [ ] republish MT pdf
- [ ] rebuild MT

**Comment by dfoll** [comment]
Leaving this open temporarily while we get confirmation about the level of effort for allowing a user to browse to a specific worksheet.
- ideal scenario is that when a user browses to a workbook the first sheet is used by default
or
- the user can go one step further to select a sheet.

I had discussions with @saip about this in the past, but the reason we cannot do this is currently escaping me, leaving open until we get clarification.

@csmoore for awareness or any possible input

**Comment by dfoll** [comment]
### Doc QC work: 
- [ ] [Coordinate Conversion Workflows](https://solutionsdev.arcgis.com/defense/help/coordinate-conversion/workflows/coordinate-conversion-introduction.htm)
- [ ] \DefenseSolutions\CoordinateConversion\October2019\Dev\170\
- [ ] [Military Tools Workflows](https://solutionsdev.arcgis.com/defense/help/military-tools/workflows/coordinate-conversion-introduction.htm)
- [ ] \DefenseSolutions\MilitaryToolsforArcGIS\October2019\Dev\343\

**Comment by lfunkhouser** [comment]
Verified note added to Import coordinates topic: When importing a .xls/.xlsx file the first sheet in the workbook is used as input.

Verified on Dev site for CC and MT and PDFs CC 175 and MT 345

**Comment by dfoll** [comment]
"As designed" the functionality is not designed to be able to use a sheet from a workbook other than the first sheet. If a user brings to us a need to use a sheet that is not the first sheet in a workbook and the work around of editing the workbook to make it the first sheet is not an option, we will open a new issue for that functionality at that time
