### ISSUE TITLE
Recent CC changes broke Visibility Addin build

### ISSUE THREAD

**Issue by csmoore** [Esri/coordinate-conversion-addin-dotnet#589]
Changes in PR #580 broke the visibility build which had dependencies on 

CoordinateConversionLibrary.Helpers.ImportCSV.Import method at: 

https://github.com/Esri/visibility-addin-dotnet/blob/dev/source/addins/ArcMapAddinVisibility/ViewModels/LOSBaseViewModel.cs#L373

Changed method in CC:

https://github.com/Esri/coordinate-conversion-addin-dotnet/pull/580/files#diff-b7593880fa549405c2e04c3ae68e8346L75 

Should see if the parameters that were added to the method can be made optional and/or nullable (note: nulling these now will cause the code to crash, so that should be fixed also).

**Comment by csmoore** [comment]
@dfoll @kgonzago @lfunkhouser @BobBooth  - FYI - this issue will need resolved before the MT and Viz builds will work again.

**Comment by dfoll** [comment]
@saip
