### ISSUE TITLE
Columns in the View Details window in ArcGIS Pro should use 100% of the space in the window

### ISSUE THREAD

**Issue by dfoll** [Esri/coordinate-conversion-addin-dotnet#591]
### Background
In ArcGIS Pro in the View Details window when more space is needed to display the entire coordinate (in the title) than is needed to display all of the field information, then an extraneous border is visible on the window, because a window large enough to display the entire coordinate is created, but the table/grid created to display the values is only as large as is needed to display the values.

### Current behavior
Extraneous border is visible on the window in ArcGIS Pro because the window needs more space to pad and display the full title
![image](https://user-images.githubusercontent.com/5322669/54538525-cad79d80-496a-11e9-8112-db482cc42f23.png)

### Expected behavior
Initial display of the window is based on the space needed to display both the title and all detail information.  After resizing the window or fields, detail information continues to take up 100% of the area of the window.  Window should resize as outlined in #590 
![image](https://user-images.githubusercontent.com/5322669/54538664-01adb380-496b-11e9-90c9-59d3f3fe59b6.png)

**Comment by dfoll** [comment]
Issues #590,#591, #592 are all very closely related, but have their own specific differences that make them unique. They very likely will be handled all in the same effort, but all require their own very specific fixes.

**Comment by csmoore** [comment]
Testing from latest branch build at: `Development\Commercial\Solutions\DefenseSolutions\CoordinateConversion\Testing\CTLocalGovTeam-dev\91\`

**Comment by csmoore** [comment]
This was switched to use the Pro "Pop Up" form so is resizable now and looks like this:

CC: Show Details
![image](https://user-images.githubusercontent.com/3090809/57805336-b1fd2580-772a-11e9-9d0f-46a2ea4cfc1c.png)

I was puzzled by the title "Pop Up" and dark-mode problems - but @dfoll explained that it was requested to just use the Pro "Pop Up" form so any issues with the form name or dark mode exist there and not in the CC addin:

Pro Feature Pop Up:
![image](https://user-images.githubusercontent.com/3090809/57805503-0dc7ae80-772b-11e9-8711-de42720c8b1d.png)

I guess the only enhancement/difference might be to just call this menu item "Pop up" (versus View Details) like Pro does:

![image](https://user-images.githubusercontent.com/3090809/57805717-7747bd00-772b-11e9-9fe6-b1da34d411af.png)

**Comment by dfoll** [comment]
logged @csmoore issue about "View Details" vs "Pop-up" in #614

**Comment by dfoll** [comment]
- https://solutionsdev.arcgis.com/defense/help/coordinate-conversion/resources/june-2019-coordinate-conversion.htm
- https://solutionsdev.arcgis.com/defense/help/military-tools/resources/june-2019-military-tools-for-arcgis.htm
- \\...\DefenseSolutions\CoordinateConversion\Testing\CTLocalGovTeam-dev\131\
- \\...\DefenseSolutions\MilitaryToolsforArcGIS\Dev\293\

**Comment by lfunkhouser** [comment]
Verified doc updates on website and tested CTLocalGovTeam-dev\132 and MilitarytoolsforArcGIS\Dev\305
