### ISSUE TITLE
View Details information is cut off in the title in ArcMap

### ISSUE THREAD

**Issue by dfoll** [Esri/coordinate-conversion-addin-dotnet#592]
### Background
The View Details window appears to display in ArcMap at a size that is needed to display all field information.
### Current behavior
If the window size needed to display all field information does not create a window large enough for the title to display, the title is cut off.

![image](https://user-images.githubusercontent.com/5322669/54539005-b8119880-496b-11e9-89d6-33646c372a29.png)
_When the amount of space needed to display all field information creates a large window, the title displays properly._

![image](https://user-images.githubusercontent.com/5322669/54539062-d5466700-496b-11e9-99c1-19bf993ac38d.png)
_When there are fields that contain smaller amounts of information, then the window needed is smaller, and the title is cut off_

### #Expected behavior
The window created to view details should always be large enough to display all field information and the title. Additionally, the fields and field information should always use up 100% of the window space (when a large window  is created because of the title, see #591 ), and the window should resizable using standard resizing behavior (#590).

![image](https://user-images.githubusercontent.com/5322669/54539461-8ea53c80-496c-11e9-8932-04c6ec7ebf8f.png)
_this is the way the example from current behavior should have displayed_

**Comment by dfoll** [comment]
Issues #590,#591, #592 are all very closely related, but have their own specific differences that make them unique. They very likely will be handled all in the same effort, but all require their own very specific fixes.

**Comment by dfoll** [comment]
@saip knows of a quick work around for this. there is a question of if we want to redesign this window completely from scratch, which will take much longer or if we want to do a work around to fix just this issue.

**Comment by dfoll** [comment]
@saip  we will need to revisit the fixes for this issue. When the View details window opens up, it opens very large with a third blank column in the window.

![image](https://user-images.githubusercontent.com/5322669/57706810-72541200-7634-11e9-9af5-c32b75f3349c.png)
_window opens very large by default_
![image](https://user-images.githubusercontent.com/5322669/57706846-81d35b00-7634-11e9-81ce-5b354aaccbb7.png)
_even after the window is resized, there is an extra, empty third column in the table_

**Comment by csmoore** [comment]
Verified that small and longer titles look correct now:

Long field length:
![image](https://user-images.githubusercontent.com/3090809/58108762-6a5b1b80-7bba-11e9-9705-a8bec6340228.png)

Short field length:
![image](https://user-images.githubusercontent.com/3090809/58108804-79da6480-7bba-11e9-8793-002c9fdb0480.png)

**Comment by dfoll** [comment]
DOC UPDATES:
- https://solutionsdev.arcgis.com/defense/help/military-tools/resources/june-2019-military-tools-for-arcgis.htm
- https://solutionsdev.arcgis.com/defense/help/coordinate-conversion/resources/june-2019-coordinate-conversion.htm

**Comment by lfunkhouser** [comment]
verified doc updated on solutionsdev and in PDFs (CC dev build 139, MT dev build 305)
