### ISSUE TITLE
Points from the List should display an empty View Details window, instead of saying "No Data"

### ISSUE THREAD

**Issue by dfoll** [Esri/coordinate-conversion-addin-dotnet#593]
### Background
Points that are added to the list using the Map Point tool, by default will not have any "attribute" information to them, but still have a coordinate to display in the title of the View Details window.
- For both ArcMap and ArcGIS Pro

### Current behavior
If you try to view details for a point that has no "attribute" information to it, it displays a window that say "No data available". This is a.) untrue, as there is a title/coordinate to display from what you clicked, and b.) very unsightly and not what is expected.
![image](https://user-images.githubusercontent.com/5322669/54540489-76362180-496e-11e9-9a61-0432db496a71.png)

### Expected behavior
![image](https://user-images.githubusercontent.com/5322669/54541622-a4b4fc00-4970-11e9-91b9-65e890627d73.png)
_only a mock up, text size and content may change_

**Comment by csmoore** [comment]
View Details gives expected message now:

Pro:

![image](https://user-images.githubusercontent.com/3090809/57870600-6b183a00-77d5-11e9-92b2-8fa4c7f7cdd3.png)

ArcMap:

![image](https://user-images.githubusercontent.com/3090809/57870653-808d6400-77d5-11e9-94d4-379109589925.png)

Note: As noted in https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/590#issuecomment-493126056 - the default size is somewhat large - in Pro if you resize the window, close, and reopen, the last window size is used, but not in ArcMap (so the large size is more of an issue in ArcMap)

**Comment by dfoll** [comment]
![image](https://user-images.githubusercontent.com/5322669/59921887-28add280-93fd-11e9-99de-80ede3ead162.png)
ArcMap 10.4.1

**Comment by dfoll** [comment]
- updated to CC june release topic
- updated MT june release topic
-

**Comment by dfoll** [comment]
- https://solutionsdev.arcgis.com/defense/help/coordinate-conversion/resources/june-2019-coordinate-conversion.htm
- \\...\DefenseSolutions\CoordinateConversion\Dev\140\
- https://solutionsdev.arcgis.com/defense/help/military-tools/resources/june-2019-military-tools-for-arcgis.htm
- \\...\DefenseSolutions\MilitaryToolsforArcGIS\Dev\309\

**Comment by lfunkhouser** [comment]
Doc verified on CC 143, MT 314, solutionsstg
