### ISSUE TITLE
Export to KMZ output symbols are too small

### ISSUE THREAD

**Issue by BobBooth** [Esri/coordinate-conversion-addin-dotnet#595]
The symbols for the output points should be larger when coordinates collected by coordinate conversion are exported to KMZ.
To reproduce:  
1. Add some output formats.
2. Click on the map in several locations to collect coordinates.
![image](https://user-images.githubusercontent.com/3801392/54617406-9b429700-4a37-11e9-8ced-fe350858cf0a.png)
The symbols in Pro are large enough to be easily visible.
3. Click Export.
4. Choose KMZ output.
5. Choose an output location and export.
6. Open the KMZ in ArcGIS Earth.
![image](https://user-images.githubusercontent.com/3801392/54618237-0fca0580-4a39-11e9-9c31-83185e168287.png)
The points are barely visible.
7. Export the points to shapefile.
8. In contents, choose an 8pt red circle.
![image](https://user-images.githubusercontent.com/3801392/54618835-0beab300-4a3a-11e9-8f36-18c79ed5bc06.png)
This approximates the symbol that is used by the addin for display of collected points.
9. Use the Layer to KML GP tool to export the layer, add to ArcGIS Earth.
The symbols are more visible.
![image](https://user-images.githubusercontent.com/3801392/54619486-0e014180-4a3b-11e9-8d27-d74765d1cd5f.png)

**Comment by dfoll** [comment]
@saip will share .kmz that is produced from the updates to see if they are acceptable in both ArcMap/ArcGIS Pro. We will need to get an answer back to them about that

**Comment by saip** [comment]
@dfoll Here is the compressed KMZ file [test.zip](https://github.com/Esri/coordinate-conversion-addin-dotnet/files/3486476/test.zip) that was generated after the updates from the CC addin. The points show symbol bigger than it used to show earlier in ArcGIS Earth, but it is not exactly of the same size you see in ArcMap/ArcGIS Pro.

We see that ArcGIS Earth renders the point symbol smaller for same data compared with how it is rendered in ArcMap. Please check and confirm whether the increase in symbol size is ok now.

**Comment by dfoll** [comment]
@saip thanks for sharing the kmz. one question, that I want to make sure of. Were there any changes to how the graphics render when using the Coordinate Conversion add-in? I understand all these changes were made to the export process, but I just wanted to confirm that we did not make any changes to the way that the original graphics that you get in CC from using the Map Point Tool display.

@lfunkhouser @csmoore @kgonzago  The changes needed to satisfy the original issue of making the points display at a reasonable size when first brought into Earth, also make them display a little bit larger when the same kmz is brought into ArcMap/ArcGIS Pro.  I did my best with the screenshot below to show the difference. @saip and @CTLocalGovTeam are waiting on our approval to go forward with this.

![image](https://user-images.githubusercontent.com/5322669/62865141-9ed30500-bcdb-11e9-80a4-0c1beaa9720f.png)

**Comment by saip** [comment]
@dfoll Correct, we made no changes to graphics rendering in the CC add-in. Only updated the size of the graphic(s) exported to KMZ.

**Comment by dfoll** [comment]
ok, it is good then, unless @lfunkhouser has anything to add

**Comment by dfoll** [comment]
G-Doc label can be removed after publishing

**Comment by dfoll** [comment]
Verified
![image](https://user-images.githubusercontent.com/5322669/63356263-7c716500-c335-11e9-950e-91d60bc53bcf.png)

**Comment by dfoll** [comment]
### Doc review:
- [ ] [Coordinate Conversion October Resources](https://solutionsdev.arcgis.com/defense/help/coordinate-conversion/resources/october-2019-coordinate-conversion.htm)
- [ ]  [Military Tools October Resources](https://solutionsdev.arcgis.com/defense/help/military-tools/resources/october-2019-military-tools-for-arcgis.htm)
- [ ] \DefenseSolutions\CoordinateConversion\October2019\Dev\167\
- [ ] \DefenseSolutions\MilitaryToolsforArcGIS\October2019\Dev\332\

**Comment by lfunkhouser** [comment]
Doc verified
