### ISSUE TITLE
Output coordinate layer should show coordinate value as header, display field in popup, not 0

### ISSUE THREAD

**Issue by BobBooth** [Esri/coordinate-conversion-addin-dotnet#596]
If you collect coordinates and export to KMZ, the output popup in ArcGIS Earth is headed with "0" values for all coordinates that you click, and if you expand the KMZ item in the Layer List, all of the points have a "0" beside them.  This seems to be coming from the ID field, which is set to "0".
![image](https://user-images.githubusercontent.com/3801392/54621510-3ccce700-4a3e-11e9-8a35-7b1ac9dc060e.png)

Since we know that all output is going to have a "coordinate" field, we should set the layer for the output symbology to use "coordinate" as the primary display field, like this:
![image](https://user-images.githubusercontent.com/3801392/54622065-3be88500-4a3f-11e9-818e-e1a1ff8117c8.png)

This would match the planned behavior for the Details window (https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/591).

Interestingly, when you export from ArcMap (10.3.1) with the same build, you do get this behavior.
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/100fb36c-5fe2-4b83-b730-b4d6150d59a0)

**Comment by csmoore** [comment]
Seems to be just my week, but I'm having problems getting KMZ export to work on Pro 2.4, it seems like a threading issue, but looking into

**Comment by csmoore** [comment]
Tested exporting from Pro and Arcmap and Legend and Pop-up looks good now - created new issue #604 for new crash observed on export at **Pro 2.4**:

![image](https://user-images.githubusercontent.com/3090809/57937085-3f5b8980-7893-11e9-97d7-a501195a0f5b.png)

**Comment by dfoll** [comment]
- https://solutionsdev.arcgis.com/defense/help/coordinate-conversion/resources/june-2019-coordinate-conversion.htm
- https://solutionsdev.arcgis.com/defense/help/military-tools/resources/june-2019-military-tools-for-arcgis.htm
- \\...\DefenseSolutions\CoordinateConversion\Testing\CTLocalGovTeam-dev\130\
- \\...\DefenseSolutions\MilitaryToolsforArcGIS\Dev\292\

**Comment by lfunkhouser** [comment]
Doc verified - website and PDFs in (MT 305 and CC 139)
