### ISSUE TITLE
Provide checkbox to show +/- for custom formatting

### ISSUE THREAD

**Issue by dfoll** [Esri/coordinate-conversion-addin-dotnet#600]
### Current behavior
When a user is providing a custom format for DD/DMS/DDM they have the option to remove the N/S/E/W hemisphere designator from the coordinates. If the user does this, in the list, there is no indicator of what what hemisphere the coordinate is in.
![image](https://user-images.githubusercontent.com/5322669/56375675-2dbf8d00-61d4-11e9-89c9-4b5de9b8e520.png)

### Expected behavior
Provide checkbox in the custom formatting area for DD/DMS/DDM to "Show + for N/E hemisphere" and a checkbox to "Show - for S/W hemisphere"
![image](https://user-images.githubusercontent.com/5322669/56376738-ae7f8880-61d6-11e9-8952-4508b0d22746.png)
![image](https://user-images.githubusercontent.com/5322669/56376983-5006da00-61d7-11e9-8d8c-ebf9460fbe38.png)
![image](https://user-images.githubusercontent.com/5322669/56377108-9f4d0a80-61d7-11e9-9d9f-5f299f0bbd15.png)
![image](https://user-images.githubusercontent.com/5322669/56377164-c4da1400-61d7-11e9-8724-c09fffbf17c9.png)

Required for ArcMap 10.3.1 -10.7.1 and ArcGIS Pro 2.1 - 2.4

**Comment by saip** [comment]
@dfoll As per our discussion this morning, we are also implementing the case of hemisphere designators (N,S,E,W, n,s,e,w) also are not allowed to be added by user in the custom format textbox. Instead, user will be allowed to choose the display of hemisphere designators with a checkbox.

**Comment by dfoll** [comment]
Feedback:
-  "Show N/S/E/W for hemisphere" should be on by default
-  If "Show N/S/E/W for hemisphere" is checked, the top two should be grayed out

**Comment by dfoll** [comment]
I have spoken to @saip he has implemented exclusivity for "Show N/S/E/W" and "Show +/-" by making each of them a radio button. When you select the "Show +/-" radio button, the user will then have the option via checkboxes to "Show + for N/E" and/or "Show - for S/W"

@saip and crew will also provide a preview of what the coordinate string based on whichever radio button and/or checkboxes you have selected. There is one important caveat to this functionality that I am accepting for this release.
- if you have a radio button selected and do some custom formatting, the custom formatting will be lost if you switch to the other radio button. This is because each radio button comes with it's own preview string that is populated as a starting point when you select a radio button or checkbox.

![image](https://user-images.githubusercontent.com/5322669/59766662-b0b1a200-926e-11e9-81d9-60cabadc66fe.png)
one change to this screenshot is that @saip with be adding a "/" between NSEW for the  "Show NSEW" radio button.

**Comment by saip** [comment]
@dfoll If we implement as discussed in the comment above, preview string would stay static and would not be updated when user types in additional characters in the format textbox. The string would only be updated when user switches selection of radio buttons/checkboxes. So, as discussed yesterday we are implementing it without the caveat mentioned above. The implementation now would be

- Custom formatting will be retained even after switching selections of radio buttons/checkboxes
- Also, we are working on displaying "**+/-**" when both "Show +" and "Show -" checkboxes are checked.
   - if the "Show +" checkbox is marked, the string will preview as
      `+Y0.0##### +X0.0#####`
   - if the "Show -" checkbox is marked, the string will preview as
     `-Y0.0##### -X0.0#####`
   - if both the "Show +" and "Show -" checkboxes both marked, the string will preview as
     `+/-Y0.0##### +/-X0.0#####`

![image](https://user-images.githubusercontent.com/2205106/59906152-a08ff300-9425-11e9-8a91-59b1a8d7e216.png)

**Comment by dfoll** [comment]
This looks good.
- [ ] When user does not select any custom formatting, N/S/E/W are displayed for lat/lon coordinates
- [ ] When custom formatting for lat/lon, you can show
   - [ ] N/S/E/W as hemisphere indicators   OR
   - [ ] +/-    
   - [ ] the two choices are exclusive
- [ ] When showing +\- you can show
   - [ ] + for N/E   AND/OR
   - [ ] - for S/W
- [ ] A preview is show
   - [ ] preview updates as the custom input box is edited

**Comment by dfoll** [comment]
@saip this is the bug i noted in the previous comment.

When you are using custom formatting and using either "Show N/S/E/W" or "Show +/-" when you switch the coordinate order to longitude latitude, the hemisphere prefix [or] suffix get confused about where they should be place and place themselves together on one end of the other of the coordinate pair.

![image](https://user-images.githubusercontent.com/5322669/60046776-2ca85180-9696-11e9-9bc6-8b4a295ba6c0.png)
![image](https://user-images.githubusercontent.com/5322669/60046910-7d1faf00-9696-11e9-8e08-8a65453630e6.png)
Decimal degrees listed as lat/lon formatted to show +/- as hemisphere indicators  - Correct!

![image](https://user-images.githubusercontent.com/5322669/60046993-a2acb880-9696-11e9-91de-391f06b45a67.png)
Decimal degrees listed as lat/lon formatted to show N/S/E/W as hemisphere indicators - Correct!

![image](https://user-images.githubusercontent.com/5322669/60047258-47c79100-9697-11e9-8dfc-c2a980981e60.png)
Decimal degrees listed as lon/lat formatted to show +/- as hemisphere indicators - in the preview the prefix for both lon and lat are stuck together at the beginning of the coordinate pair

![image](https://user-images.githubusercontent.com/5322669/60047106-e43d6380-9696-11e9-88da-31265af6aa07.png)
Decimal degrees listed as lon/lat formatted to show N/S/E/W as hemisphere indicators - in the preview the suffix for both lon and lat are stuck together at the end of the coordinate pair

**Comment by dfoll** [comment]
Two significant issues I found that i referenced in [this comment](https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/600#issuecomment-505148542)

**Comment by lfunkhouser** [comment]
@CTLocalGovTeam do you have an update on this issue?

**Comment by dfoll** [comment]
@saip @CTLocalGovTeam tested CC build 151 built from [this branch](https://github.com/Esri/coordinate-conversion-addin-dotnet/tree/CTLocalGovTeam-dev) looks good. thanks!
