### ISSUE TITLE
List box should be populated in chronological order

### ISSUE THREAD

**Issue by dfoll** [Esri/coordinate-conversion-addin-dotnet#601]
### Current behavior
The Coordinate Conversion List populates coordinates in reverse chronological order with the newest coordinates being placed at the top of the List.

### Expected behavior
The Coordinate Conversion List should populate in chronological order with the newest point at the bottom of the List.

Requested for ArcMap 10.4.1 - 10.7.1 and ArcGIS Pro 2.2 - 2.4

**Comment by dfoll** [comment]
This issue supersedes #582

**Comment by dfoll** [comment]
Verified working as requested.

**Comment by dfoll** [comment]
- https://solutionsdev.arcgis.com/defense/help/coordinate-conversion/resources/june-2019-coordinate-conversion.htm
- https://solutionsdev.arcgis.com/defense/help/military-tools/resources/june-2019-military-tools-for-arcgis.htm
- \\...\DefenseSolutions\CoordinateConversion\Testing\CTLocalGovTeam-dev\129\
- \...\DefenseSolutions\MilitaryToolsforArcGIS\Dev\291\

**Comment by lfunkhouser** [comment]
Tested on MT dev 307 and CC dev 139
Verified on solutionsdev website
