### ISSUE TITLE
Coordinate Output Settings/Configuration not saved at Pro 2.4

### ISSUE THREAD

**Issue by csmoore** [Esri/coordinate-conversion-addin-dotnet#605]
On **Pro 2.4** when you add and configure Output Coordinate formats, these should be saved in-between Pro runs until you hit the Reset button.  At Pro 2.4 these are no longer saved in-between runs.

Similar to Issue: https://github.com/Esri/military-symbology/issues/374 - Pro 2.4 no longer allows files to be saved to the Assembly Cache (`C:\Users\{user}\AppData\Local\ESRI\ArcGISPro\AssemblyCache`):

Repro steps:

0. On **Pro 2.4**
1. Launch Pro, Create a project, Launch Coordinate Conversion Addin
2. In the Output Group, use the "+" Add button to "Add New Output Coordinate Format"
3. Add several new formats (ex: DD, MGRS)
4. Close Pro
5. Launch Pro, reopen project oordinate Conversion Addin
6. There are no Output Formats in the Output Group (these should be the same as those added in Step 3), 

![image](https://user-images.githubusercontent.com/3090809/58052080-e0f80a80-7b21-11e9-975b-e295fc6cc405.png)

**Comment by csmoore** [comment]
Addressed in PR #606

**Comment by dfoll** [comment]
verified issue using Pro 2.4 build B1 with MT (released build 227)

**Comment by dfoll** [comment]
verified issue is fixed using Pro 2.4 B1 with CC (build 95)

**Comment by dfoll** [comment]
because we have never released on 2.4 and this issue is 2.4 specific, I do not think that we need to doc this issue

**Comment by lfunkhouser** [comment]
now saved to ...\Documents\ArcGIS

**Comment by csmoore** [comment]
A later PR ( #612 ) seems to have accidentally overwrote this fix ( in #606 )  - at 
https://github.com/Esri/coordinate-conversion-addin-dotnet/pull/612/files#diff-72fc8a70d9ede6e7ce33f30c4e19a45eL158 

Just need to reapply this fix

**Comment by dfoll** [comment]
Observed problem with MT 344 on Pro, did not observe on ArcMap.

With CC build 173 (csm-605-redo) this looks good on Pro 2.4. and  ArcMap 10.4.1 (functionality worked before and after on ArcMap)

**Comment by dfoll** [comment]
Rebuilt CC and MT from dev after #635 was merged

- \DefenseSolutions\CoordinateConversion\October2019\Dev\174\
- \DefenseSolutions\MilitaryToolsforArcGIS\October2019\Dev\345\
