### ISSUE TITLE
Points [graphics] in the map display cannot be selected

### ISSUE THREAD

**Issue by dfoll** [Esri/coordinate-conversion-addin-dotnet#608]
## Current behavior
When points [graphics] are in the map display, either from the Map Point Tool, or an imported CSV, those points cannot be selected with the Select Point tool.

## Expected behavior
When points [graphics] are in the map display, either from the Map Point Tool, or an imported CSV, those points can be selected using the Select Point tool. When they are selected using the Select Point tool, the graphic should highlight with the typical green halo, and the coordinate should be highlighted in the list.

Found on ArcGIS Pro 2.3 and 2.4 build 19590 CC build 94 
This was also observed with ArcMap 10.3.1 CC build 94

Did not observe on ArcMap with the released version of MT (227) but did observe on ArcGIS Pro even with the released version of Military Tools

**Comment by dfoll** [comment]
This issue was was found while testing issue #586

**Comment by dfoll** [comment]
@saip we would like to discuss if there will be time to bring in this one and #600 for this release.

@lfunkhouser fyi

**Comment by dfoll** [comment]
Tested this with @ljuru . Selecting points in the map is working as expected. Once a point is highlighted though, it cannot be clicked again to unselect it. I would expect that both selecting/unselecting points is part of the way this would operate. @saip are you able to deliver that as part of this issue, or is that a larger effort?

**Comment by dfoll** [comment]
- https://solutionsdev.arcgis.com/defense/help/coordinate-conversion/resources/june-2019-coordinate-conversion.htm
- https://solutionsdev.arcgis.com/defense/help/military-tools/resources/june-2019-military-tools-for-arcgis.htm
- \\...\DefenseSolutions\CoordinateConversion\Testing\CTLocalGovTeam-dev\132\
- \\...\DefenseSolutions\MilitaryToolsforArcGIS\Dev\294\

**Comment by lfunkhouser** [comment]
Tested on MT dev 307 and CC dev 139
Verified on solutionsdev website
