### ISSUE TITLE
Crash when exporting to KMZ on ArcGIS Pro 2.3

### ISSUE THREAD

**Issue by dfoll** [Esri/coordinate-conversion-addin-dotnet#611]
## Current behavior
A crash has been found by @CTLocalGovTeam involving exporting to KMZ and the Edit Properties button.

When you open a new project if you do not first open the Edit Properties window before exporting to KMZ, the KMZ you intend to export will not be created in the destination, and if you click the Edit Properties button after the export, ArcGIS Pro will crash.

### Repro steps:
0. Install ArcGIS Pro 2.3 + Military Tools 3.3.1
1. Using Coordinate Conversion add some points to the map
2. Click Export on the bottom of the Coordinate Conversion pane
3. Select the KMZ radio button
4. Give the KMZ a name and click save.
5. Navigate in the catalog pane to the location where you saved the KMZ, note that the KMZ was not actually created.
6. Click the Edit Properties button (on the Coordinate Conversion pane).
**_ArcGIS Pro crashes_**

0. Install ArcGIS Pro 2.3 + Military Tools 3.3.1
1. Using Coordinate Conversion add some points to the map
2. Open and close the Edit Properties window from the Coordinate Conversion window (do not need to actually change anything on the window, just open and close it).
3. Click Export on the bottom of the Coordinate Conversion pane
4. Select the KMZ radio button
5. Give the KMZ a name and click save.
6. Navigate in the catalog pane to the location where you saved the KMZ, note that the KMZ is created.
7. Click the Edit Properties button (on the Coordinate Conversion pane). Crash listed above does not happen.

### Additional notes:
- Observed on ArcGIS Pro 2.3 with released version of MT/CC
- I observed that this behavior relates to the "lifespan" of an ArcGIS Pro project... If you go through the steps to make sure it does not crash, but do not save, if you open the same project again, the crash will occur.
- Did not observe on ArcMap 10.3.1/10.4.1

## Expected behavior
When exporting to KMZ the user should not need to open the Edit Properties window before trying to export.

**Comment by dfoll** [comment]
This was fixed in [this commit](https://github.com/Esri/coordinate-conversion-addin-dotnet/pull/602/commits/10c20d25ed6d0b6ee07788d030fe9d835c0ba067) by @CTLocalGovTeam team as part of the [delivery for Coordinate Conversion](https://github.com/Esri/coordinate-conversion-addin-dotnet/pull/602)

**Comment by dfoll** [comment]
With dev build 113 I am still experiencing this crash

**Comment by dfoll** [comment]
CC build 114 seems to have this fix back in. @saip please consider include this issue as part of the upcoming CC delivery. When we test for merging that PR, we can close this issue

**Comment by saip** [comment]
@dfoll We are working on issue 600 updates we discussed this morning. We will raise a pull request soon.

**Comment by csmoore** [comment]
Tested on Pro 2.3 this seems to be resolved for the case where the points have been created by *either* (1) clicking on the map or (2) import from a file. 

However it seems like if I *mix/combine* (1) map click points and (2) file import points in the output list. I either don't get a KMZ file created or I get an error.

![image](https://user-images.githubusercontent.com/3090809/58590722-b3524600-8232-11e9-8fd6-8441f5a5e451.png)

**Comment by dfoll** [comment]
Tested on ArcGIS Pro 2.3 with CC build 127 (created from [this branch](https://github.com/Esri/coordinate-conversion-addin-dotnet/tree/CTLocalGovTeam-dev). Fix in #612 .

I cannot repro the problem with my original repro steps or @csmoore updated repro steps

**Comment by dfoll** [comment]
- https://solutionsdev.arcgis.com/defense/help/coordinate-conversion/resources/june-2019-coordinate-conversion.htm
- https://solutionsdev.arcgis.com/defense/help/military-tools/resources/june-2019-military-tools-for-arcgis.htm
- \\...\DefenseSolutions\CoordinateConversion\Testing\CTLocalGovTeam-dev\128\
- \\...\DefenseSolutions\MilitaryToolsforArcGIS\Dev\290\

**Comment by lfunkhouser** [comment]
Tested on MT dev 307 and CC dev 139
Verified on solutionsdev website
