### ISSUE TITLE
Progress dialog does not close on import with custom format

### ISSUE THREAD

**Issue by csmoore** [Esri/coordinate-conversion-addin-dotnet#619]
There is a scenario where the Pro Progress Dialog is shown and not closed when the operation is complete:

0. Start Pro 
1. Set Input Properties: Edit Properties Button / Form
    a. Display Coordinate: DD 
    b. Formats: Custom
    c. No other changes needed 
    d. Click OK
2. Import Coordinates:
    a. Import TabletoPoint_small.csv (data attached to this issue) - [TabletoPoint_small.zip](https://github.com/Esri/coordinate-conversion-addin-dotnet/files/3322718/TabletoPoint_small.zip)
    b. X Field: x, Y Field y, Additional Fields: title
    c. Click OK
3. Progress Dialog "Processing.. Please wait" is shown but never goes away and user is not able to use Pro because the form is always active

Tested on Pro 2.4.19948

@dfoll found this issue - I just wrote up while we were looking at the issue together

**Comment by dfoll** [comment]
i could no longer reproduce the hang up with CC 146 built from [this branch](https://github.com/Esri/coordinate-conversion-addin-dotnet/tree/csm-619-progress-wont-go-away)

**Comment by dfoll** [comment]
- https://solutionsdev.arcgis.com/defense/help/coordinate-conversion/resources/june-2019-coordinate-conversion.htm
- \\...\DefenseSolutions\CoordinateConversion\Dev\149\
- https://solutionsdev.arcgis.com/defense/help/military-tools/resources/june-2019-military-tools-for-arcgis.htm
- https://solutionsdev.arcgis.com/defense/help/military-tools/resources/june-2019-military-tools-for-arcgis.htm

**Comment by lfunkhouser** [comment]
doc verified on solutionsdev, MT dev build 315 and CC 149
