### ISSUE TITLE
Add-in fails if .mxd opens with Coordinate Conversion pane already open

### ISSUE THREAD

**Issue by dfoll** [Esri/coordinate-conversion-addin-dotnet#626]
# Repro steps
1. Open ArcMap 
2. Ensure that there is no basemap
3. Ensure that Coordinate Conversion is not open
4. Save the .mxd as something such as CoordinateConversionTest.mxd
5. Close CoordinateConversionTest.mxd
6. Open CoordinateConversionTest.mxd
- .mxd should have opened with no basemap and Coordinate Conversion pane not open
7. Add a basemap
8. Open Coordinate Conversion pane
9. Add some points, points add successfully.
10. Clear points
11. Save CoordinateConversionTest.mxd
12. Close CoordinateConversionTest.mxd
13. Open CoordinateConversionTest.mxd
   - .mxd should have opened with a basemap and Coordinate Conversion pane open
14. Try to add some points
   - you get a message "Please add a basemap or layer to the map" even though there is a  basemap in the .mxd

# Additional info
- Military Tools 3.5.0.317
   - ArcMap 10.7.0.10450
- could not reproduce in ArcGIS Pro. Even if you choose to start a project just with Catalog and Coordinate Conversion pane open in the project, then add a map this is not reproducible.

**Comment by csmoore** [comment]
Addressed in PR #628

**Comment by dfoll** [comment]
document #672 at the same time

**Comment by dfoll** [comment]
Tested on 10.4.1 with CC build 163. Confirmed repro steps above no longer have the problem listed, as well as another case. Also tested the case of if you intentionally tried to use CC with no basemap or layer, you would be stuck not being able to use CC even after you added a basemap or layer. This no longer happens.

**Comment by dfoll** [comment]
- [ ] update October resources topic
- [ ] publish Resources 
- [ ] publish pdf
- [ ] build .zip

**Comment by dfoll** [comment]
### Doc review:
- [ ] [Coordinate Conversion October Resources](https://solutionsdev.arcgis.com/defense/help/coordinate-conversion/resources/october-2019-coordinate-conversion.htm)
- [Coordinate Conversion homepage](https://solutionsdev.arcgis.com/defense/help/coordinate-conversion/)
- Coordinate Conversion build location
- [Military Tools October Resources]()
- Military tools build location

**Comment by csmoore** [comment]
Verified:
 
1. Coordinate Conversion October Resources - bug added to table
2. Coordinate Conversion homepage - Added to Releases Table
3. Coordinate Conversion .pdf - bug added to table
4. Military Tools October Resources - bug added to Issues addressed
5. Military Tools for ArcGIS Release Notes.pdf - bug added to table
6. Defense What's new - CC added to October 2019
