### ISSUE TITLE
Rename buttons for importing and exporting an Output list

### ISSUE THREAD

**Issue by dfoll** [Esri/coordinate-conversion-addin-dotnet#627]
### Current behavior
The button labels to import or export the Output section list are confusing because they look the same as the buttons to import or export from the List section.

![image](https://user-images.githubusercontent.com/5322669/61642872-c18b7400-ac6f-11e9-8d54-cd6da575e732.png)

### Expected behavior
The button labels for the Output section should be changed to `Open` and `Save'.
- `Open` should replace the Import button but the functionality should be the same. It is the button used to open a previously saved configuration file for the Output section.

- `Save` should replace the Export button but the functionality should be the same. It is the button used to save a configuration file for the Output section.

### Notes:
- requested for ArcMap and ArcGIS Pro. 
- Should work for 
   - Arcmap 10.4.1-10.7.1
   - ArcGIS Pro 2.2-2.5

**Comment by dfoll** [comment]
Need to add a topic for this functionality as  well

**Comment by dfoll** [comment]
G-Doc label can be removed after publishing

**Comment by dfoll** [comment]
Verified
![image](https://user-images.githubusercontent.com/5322669/63356468-d83bee00-c335-11e9-8ac9-2c2509de2b14.png)

**Comment by dfoll** [comment]
- [ ] [Whats new](https://solutionsdev.arcgis.com/defense/what-is-new/) (after [PR 7999](https://github.com/ArcGIS/arcgis-solutions-website/pull/7999) is merged and DEV is built)

**Comment by lfunkhouser** [comment]
verified:
PDFs MT 341, CC 168
/defense/help/military-tools/workflows/open-or-save-output-setup.htm
/defense/help/coordinate-conversion/workflows/open-or-save-output-setup.htm
online resources for CC and MT
