### ISSUE TITLE
Holistic : Crash when switching in CC edit properties tab from display coordinate > symbology

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/coordinate-conversion-addin-dotnet#631]
Looks like there is a crash when navigating in the edit properties tab of CC add-in. 

This info came in from holistic testing on 8/9 of Pro for Intel.

To reproduce:
- in pro intel, open a project where you have point data on the map, or add point data into a new project
- in pro intel, open CC pane from the map tab
- use the map point tool to add a coordinate in the CC dialog and click the map when it snaps to an existing point feature location
- click the edit properties button to open the edit properties dialog
- switch from the display coordinate tab to the symbology tab; this is where crash is experienced. Take a look at screenshot for more context:
![image](https://user-images.githubusercontent.com/13024357/62895369-9bec0a80-bd03-11e9-83e7-f3e6e42a8602.png)

It looks like the loading dialog is happening for symbology before the crash occurs.

**Comment by csmoore** [comment]
I have the environment setup (Pro 2.5.21278, ArcGISIntel 1335) but I am having trouble reproducing this issue.


![image](https://user-images.githubusercontent.com/3090809/62960954-caccb400-bdc9-11e9-8dee-623f752c713e.png)

**Comment by Dbarnes1** [comment]
@csmoore I can try and reproduce as well, I'll look and get in contact with the tester from holistic and share info here.

**Comment by Dbarnes1** [comment]
@csmoore I am able to get a crash, but it is inconsistent. I'll keep trying and let you know if I have any more detailed repro steps

**Comment by dfoll** [comment]
Tried reproducing using steps listed in original issue. Crash was inconsistent. The one time out of eight that I saw the crash was not on the development version of AP4I or MT. I wouldn't have seen this crash (it was the second time I tried) had I not thought of something I wanted to check out and gone back to scenario I had already tested.

### Pro 2.4 (AP4I not installed)(MT 339)
- could not repro
### Pro 2.4 w/AP4I 2.4 (MT 317)
- (1st attempt) could not repro
- (2nd attempt) crash
- (3rd attempt) could not repro
### Pro 2.4 w AP4I 2.4 (MT 339)
- could not repro
### Pro 2.5.0.21502 (AP4I not installed)(MT 339)
- could not repro
### Pro 2.5 w/AP4I 2.5.1394 (MT 317)
- could not repro
### Pro 2.4 wAP4I 2.5.1394 (MT 339)
- could not repro
