### ISSUE TITLE
Image of Coordinate Tool in README does not match current version.

### ISSUE THREAD

**Issue by pshowalter** [Esri/coordinate-conversion-addin-dotnet#66]
Current version - downloaded today:
![image](https://cloud.githubusercontent.com/assets/6842145/13011219/be73ce5a-d173-11e5-8e2a-cfc3826f698d.png)

README graphic on repo
![image](https://cloud.githubusercontent.com/assets/6842145/13011260/f2657a06-d173-11e5-98d8-8b6e64ff6b85.png)

**Comment by topowright** [comment]
Update the readme to show the correct image for ArcMap 10.3.1 and for ArcGIS Pro 1.2

**Comment by topowright** [comment]
@pshowalter has this been fixed?

**Comment by pshowalter** [comment]
It changed a couple of times.

Now needs to be updated for new "Coordinate Conversion Window" banner.

![image](https://cloud.githubusercontent.com/assets/6842145/13531389/5332fb66-e1f4-11e5-9a95-5bf97be148c2.png)

**Comment by pshowalter** [comment]
README graphic needs  updating.  Still has "Coordinate Tool" and one of the buttons has been removed.
![image](https://cloud.githubusercontent.com/assets/6842145/14079346/e6349526-f4ca-11e5-9a32-db5359466e42.png)

**Comment by jmccausland** [comment]
@pshowalter @topowright can we just update the screenshots instead of creating an issue every time?

**Comment by pshowalter** [comment]
Updated.
