### ISSUE TITLE
Use the "Flash" Call Inherent to ArcMap for Flash button

### ISSUE THREAD

**Issue by mcalamito** [Esri/coordinate-conversion-addin-dotnet#68]
Customer Feedback from on-site visit on 18FEB2016. Currently the Flash button pans-to and creates a graphic at the coordinate location. What if the graphic is the same symbology as a feature at the same location? When clicking the "Flash" button, the user thought it would act just like the inherent "Flash" call in ArcMap. 

This isn't identical to Issue #67, but does overlap when speaking about the graphic being placed in the Data Frame.

**Comment by topowright** [comment]
Remove the creation of graphic and only have a flash for the given location that was entered. Flash should work the same way that flash works for the Geocoding tool

**Comment by jmccausland** [comment]
The flash has been updated to behave like the geocoding "flash"

@mcalamito please verify

**Comment by mcalamito** [comment]
reviewed and verified. closing ticket.
