### ISSUE TITLE
Change the name of the tool and the repo

### ISSUE THREAD

**Issue by topowright** [Esri/coordinate-conversion-addin-dotnet#70]
- [x] The add-in should be called Coordinate Conversion ArcMap 10.3.1
- [x] The add-in should be called Coordinate Conversion ArcGIS Pro 1.2
- [x] The repo should be called coordinate-conversion-addin

**Comment by jmccausland** [comment]
FYI, @topowright, I do not have permissions to change the name of a public repo

**Comment by csmoore** [comment]
I believe I do have permission - let me know if you want me to change:

This would be the only repo that uses the name "add-in" versus "addin" if you wanted to be consistent with the existing ones: https://github.com/Esri?utf8=%E2%9C%93&query=addin

**Comment by pshowalter** [comment]
When the naming issue is resolved, make sure to catch the typo on 
Use:
**coordinate**-conversion-add-in
not:
**coordiante**-conversion-add-in

**Comment by mfunk** [comment]
@pshowalter that stuff can be edited in-line. I've changed it.

**Comment by mfunk** [comment]
I'm checking off the repo rename.

**Comment by jmccausland** [comment]
@topowright please verify
