### ISSUE TITLE
A complete description for each of the add-ins

### ISSUE THREAD

**Issue by topowright** [Esri/coordinate-conversion-addin-dotnet#71]
- [x] ArcGIS Pro 1.2
- [x] ArcMap 10.3.1

**Comment by mfunk** [comment]
This is the description seen in the ArcMap Add-In Manager.

**Comment by jmccausland** [comment]
@topowright please verify and close

**Comment by topowright** [comment]
This needs to be verified.

**Comment by topowright** [comment]
We can see the description in ArcMap, but cannot find the description in ArcGIS Pro.

**Comment by topowright** [comment]
Description can be seen within the Project tab.
