### ISSUE TITLE
Coordinate Tool - Readme - Custom Formatters - Spatial Reference - not documented

### ISSUE THREAD

**Issue by pshowalter** [Esri/coordinate-conversion-addin-dotnet#75]
The Coordinate Tool - Readme (and other doc) - Custom Formatters - Spatial Reference is not documented.  Is the intent of this tool to allow user to change aspects of the converted coordinates, such as datum?  Changed the data to GCS_OSGB_1936 as used in issue  https://github.com/Esri/coordinate-tool-addin-dotnet/issues/23 - results are inconclusive.

![image](https://cloud.githubusercontent.com/assets/6842145/13436432/3a729242-dfad-11e5-8790-a926a4a01381.png) 

![image](https://cloud.githubusercontent.com/assets/6842145/13436492/84958fbe-dfad-11e5-8416-9f94d93fa265.png)

**Comment by jmccausland** [comment]
This has been removed
