### ISSUE TITLE
Coordinate Tool - erases user graphics when Flash is clicked.

### ISSUE THREAD

**Issue by pshowalter** [Esri/coordinate-conversion-addin-dotnet#76]
If user adds graphics via Draw menu to the map, then clicks the Flash tool on Coordinate Calculator (Coordinate Tool), the users graphics are erased. Tested with point, poly, ellipse, line.
![image](https://cloud.githubusercontent.com/assets/6842145/13436901/7b06d672-dfaf-11e5-84d3-2a24f99977af.png) 
![image](https://cloud.githubusercontent.com/assets/6842145/13436919/941cb23a-dfaf-11e5-8e97-e529ce09a7e6.png)

**Comment by jmccausland** [comment]
@pshowalter please test and verify that this doesn't happen with the latest
