### ISSUE TITLE
Rename repo coordinate-tool-addin-dotnet to coordinate-conversion-addin-dotnet

### ISSUE THREAD

**Issue by mfunk** [Esri/coordinate-conversion-addin-dotnet#80]
@chinasio
@nicogis
@qjw2bqn
@Esriitalia

Follow direction from management the repository will be renamed to match name of the addin and will now be **coordinate-conversion-addin-dotnet**. This could cause issues with any existing forks, and it is therefore recommended that you re-fork the repository. 

Since there are no open Pull Requests, the only thing I would only like to do is drop any dead feature branches. @jmccausland can we remove any unused ones in the next hour or so?

**Comment by jmccausland** [comment]
@mfunk 
I have on PR I'd like to create before this name change

**Comment by jmccausland** [comment]
@mfunk I have merged my PR and removed all dead branches

**Comment by mfunk** [comment]
Got it. Done.
