### ISSUE TITLE
Rename the esriAddIn filename to ArcMapAddinCoordinateConversion

### ISSUE THREAD

**Issue by mfunk** [Esri/coordinate-conversion-addin-dotnet#82]
Rename the *esriAddIn* filename to **ArcMapAddinCoordinateConversion**.

Currently it is *ArcMapAddinCoordinateTool.esriAddIn* and I believe it should be consistent with the recent name changes.

**Comment by jmccausland** [comment]
@mfunk this was changed, please verify

**Comment by jmccausland** [comment]
closing, this is no longer a valid issue
