### ISSUE TITLE
NUnit/Automated test(s)

### ISSUE THREAD

**Issue by ACueva** [Esri/coordinate-conversion-addin-dotnet#90]
Please add and document JUnit tests for use in our daily builds.

Documentation can look similar to this repo(s):

https://github.com/Esri/solutions-widgets-wpf#getting-started-with-the-solution-widgets-wpf
https://github.com/Esri/joint-military-symbology-xml#getting-started-with-the-solution

**Comment by csmoore** [comment]
Looks like (for this repo at least) these are here: https://github.com/Esri/coordinate-conversion-addin-dotnet/tree/dev/source/CoordinateConversion/CoordinateConversionLibrary.Tests 

And just need some doc so Avi knows how to run with the build

**Comment by jmccausland** [comment]
After a successful build of Coordinate Conversion solution, you should be able to run the following command for unit testing:

`MSTest /testcontainer:CoordinateConversionLibrary.Tests.dll`  

This is usually done from a Developer command prompt, shortcut is found in `C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Tools\Shortcuts`

**Comment by jmccausland** [comment]
@ACueva we need unit tests added to Jenkins.  I've updated the readme to have unit test instructions also.

**Comment by jmccausland** [comment]
@ACueva @csmoore anything else needed for unit testing to work with Jenkins?

**Comment by csmoore** [comment]
Just where to find the tests and how to run & I see in the readme: https://github.com/Esri/coordinate-conversion-addin-dotnet#development-environment 

It looks like this isn't calling/triggering any SDK calls, ex. AOInitialize (ArcObjects) or Host.Initialize (Pro SDK) so we shouldn't have any of the x86/x64 configuration setting/issues so should be straightforward - @ACueva - just ping me if you want any help but it should be the same as when you call msbuild (vcvars.bat + MSTest.exe )

**Comment by dhagens** [comment]
Unit tests were added for [visibility-addin-dotnet ](https://github.com/Esri/visibility-addin-dotnet)

After a successful build of Visibility solution, you should be able to run the following command for unit testing:

  MSTest /testcontainer:ArcMapAddinVisibility.Tests.dll *

**Comment by ACueva** [comment]
Visibility and Coordinate tool tests implemented and passed:
http://<Jenkins Server>:8080/job/military-tools-for-arcgis-build/374/console

@csmoore please verify.

**Comment by jmccausland** [comment]
One final additon, [distance and direction](https://github.com/Esri/distance-direction-addin-dotnet)

**Comment by csmoore** [comment]
Sorry, didn't notice this was assigned to me - verified
