### ISSUE TITLE
Flash AND Pan-to When Enter is Pressed

### ISSUE THREAD

**Issue by mcalamito** [Esri/coordinate-conversion-addin-dotnet#95]
Direct Customer feedback - They would like to be able to Pan-to the coordinate entered when clicking the Enter button on the keyboard. If the coordinate they enter is out of the Data Frame View, they will never see it flashing. This occurs very often.

**Comment by pshowalter** [comment]
As an alternative, I would prefer that the behavior approximate ArcMap (Geocoding Input box, Find tool results, or Go To XY, and user would right click to view context that would allow Zoom To, Pan To, Flash.  I don't usually want the map to Pan if I have an AOI that I am working on with points scattered around.
![image](https://cloud.githubusercontent.com/assets/6842145/14494488/125496d4-0159-11e6-8692-e67f8d680f66.png)


 
![image](https://cloud.githubusercontent.com/assets/6842145/14494574/818906fc-0159-11e6-8969-7faab65c0e7c.png)

**Comment by jmccausland** [comment]
What we could do for now is if the point is outside the current map extent, pan to, then flash.  But if the point is already within the current map extent, just flash.

**Comment by mcalamito** [comment]
@jmccausland fantastic idea and would alleviate Patrick's concerns.

**Comment by topowright** [comment]
I think this is a good approach. I think if we get into the zoom levels that it might be seen as noise.

**Comment by jmccausland** [comment]
this has been addressed
